### ISSUE TITLE
ReaLearn main FX window, Mapping Panel UI seems not to respect OS window theme

### ISSUE THREAD

**Issue by GavinRay97** [helgoboss/realearn#136]
Not a big deal, and this is **a custom/unofficially patched Windows system theme**, but just thought I'd point this out:

![realearn-mapping-panel-theme-bug](https://user-images.githubusercontent.com/26604994/107276036-7a66fe80-6a20-11eb-875b-20d75b77b0f3.gif)

**Comment by NGF86** [comment]
This is also the same on Mac OS at the moment. Although it is a lot worse and isn't really usable since you can see very little after you click 'add one'

**Comment by helgoboss** [comment]
@GavinRay97 Cool, how did you get this look? I want it, too :)

Yes, both the macOS and Windows issues have the same cause. Fixing ASAP.

**Comment by helgoboss** [comment]
@GavinRay97 On macOS, it's fixed. For Windows, I'm trying to find the correct way to determine when to use a dark background color. Any chance you can point me into the right direction with the Win32 API? AFAIK, what you use is not some kind of official dark mode but rather a custom theme, so I would probably need to determine the most relevant theme background color. Once I have that, I could decide whether to paint a dark or a bright background color.

A quick alternative would be to just use the default color, but then the mapping rows would look as boringly grey as they looked in the previous version.

**Comment by GavinRay97** [comment]
Hey @helgoboss =D

Yeah it's a really nice theme, especially with dark REAPER themes, it hides all the ugly white parts that stick out.

So it's this theme:
https://www.deviantart.com/niivu/art/Big-Sur-2-Windows-10-Themes-861727886

(The "Night" variant of the theme)

To be applied, you'll need to use:
https://github.com/namazso/SecureUxTheme

I've attached the theme directly in a zip to save you having to sign up for Deviant Art to download 🙂 (though feel free to do that obviously if you want)

[Big Sur 2 - niivu.zip](https://github.com/helgoboss/realearn/files/5967052/Big.Sur.2.-.niivu.zip)

This is REAPER before/after patched theme:

![](https://user-images.githubusercontent.com/26604994/106361986-59026600-62ee-11eb-8849-17c1c2b81595.png)

![](https://user-images.githubusercontent.com/26604994/106361988-5b64c000-62ee-11eb-90cd-449eb5b6dea0.png)

**Comment by helgoboss** [comment]
Found a way to get the theme color. I calculate the luminance of that color and if it's on the dark side, I use the default background instead of the white color. Works with the theme that you use and hopefully also with others.
