### ISSUE TITLE
Mac OS dark mode not supported in main 'add one' mapping area 

### ISSUE THREAD

**Issue by NGF86** [helgoboss/realearn#138]
Please see image to show the issue. You can see some text if you look closely but it is white, on a white background. This suggests the text is correct just the background should also be dark like the rest of the VST. 
![Screenshot 2021-02-10 at 21 59 37](https://user-images.githubusercontent.com/58295508/107579789-94097100-6bed-11eb-9f59-0aa5a60c6138.png)

**Comment by helgoboss** [comment]
Oh, this is bad. I know why it happens and will fix it ASAP.

**Comment by NGF86** [comment]
> Oh, this is bad. I know why it happens and will fix it ASAP.

Amazing thanks so much for the quick response!

**Comment by helgoboss** [comment]
Fixed. Will release this latest tomorrow.
