### ISSUE TITLE
Can't edit ReaLearn Companion layout

### ISSUE THREAD

**Issue by daeavelwyn** [helgoboss/realearn#151]
Hi Benjamin,

First of all, htanks so much for your HUGE work !
Well, I can't copy a map from the main map to the controller map using import/export to clipboard
see here : https://imgur.com/a/7P12FrQ
I can of course make futher tests if you can guide me throught your need.

**Comment by helgoboss** [comment]
"Import/export to clipboard" always relates to all ReaLearn settings, not just one compartment. At some point, #121 will be implemented, then what you want is going to be possible. Until then, your only resort is using a text or JSON editor.

**Comment by helgoboss** [comment]
The title of this issue doesn't fit the description. Is it possible that something went wrong?

**Comment by daeavelwyn** [comment]
> 
> 
> The title of this issue doesn't fit the description. Is it possible that something went wrong?

Yep, sorry made a mistake while copy/pasting stuff, sorry ^^'

**Comment by daeavelwyn** [comment]
> 
> 
>  Until then, your only resort is using a text or JSON editor.

Any documentation I could browse to acheive this ?

**Comment by helgoboss** [comment]
1. Hit "Export to clipboard"
2. Paste the text into a programmer's text editor (e.g. Visual Studio Code)
3. Do the transformations
    - In your case you need to take the list (`[...]`) of `mappings` and assign it instead to `controllerMappings`.
4. Copy the complete text
5. Hit "Import from clipboard"

**Comment by daeavelwyn** [comment]
> 
> 
>     3. Do the transformations
>        
>        * In your case you need to take the list (`[...]`) of `mappings` and assign it instead to `controllerMappings`.
> 

That was the part I missed, thanks ;)
