### ISSUE TITLE
MIDI Fighter Twister toggle switches don't react to feedback

### ISSUE THREAD

**Issue by stereokai** [helgoboss/realearn#152]
Hello, just wanted to say I absolutely love this plugin, and version 2 is absolutely amazing!

I just set up a sample project using MIDI Fighter Twister and ReaLearn 2. The switches on the Twister knobs are set to "CC Toggle", and I set the colored light to reflect the change in state as well.

The issue is as follows:
**Expected behavior** - When I change the (on/off) state directly in the software plugin, the Twister will reflect that by changing of the colored light for the bound knob-switch, in response to MIDI feedback from Reaper.
**Actual behavior** - MIDI feedback does not work with the toggle switches/the colored light under the knob doesn't reflect the change in the plugin.

For clarity, MIDI feedback *does* work on the encoders themselves. I have also tried assigning the switch to a Reaper control (as opposed to a VST) - a track mute button. Same behavior.

Am I doing something wrong? Is it a MIDI Fighter Twister limitation? Or a ReaLearn limitation?

Thanks for the help :)

**Comment by helgoboss** [comment]
That's because you have set up your Twister buttons as "CC Toggle", which is a no-go with applications like ReaLearn. It's mentioned in the ReaLearn user guide. Always configure your controllers to use momentary button mode, otherwise there's no way ReaLearn can take control over your buttons and also "Toggle buttons" mode also won't work correctly.

**Comment by stereokai** [comment]
I don't see the need to be so harsh, and completely block this issue from further conversation. I did have a read at scroll-length user guide, and I have no use for momentary switches in my use case.

**Comment by helgoboss** [comment]
Sorry if this came across as harsh, was not intended. We can still talk about this, the conversation is not blocked. ReaLearn's issue list acts as a sort of to-do list for me and closing an issue is just to remind to myself that this won't result in any feature or bugfix.

Let me explain in more detail: ReaLearn of course supports toggle mode (via Mode "Toggle buttons"), but in order to make it work, it *requires* controller buttons to act as momentary buttons. ReaLearn takes care of managing the toggle state (on/off) itself. This is important because your Midi Fighter Twister has no way of knowing the current target parameter value, so its own toggle mode ("CC Toggle") has less possibilities than ReaLearn's toggle mode.

**Comment by helgoboss** [comment]
Thanks BTW for the nice words :) It's always appreciated, even I don't usually respond to it specifically.

**Comment by stereokai** [comment]
Thanks for responding with more information :)

I followed your tip and everything now works as I hoped for. This is so fun! Your work is very impressive and makes life so much better!

I would like to pose another question for you, perhaps a bit complicated so excuse for being verbose:

Using the Twister, which has the encoders combined with a switch, is it possible to allow, using one encoder, both the simple toggle behavior we have discussed above, alongside a behavior which is described in your guide: [4.2.2.5 Use case: Control A when a button is not pressed, control B when it is](https://www.helgoboss.org/projects/realearn/user-guide#conditional-activation) - **_but_**, as long as the switch was only pressed shortly (used like a toggle button), ignore the conditional activation, and only if the switch is being held down put the conditional activation into effect? (Perhaps after a threshold time in ms).

Thank you again!

**Comment by helgoboss** [comment]
Glad to hear.

Yes, this is possible. If you made it that far, you probably already have a mapping that maps the Twister switch to an internal ReaLearn parameter (which in turn you use for conditional activation in another mapping). You need to split this mapping in two, let's call them "Short press" and "Long press". Both will have the same source (the switch).

- "Short press" mapping: Set the Length interval to 0 - 299ms. Change the target to whatever you want it to do when you do the short press.
- "Long press" mapping: Set the Length interval to 300 - 5000ms. Leave the target as is (ReaLearn's internal parameter).

**Comment by stereokai** [comment]
> you probably already have a mapping that maps the Twister switch to an internal ReaLearn parameter (which in turn you use for conditional activation in another mapping).

I did play a lot with ReaLearn today. Spent some time with the user guide and tried the internal mappings, controller mappings, virtual mappings, the projection web server feature, relative vs absolute encoder function, mapping groups, and more. Really admire all the work you put in.

So while I did make myself familiar with all these features, it's a lot to take in at once, and I feel like I'm missing the glue to put all the pieces of the puzzle together.

If I understand you correctly, I would map the button to an internal ReaLearn parameter, and then use in a separate mapping for the encoder, that will only be active when that internal parameter is changed to "on" by the button press. Is that correct?

I did change the encoder type as you recommended to `ENC 3FH/41H`. And was able to use the virtual mapping to recreate the setup I had created before using direct MIDI mapping with absolute values. However, one problem I could not remedy was that I've been using the "Blended Bar" indicator type and ReaLearn's feedback turns that into a single dot. What do you think about that?

Thanks again :)

**Comment by helgoboss** [comment]
> If I understand you correctly, I would map the button to an internal ReaLearn parameter, and then use in a separate mapping for the encoder, that will only be active when that internal parameter is changed to "on" by the button press. Is that correct?

Exactly. The "when that internal parameter is changed to on" part you express by setting the "Activation" dropdown to "When modifiers are on/off", set the first modifier to the internal ReaLearn parameter (to which you mapped the button) and enable the checkbox beside it (in order to tell ReaLearn "Only if this modifier is on.").

> I did change the encoder type as you recommended to `ENC 3FH/41H`. And was able to use the virtual mapping to recreate the setup I had created before using direct MIDI mapping with absolute values. However, one problem I could not remedy was that I've been using the "Blended Bar" indicator type and ReaLearn's feedback turns that into a single dot. What do you think about that?

That might be related to your issue #154. I actually never changed the indicator type in the Twister editor, need to try that.

**Comment by stereokai** [comment]
> That might be related to your issue #154. I actually never changed the indicator type in the Twister editor, need to try that.
The interesting thing is that in absolute mode, the Twister maintains the "Blender Bar" indicator style when it receives feedback from ReaLearn. I wonder if it's a limitation of the Twister.

I have another question to pose to you. I've been trying a few ideas, and all were working, but dirty and quite convoluted. And you know how us programmers feel about these kind of solutions ;) I wonder what you'll come up with: In my project are 3 track used for live monitoring, but *only 1 at any given time*. Meaning - if I switch from one track to the next, I want to *mute* as well as *turn off the FX* of the track I'm switching _from_, and of course the opposite on the track I'm switching _to_. I would like to use the side buttons on the Twister, corresponding to each track, for that. How would you implement that?

I have set it up so that when pressing any side button, first mutes and turns off the FX on all 3 tracks, and then enables the relative track.

**Comment by helgoboss** [comment]
Yes, this sounds convoluted, also not manageable if you add more tracks that you want to handle like this.

I see the following basic approaches:

1. Use one track instead of many (snapshot-based approach).
    - It seems like you only need 1 track at any given time. So why use 3 tracks?
    - You could make a snapshot of each of your 3 track states via ReaLearn target "Load track snapshot" (which doesn't yet exist but it's almost trivial to write, it would work like the FX snapshot target).
    - This might not be an option if loading the snapshot takes too long though or if that causes some kind of audio clicks.
2. Implement a specific ReaLearn target which does that (turning off all tracks except a particular one)
    - Possible but this sounds a bit too specific, too hard-coded to me.
    - Maybe the "Track selection" target could be reused for this and I could add checkboxes for muting other tracks and so on.
    - Still not great, not very composable.
3. Script
    - This is probably the most straightforward and composable way: You write a ReaScript which turns off each track except the currently selected one.
    - You add a second ReaLearn mapping to the button press that calls this script (below the one that selects the track).
    - I think the mappings are sequentially processed. If not, let me know.

**Comment by stereokai** [comment]
Thanks for the thoughtful and creative answer.

The problem with the snapshot approach, is that it will reset any FX parameter on recall. 

> Implement a specific ReaLearn target which does that (turning off all tracks except a particular one) 
How is that done? Does ReaLearn have a multi-target option?

**Comment by stereokai** [comment]
Thanks for the thoughtful and creative answer.

The problem with the snapshot approach, is that it will reset any FX parameter on recall. 

> Implement a specific ReaLearn target which does that (turning off all tracks except a particular one) 
How is that done? Does ReaLearn have a multi-target option? Or do you mean a separate mapping for each track specifically for muting?

One interesting detail, is that if I use the built in bank functionality of the Twister, for each side button press, the Twister send 2 midi CCs, one for the current bank and one for the next bank being switched to, for example:
```js
CH 4, CC 0, VAL 0 // Leaving bank no. 1 (CC numbers start at 0 for the banks. Channel 4 is the default for the side buttons)
CH 4, CC 1, VAL 127 // Entering bank no. 2
```
So, if I don't use the controller mappings in ReaLearn, that could also be something to rely on. Could I, for example, do something like: "Every time any CC on CH4 comes in with a value of 0, mute these 3 tracks"?

**Comment by helgoboss** [comment]
> @helgoboss Thanks for the thoughtful and creative answer.
> 
> The problem with the snapshot approach, although a great idea, is that it will reset any FX parameter on recall, and that breaks my use case.

Oh right.

> > Implement a specific ReaLearn target which does that (turning off all tracks except a particular one)
> 
> How is that done? Does ReaLearn have a multi-target option? Or do you mean a separate mapping for each track specifically for muting?

No, implementing this would be my job. It can't be done by the user. It would be a new feature. Not so keen on this though for the mentioned reasons.

> One interesting detail, is that if I use the built in bank functionality of the Twister, for each side button press, the Twister send 2 midi CCs, one for the current bank and one for the next bank being switched to, for example:
> 
> ```js
> CH 4, CC 0, VAL 0 // Leaving bank no. 1 (CC numbers start at 0 for the banks. Channel 4 is the default for the side buttons)
> CH 4, CC 1, VAL 127 // Entering bank no. 2
> ```
> 
> So, if I don't use the controller mappings in ReaLearn, that could also be something to rely on as an alternative. Could I, for example, do something like: "Every time any CC on CH4 comes in with a value of 0, mute these 3 tracks"?

Ah, they really put much though into this device. If you want to talk to 3 tracks, you need 3 mappings. Use the "Track mute" target and the "CC value" source. Set channel to 4. Set CC to <Any> (if you really want to react to any CC on that channel, rarely used feature which I only added because the world felt somehow incomplete without it). Set both Source Min/Max to 0. Set "Out-of-range behavior" to "Ignore". This does what you say, though I'm not sure it's 100% what you need.

> Edit: On a second thought, "mute these 3 tracks" could be a plain ol' custom Reaper action. But my other two questions still stand :)

The still think 3 (script) is the best option. It would be very scaleable. But if targeting 3 fixed tracks is really enough for you, a custom REAPER action is enough.

**Comment by stereokai** [comment]
I appreciate the extensive communication on this.

> No, implementing this would be my job. It can't be done by the user. It would be a new feature. Not so keen on this though for the mentioned reasons.

Don't bother implementing that just for me :) The feature on #154 is more important ;)

In case I do use the virtual controller mappings, the way to go about this would be a script/custom action + 2 mappings per button? (one for muting all tracks, one for unmuting the selected track) - right? Or is there a simpler way I missed?

**Comment by stereokai** [comment]
I appreciate the extensive communication on this.

> No, implementing this would be my job. It can't be done by the user. It would be a new feature. Not so keen on this though for the mentioned reasons.

Don't bother implementing that just for me :) The feature on #154 is more important ;)

> Set both Source Min/Max to 0. Set "Out-of-range behavior" to "Ignore". This does what you say, though I'm not sure it's 100% what you need.

In the same manner, could I set Source Min/Max to 127 and respond only to the "enter bank" CCs?

Otherwise, in case I do use the virtual controller mappings (that depends on #154 tbh), the way to go about this would be a script/custom action + 2 mappings per button? (one for muting all tracks, one for unmuting the selected track) - right? Or is there a simpler way I missed?

**Comment by helgoboss** [comment]
> In the same manner, could I set Source Min/Max to 127 and respond only to the "enter bank" CCs?

Yes.

> Otherwise, in case I do use the virtual controller mappings (that depends on #154 tbh), the way to go about this would be a script/custom action + 2 mappings per button? (one for muting all tracks, one for unmuting the selected track) - right? Or is there a simpler way I missed?

Actually only one if I think about it (not counting the track selection mapping(s) which I guess you already have finished). If you use a script, you can easily write it in a way so that every track except the selected one gets muted.

**Comment by stereokai** [comment]
That's a good improvement indeed.

> That might be related to your issue #154
<https://github.com/helgoboss/realearn/issues/154>. I actually never
changed the indicator type in the Twister editor, need to try that.

Would you like me to open a specific issue for that?

**Comment by stereokai** [comment]
> Yes, this is possible. If you made it that far, you probably already have a mapping that maps the Twister switch to an internal ReaLearn parameter (which in turn you use for conditional activation in another mapping). You need to split this mapping in two, let's call them "Short press" and "Long press". Both will have the same source (the switch).
> 
> * "Short press" mapping: Set the Length interval to 0 - 299ms. Change the target to whatever you want it to do when you do the short press.
> 
> * "Long press" mapping: Set the Length interval to 300 - 5000ms. Leave the target as is (ReaLearn's internal parameter).

@helgoboss I have an update on this that might be of relevance to you.

I was able to set the Twister up to control 2 faders with 1 knob: one fader by twisting the knob, and a separate fader by holding the knob down and twisting it - including separate feedback for both faders. That was achieved by mapping the momentary button CC Hold to a virtual parameter in ReaLearn and activating/deactivating the mapping accordingly. Additionally, the same knob acts as a toggle switch for a different control. The differentiation between toggle and momentary mappings was done by limiting the toggle action to 250ms.

What might be interesting to you, is I didn't, and couldn't, use the time (Length) controls for the momentary action, in the manner which you previously recommended (as described above, I was nevertheless able to find a different solution). The situation was, as soon as any "Length" value was applied - the mapping stopped acting as a momentary button, and behaved like a toggle button, which only "turned on" the virtual parameter once the physical button was released. I hope my description is not as confusing as this behavior was to me :S

**Comment by helgoboss** [comment]
> What might be interesting to you, is I didn't, and couldn't, use the time (Length) controls for the momentary action, in the manner which you previously recommended (as described above, I was nevertheless able to find a different solution). The situation was, as soon as any "Length" value was applied - the mapping stopped acting as a momentary button, and behaved like a toggle button, which only "turned on" the virtual parameter once the physical button was released. I hope my description is not as confusing as this behavior was to me :S

I just checked here, it works. I think you got confused by the way the "Length" thing works. It's not turning anything into a toggle:

1. It receives the button press (which is a value *v* which is usually 127 or something between 1 and 127 if you have a velocity-sensitive button).
2. It doesn't do anything at this point, just remembers the value *v*.
3. As soon as you release the button it checks if the the duration of the button press is within the "Length" interval that you have set.
4. If it is, it will trigger the target with the value *v*.

Makes sense, doesn't it? If you still need another mapping that reacts to a short press, you need to add another mapping where Length Min is 0.

**Comment by stereokai** [comment]
> 3. As soon as you release the button it checks if the the duration of the button press is within the "Length" interval that you have set.

That's exactly the behavior that threw me off. I am sure you understand - that is the function of a toggle button, not a momentary button

**Comment by helgoboss** [comment]
> > 1. As soon as you release the button it checks if the the duration of the button press is within the "Length" interval that you have set.
> 
> That's exactly the behavior that threw me off. I am sure you understand - that is the function of a toggle button, not a momentary button

I think I understand what you mean but it has nothing to do with toggle buttons. A toggle button is something that toggles the target value (between on/off). How in any way does above behavior toggle a target value?

I think what threw you off is the fact that the target is triggered at the moment the button is released, not when the 300ms are reached. This is something I want to improve.

**Comment by stereokai** [comment]
Apologies, I actually just realized my mistake - I've been using "toggle button" throughout the entire conversation but in fact meant "latching button", as in, a latching on/off switch, in contrast with momentary button. Perhaps that will make my last communications clearer :)

**Comment by helgoboss** [comment]
Okay, I'm not so familiar with that term. Just to make sure and without using any of those potentially misleading terms ... am I correct that the fact that confuses you is that it fired on "button release" and not as soon as having it pressed 300ms?

**Comment by stereokai** [comment]
Yes, you are correct - because, what I was expecting is a momentary behavior, that only takes place once the button has been held for a certain time threshold. Can you give me an example of when it would be useful to have the mapping fire only once the button is _released_ **_and_** only after a time threshold?

**Comment by helgoboss** [comment]
Yes, of course. E.g. the example that I demonstrated [here](https://www.youtube.com/watch?v=dUPyqYaIkYA&t=1230s). If I press the button very shortly (< 300ms), it will reset just the parameter controlled by this push encoder. If I press it longer, it will reset many more parameters. For the final result it's completely irrelevant if this reset occurs as soon as I release the push encoder or as soon as the 300ms are reached.

Actually I don't see much of a difference between those two variants at all (variant 1 being "fire on release" and variant 2 being "fire as soon as duration reached"). It's more a difference in quality and how it feels. But the final result is the same, isn't it?

One thing that can even only be done with "Fire on release" is having more than 2 press durations: A super short one, a bit longer one and a very long one (e.g. for resetting really everything - to name a practical use case).

**Comment by stereokai** [comment]
Really good examples provided! I can definitely see now where it would come into play.

> Actually I don't see much of a difference between those two variants at all (variant 1 being "fire on release" and variant 2 being "fire as soon as duration reached"). It's more a difference in quality and how it feels. But the final result is the same, isn't it?

I was trying to map one knob to 2 faders, and control either fader depending on whether the knob is held pressed down or not. This will not work, if the internal parameter which flips between the two fader would only get triggered when the knob is released. Can you visualize that? In your example it does make no difference because you are not using the state of whether or not the knob is pressed down to affect a second control (in my case, the knob twist).

**Comment by helgoboss** [comment]
Ah, finally I get what you mean ;) ;) ;) I see the problem lol. Well, then I'll create an issue to support "Fire as soon as Length Min reached" or something.
