### ISSUE TITLE
Allow copying only the mappings between instances of ReaLearn

### ISSUE THREAD

**Issue by stereokai** [helgoboss/realearn#157]
The clipboard copy/import feature is very useful! It could be made even more useful, if it would allow copying only the mappings between instances of ReaLearn, instead of the entire current plugin configuration.

An additional nice to have feature would be mapping drag-and-drop between instances of ReaLearn.

**Comment by helgoboss** [comment]
Implemented as part of #121

**Comment by stereokai** [comment]
Amazing. Thank you very much!
