### ISSUE TITLE
Add option to fire as soon as "Length Min" reached

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#166]
At the moment it fires on button release. There are cases [like this one](https://github.com/helgoboss/realearn/issues/152#issuecomment-782927930) where this is not enough. Additionally, it just feels better if it fires without having to release the button.

**Comment by jackmau** [comment]
+1 it feels better indeed, and solves that psicological dilemma for which for long press we tend to always press more than necessary
