### ISSUE TITLE
feedback proportionaly

### ISSUE THREAD

**Issue by libertyrock** [helgoboss/realearn#175]
add a virtual feedback device to save midi cc value for changes of targets. Then change values proportionaly controller input set

**Comment by helgoboss** [comment]
Can you explain in more detail? Not sure what you mean.

**Comment by libertyrock** [comment]
sorry for my english...spanish?

**Comment by helgoboss** [comment]
I'm not good in Spanish ;) But maybe you can try it and I use Google Translate.

**Comment by libertyrock** [comment]
This is an app made by me... it's possible make this?
https://youtu.be/VBXqmerQL9s?t=370

**Comment by helgoboss** [comment]
Ah! Perfect, now I understand what you mean! You are looking for this: #12.

ReaLearn at the moment supports what is called "Buscar" in the video by setting "Jump Max" to a small value. And if you enable "Slowly approach if jump too big", you can achieve something similar to "Proporcional" but the value can move in the opposite direction, which is sometimes not a good thing.

Please try the above or wait for #12.

**Comment by libertyrock** [comment]
Muchas gracias. Buena herramienta.

**Comment by libertyrock** [comment]
Another issue. Possible error....

https://user-images.githubusercontent.com/68690304/109537267-fc49c500-7abe-11eb-96a7-9aaaad9bfcb7.mp4
