### ISSUE TITLE
Possible error sending midi out device

### ISSUE THREAD

**Issue by libertyrock** [helgoboss/realearn#194]
https://user-images.githubusercontent.com/68690304/109537770-9447ae80-7abf-11eb-98f5-c2acdf79d084.mp4

**Comment by libertyrock** [comment]
when return to reaper send midi out cc true values of track (volume, pan, mute, solo) but when load the project send all CC values to zeros.

**Comment by helgoboss** [comment]
Thanks. Which version do you use and can you attach the RPP file please?

**Comment by libertyrock** [comment]
[Pruebas realearn prueba2.zip](https://github.com/helgoboss/realearn/files/6063889/Pruebas.realearn.prueba2.zip)
reaper 6.23

**Comment by helgoboss** [comment]
Thanks, I could reproduce it. It might be related to using multiple instances.
