### ISSUE TITLE
hardware output routing override track sends

### ISSUE THREAD

**Issue by arnoldmoon** [helgoboss/realearn#200]
when a track has hardware output and track sends, total number of send dropdown on mapping page becomes number of track sends, then first n number of track sends gets overriden by hardware sends.

steps to reproduce
-create 2 tracks
-on track1 routing, add send to track2
-on track1 routing, add hardware output
-reaLearn mapping for track1 shows no send to track2, just hardware output.

thanks!
Arnold

**Comment by helgoboss** [comment]
Oh right, thanks, will see how I can fix this.
