### ISSUE TITLE
Allow to customize internal free parameters

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#209]
Name and Discrete(step size) or NonDiscrete

**Comment by jackmau** [comment]
+1, this would be a requirement for #187

**Comment by helgoboss** [comment]
Accidentally closed

**Comment by helgoboss** [comment]
This is partially implemented (names can be changed via GUI). Step sizes not yet. Will leave it open.

**Comment by helgoboss** [comment]
Also modify the conditional activation bank list according to the configured number of discrete values (see https://github.com/helgoboss/realearn/discussions/371#discussioncomment-760569).

**Comment by helgoboss** [comment]
Users can now configure a maximum value count for a parameter, making it discrete.
