### ISSUE TITLE
Select region when using Go to region target

### ISSUE THREAD

**Issue by DLongoni** [helgoboss/realearn#215]
When selecting the "Go to region" target, it would be great to have a "select region" flag, or even to do it by default. This way the target region would be selected in reaper either when the target is triggered, or when the cursor actually jumps to the region. Personally I wouldn't have any preference for either. 

Thanks!

**Comment by helgoboss** [comment]
Making it be selected when the cursor actually jumps would be more difficult, so I would select it when the target is triggered. By "selecting" you mean simply creating a time selection (a loop) that goes from the start of the region till its end, right?

**Comment by DLongoni** [comment]
Yes exactly, I mean a time selection, like if you just selected it by clicking and dragging with your mouse over the region. 

Selection at trigger is perfect, I have used it like that until now and never had a problem (except I didnt have feedback =D)
