### ISSUE TITLE
When editing individual Mappings, shortcut to "save and go to next Mapping"

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#224]
(Maybe also previous)

**Comment by helgoboss** [comment]
One question: What does next and previous refer to? The complete compartment, the group, the filtered mapping list?

**Comment by vonglan** [comment]
I guess the filtered mapping list, would be the most useful default.
The Use Case I encountered was this: 
- Autolearn many, from an NRPN source
- So after learning everything initially I need to go back to refine: add specific NRPN max value (different for many knobs on Sequential synths), add specific Virtual Target

**Comment by helgoboss** [comment]
I'm so happy that someone uses NRPN :D I put much work in that for the sake of completeness (supporting even exotic MIDI features). But so far I actually didn't stumble upon any controller in the wild that actually uses this (at least not as a default).

**Comment by vonglan** [comment]
Again, all Dave Smith (Sequential) synthesizers use NRPN. They also offer CC, but only for a subset (about 1/3) of the controllers, and sometimes with less range. Yes, I think CC is the factory default. But they recommend to use NRPN in the manual.

**Comment by helgoboss** [comment]
I guess NRPN (although a bit more complicated and bloated than other types of MIDI messages) makes sense for any synthesizer that has more than 32 high-resolution controls. If it would be up to 32, they could just as well use 14-bit CC spec. If it would be low resolution, they could just use normal CCs.

**Comment by grnprplorngyllw** [comment]
Yeah! "Next" and "Previous" buttons would be awesome! That way we don't have to leave de EDIT window to edit other mappings

**Comment by vonglan** [comment]
Just saw your comments now again.

> I guess NRPN (although a bit more complicated and bloated than other types of MIDI messages) makes sense for any synthesizer that has more than 32 high-resolution controls. If it would be up to 32, they could just as well use 14-bit CC spec. If it would be low resolution, they could just use normal CCs.

The Sequential synth (OB6 and Prophet 6 and I think the others follow the same principles):
- don't use all 14 bits, only up to 8 (don't know why - maybe the differences wouldn't be audible anyway?)
- but much less than half of the controls are exposed as CCs
- so it's definitely necessary to change from CC (which I think is the factory default) to NRPN
- it does not offer any other "controller settings" apart from CC/NRPN and MIDI channel

> When you build your standardized set (#205), I think it would be great if you would rely as far as possible on the synth defaults. Unless you hit limits. E.g. one rule I have with my "official" controller presets: If the factory setting is to have encoders transmit absolute values, change it to relative ones. Otherwise stick to the factory settings.

**Comment by vonglan** [comment]
I just notice again how much I would like to have this feature. 
Quite often, I have to go over multiple mappings again, to change just one field.
Does anyone else want this?

**Comment by vonglan** [comment]
"question" label can be removed

**Comment by vonglan** [comment]
I just notice again how much I would like to have this feature :-)

**Comment by helgoboss** [comment]
Someone in the forum was asking for it as well, so I guess this issue gets some new traction. I'll see what I can do.

**Comment by PucksEvilTwin** [comment]
Yes this would be great to have!

Basically a similar use case for my OSC layout.  Say I learn a bunch of buttons but now need to make one small tweak on each of them.  Prev/Next mapping buttons would be great for that.

When you do this with Realearn as it sits now, it feels clunky and it's easy to miss a mapping.  However, if you only had one mapping panel open and were clicking next to cycle through them all, that should feel less clunky and minimize mistakes of small edits to a bunch of different mappings.
