### ISSUE TITLE
Make it possible to map different plug-ins to the same preset (e.g. VST vs. VST3)

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#226]
On OSX, I have VST, VST3 and AU versions for many "VSTs", for example for RePro-5. Normally I prefer the AU version (because it seems "native" on OSX, not sure whether that has any real advantage). However, due to a current bug in Big Sur, I have to use VST or VST3 (otherwise parameter feedback does not show - at least not the way I used to do it without ReaLearn).
When I currently (still have ReaLearn 2.5) save the Main Mapping, ReaLearn offers to automagically relate all Mappings to the currently open FX.
What I would like, is for ReaLearn to relate this set of mappings to Repro-5 - No matter, whether it is AU or VST3 or whatever.
And it seems that I would also want to store this set of mappings for Repro-5 separately (not - or not only - as part of a bigger "Main Mapping"). Maybe this should be a different Compartment Type called "VST Mappping"?

**Comment by helgoboss** [comment]
> On OSX, I have VST, VST3 and AU versions for many "VSTs", for example for RePro-5. Normally I prefer the AU version (because it seems "native" on OSX, not sure whether that has any real advantage). However, due to a current bug in Big Sur, I have to use VST or VST3 (otherwise parameter feedback does not show - at least not the way I used to do it without ReaLearn).
> When I currently (still have ReaLearn 2.5) save the Main Mapping, ReaLearn offers to automagically relate all Mappings to the currently open FX.
> What I would like, is for ReaLearn to relate this set of mappings to Repro-5 - No matter, whether it is AU or VST3 or whatever.

I expected this to come up sooner or later :) The structure for this kind of thing is there. You might even be able to achieve that by modifying the file `Data/helgoboss/realearn/auto-load-configs/fx.json` in the REAPER resource path (but maybe ReaLearn will overwrite it when you change it via GUI). This is how it looks for me:

```json
{
  "links": [
    {
      "fx": {
        "fileName": "Vibrato 64.dll"
      },
      "presetId": "vibrato-test2"
    },
    {
      "fx": {
        "fileName": "ColourCopy(x64).dll"
      },
      "presetId": "colour-copy"
    },
    {
      "fx": {
        "fileName": "reasynth.dll"
      },
      "presetId": "reasynth"
    },
    {
      "fx": {
        "fileName": "Vital.dll"
      },
      "presetId": "vital-test"
    },
    {
      "fx": {
        "fileName": "Pianoteq 7 STAGE.vst3"
      },
      "presetId": "pianoteq-test"
    }
  ]
}
```

Either I will allow wildcard matching (e.g. `"fileName": "ColourCopy*"` ) or allow to add multiple mappings with the same `presetId` via GUI. Not sure yet.

> And it seems that I would also want to store this set of mappings for Repro-5 separately (not - or not only - as part of a bigger "Main Mapping"). Maybe this should be a different Compartment Type called "VST Mappping"?

I have thought about that possibility a lot in the design phase and decided against it. So it's probably not going to happen (would also be pretty difficult). There's always the possibility to use multiple ReaLearn instances. Sometimes using multiple instances instead of one has *currently* still disadvantages but there are some ideas and open issues that I want to implement in order to mitigate that.

**Comment by vonglan** [comment]
I thought you had already thought about these topics :-)
So what is your current recommendation if I want to create multiple, VST-specific mappings. Save each of them separately under the VST-specific name. And then load them into the track instance of ReaLearn as needed (or bundle them with the VST as an FX Chain)?
Will this also work acceptably when I combine an instrument with an effect in a track?

**Comment by helgoboss** [comment]
Can you go more into detail what you mean by that?

**Comment by vonglan** [comment]
I'll open a separate issue, as that is a separate issue from the one that you already answered.

**Comment by jackmau** [comment]
> Normally I prefer the AU version (because it seems "native" on OSX, not sure whether that has any real advantage)

I have been often transfering projects between my windows desktop and macbook and I have never had a problem since v1, using VSTs. Wouldn't the changing your mapping to `<By Name>` FX selector be enough to solve the issue, @vonglan?

**Comment by helgoboss** [comment]
@jackmau It's about "Auto-load preset: Depending on focused FX". This currently depends on the file name including its extension.

**Comment by vonglan** [comment]
> I have been often transfering projects between my windows desktop and macbook and I have never had a problem since v1, using VSTs. Wouldn't the changing your mapping to `<By Name>` FX selector be enough to solve the issue, @vonglan?

I haven't experimented or fully understood how these features work yet, so I can't really say yet. Certainly <By Name> is a very useful feature.

**Comment by vonglan** [comment]
Just tried out the FX selector "By name". Works great! I particularly like that the name of the (previously mapped) FX parameter appears as soon as I type a matching pattern.

**Comment by helgoboss** [comment]
At this occasion, use popup menus to make this configurable!

**Comment by vonglan** [comment]
> At this occasion, use popup menus to make this configurable!

I did not understand this. I will see it when you have implemented it.

**Comment by helgoboss** [comment]
Was just a note to self.
