### ISSUE TITLE
Let the companion app show the current target value

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#235]

**Comment by DLongoni** [comment]
Alright sorry for the late reply, very busy in this period. I see you linked this feature in two other issues. It looks super promising to me, but I tried a little bit to use it and with a simple example (using the web browser version of the companion) I just see no feedback. I am 100% sure I am doing something wrong but I really can't see what should happen and how to achieve it. If you already explained it somewhere sorry but I can't find it. (=

**Comment by helgoboss** [comment]
You need to use the companion beta: https://605335d551bba800082b1e37--realearn-companion.netlify.app/

**Comment by DLongoni** [comment]
Tried it, stuck on "Almost there! TODO Linux instructions" and no way go past this message to the actual app. Anyway I can also wait for the compaion to go to a stable release and retry, don't wanna pressure you on this!! Thanks

**Comment by helgoboss** [comment]
Are you on Linux?

**Comment by helgoboss** [comment]
Actually it would be good if you could test it. Otherwise the bug will be in the final release and nobody wants that to happen.

**Comment by DLongoni** [comment]
Of course I can test it! And yes I'm on linux (=

**Comment by helgoboss** [comment]
Can you try it again? You should see further instructions now, not just a TODO. If you still see the TODO, you might need to open the (beta) companion app web page, close the browser and open it again for the changes to have an effect.

**Comment by DLongoni** [comment]
Sorry for the delay, I'm a bit busy these days. I've tried a few times with 2.8.0-pre6, nothing changed. The stable app shows no sign of any current value/feedback, and the beta app is still stuck on "TODO linux trust instructions".  I am connecting to the beta app via browser using the "enter connection data" method. It might be helpful to note that if I enter the correct IP then the app is stuck on "TODO" regadless of the session id. On the other hand if I input a non existent IP then the app will show the "connection failed" message.
