### ISSUE TITLE
Check if we need "Virtual parameters" for presets

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#241]
Copied from here: https://github.com/helgoboss/realearn/issues/231#issuecomment-802360108

I think one challenge that would come up with this is how to decide which parameters to use.

Imaginary scenario: You make a controller preset that uses parameter 1 for some control element switching. Someone else makes a main preset that uses parameter 1 for something else. BOOM. The two will interfere with each other.

This kind of problems could be prevented by strictly following a convention, e.g. using parameters 1 - 50 for main mappings only and 51 - 100 for controller mappings.

But what if not everybody does this in the presets? Big chaos. Actually, it's a problem with using conditional activation in presets in general. Do we maybe need a "Parameter mapping" feature? So that each preset creator can rely on *virtual ReaLearn parameters* but the actual mapping to *real ReaLearn VST instrument parameters* is done by the preset consumer.

**Comment by vonglan** [comment]
I have been thinking about something similar, with regard to #205 .
If we have standardized FX parameter sets like "analog synth", that are shared by many users, it would be good if they could be called by names in the UI and JSON (maybe with a namespace convention, like "AS/Filter Cutoff", or "FX/Rate"), and internally processed by their hash values. (And maybe these are only needed inside the ReaLearn infrastructure, not visible to Reaper as ReaLearn's 100 Parameters.)

**Comment by helgoboss** [comment]
> I have been thinking about something similar, with regard to #205 .
> If we have standardized FX parameter sets like "analog synth", that are shared by many users, it would be good if they could be called by names in the UI and JSON (maybe with a namespace convention, like "AS/Filter Cutoff", or "FX/Rate"), and internally processed by their hash values. (And maybe these are only needed inside the ReaLearn infrastructure, not visible to Reaper as ReaLearn's 100 Parameters.)

I don't really get that. I think the problem is that we have different understandings of the terms "parameter", "virtual parameter" and "virtual sources/targets". And that "parameters" can be used in multiple contexts. Let's agree on one wording first (designing software and talking about software is really much about wording, so even if it appears we are pedantic here, I think it's very important):

**FX parameters** = Automatable parameters of a VST/JS/AU/DX plug-in, e.g. "Attack" is the first FX parameter of ReaSynth.

**ReaLearn FX parameters** = FX parameters of ReaLearn itself (there are 100 of them and their meaning is totally up to the user).

**Virtual target** = A controller mapping can have a virtual target, e.g. "Button 5". This is a kind of wire to a "Virtual source" on main mapping side.

**Virtual source** = This is the receiving end of the wire, e.g. of "Button 5". Only main mappings can have it.

**Virtual parameters** = This term actually doesn't exist yet in the domain of ReaLearn. You have been using it but I don't know what you mean by that. With this ticket (#241) I *might* introduce it to ReaLearn. For me this is a kind of input value of a ReaLearn preset. It can be connected to a real ReaLearn FX parameter in some way (that is not yet defined).

Can you explain what role do **ReaLearn FX parameters** play exactly in your #205 "Standardized set of Analog Synth virtual parameters"? Actually I thought #205 is primarily about "Virtual targets" and "Virtual sources", not about "ReaLearn FX parameters".

**Comment by vonglan** [comment]
Quick answer: I believed Virtual targets/sources were identical to ReaLearn FX Parameters.
I will give a longer answer later.

**Comment by vonglan** [comment]
I posted some ideas how to solve this in #231 .

I think "virtual ReaLearn FX parameters" could not work, because you would not be able to address them from outside (e.g. a ReaScript).

**Comment by helgoboss** [comment]
> Quick answer: I believed Virtual targets/sources were identical to ReaLearn FX Parameters!
> Sorry for the confusion and fruitless discussions.

No problem, glad we use the same wording now.

> I think "virtual ReaLearn FX parameters" could not work, because you would not be able to address them from outside (e.g. a ReaScript).

Unless there would be a way to map them to real ReaLearn FX parameters (with a mapping that's defined by the user of the preset containing those virtual FX parameters). But I have no idea yet how this could be done, especially with the goal in mind to not overload the user with too much mental burden and annoying click orgies.

By the way: If it's about ReaScript only, then one solution would be to use a REAPER extension of the VST API called "Named parameters" (which is already used by ReaLearn to enable ReaScripts to load ReaLearn JSON presets). They can be set by ReaScripts using `TrackFX_SetNamedConfigParm`. However, named VST parameters can't be automated or listed in REAPER so they are quite limited unfortunately. Otherwise, clever naming conventions could make virtual parameters entirely obsolete.

> I posted some ideas how to solve this in #231 .

Great, I will have a look.

**Comment by helgoboss** [comment]
We came up with the idea of having preset-specific parameter customizations, as described in https://github.com/helgoboss/realearn/issues/231#issuecomment-803636716. No additional "outer FX parameters" to "virtual preset parameters" necessary.

**Comment by helgoboss** [comment]
Parameter customization is handled in #209 so I can close this.
