### ISSUE TITLE
Named Virtual sources/targets: no effect on VST

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#250]
In the Main Mapping, I can properly learn the virtual sources from the Controller Mapping.
However, the mapping as a whole does not reach the VST (the slider does not move in the VSTs GUI and the synth sound does not change).
Here are excerpts from two mappings, one with name, one with number. With number works, with numbers doesn't.

(By the way, what does it mean in the list of mappings in the Main Mappings Compartment, when there is a number in parentheses behind the parameter?)

(And one more little bug: In the list of mappings, the mapping target with "FX by name" is still displayed with the previous selection (by ID) even though I just changed it)

Controller Mapping:
    {
      "id": "729b9a7f-2100-4ade-aa21-21c5b232f093",
      "name": "1",
      "source": {
        "channel": 0,
        "number": 7,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "fxIndex": 2,
        "fxGUID": "9D583EEF-A410-AB47-8AD5-61369270D8C4",
        "paramIndex": 104,
        "controlElementIndex": "AS/Cutoff",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },
    {
      "id": "6b27af41-2b56-496f-95dc-e7f51d11f46a",
      "name": "3",
      "source": {
        "channel": 0,
        "number": 11,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "controlElementIndex": 2,
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },

Main Mappings:
    {
      "id": "73e32204-67bb-4ea9-8e79-5c439dfde736",
      "name": "7",
      "source": {
        "category": "virtual",
        "type": 6,
        "channel": 0,
        "number": 45,
        "isRegistered": false,
        "is14Bit": true,
        "oscArgIndex": 0,
        "controlElementIndex": "AS/Cutoff"
      },
      "mode": {
        "maxTargetJump": 0.0,
        "takeoverMode": "parallel"
      },
      "target": {
        "fxAnchor": "name",
        "fxName": "*J-8*",
        "paramIndex": 104
      }
    },
  {
      "id": "abfd0fb3-9acf-460a-92d7-44a770b8d90d",
      "name": "1",
      "source": {
        "category": "virtual",
        "type": 6,
        "channel": 0,
        "number": 0,
        "isRegistered": false,
        "is14Bit": true,
        "oscArgIndex": 0,
        "controlElementIndex": 2
      },
      "mode": {},
      "target": {
        "fxAnchor": "id",
        "fxIndex": 2,
        "fxGUID": "9D583EEF-A410-AB47-8AD5-61369270D8C4",
        "paramIndex": 102
      }
    },

**Comment by vonglan** [comment]
same symptom also in pre5 (with existing presets)

**Comment by helgoboss** [comment]
Can't reproduce this. Can you attach a RPP?

**Comment by vonglan** [comment]
[Temp Bug.RPP.zip](https://github.com/helgoboss/realearn/files/6193220/Temp.Bug.RPP.zip)

**Comment by helgoboss** [comment]
If possible without 3rd-party VSTs (just bult-in)

**Comment by vonglan** [comment]
I just realize that it did work in my next example which I built from scratch - see #253 

This can be closed.
