### ISSUE TITLE
#231 works great, except Bank Switching did not

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#253]
Maybe I made a mistake.
I see in reaper that the parameter is changed correctly from 0.0 to 0.01.
But still, the first bank is selected.
Here is my complete example:

{
  "version": "2.8.0-pre5",
  "id": "RzdhYLI-",
  "controlDeviceId": "0",
  "defaultGroup": {},
  "defaultControllerGroup": {},
  "controllerGroups": [
    {
      "id": "2a39f666-254a-44ab-bd4b-402c7b61a6d7",
      "name": "Osc",
      "activationType": "program"
    },
    {
      "id": "37ed3389-3c63-4618-91aa-c5c32cc33995",
      "name": "Mix",
      "activationType": "program",
      "programCondition": {
        "paramIndex": 0,
        "programIndex": 1
      }
    }
  ],
  "mappings": [
    {
      "id": "2ed6bf79-c87c-491c-b2b1-6a7c0d737df7",
      "name": "1",
      "source": {
        "category": "virtual",
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0,
        "controlElementIndex": "AS/Osc1Pitch"
      },
      "mode": {},
      "target": {
        "fxAnchor": "name",
        "fxName": "*J-8*",
        "paramIndex": 88,
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      }
    },
    {
      "id": "6e7fae8f-abcf-4ab0-80ea-2e01a1139a73",
      "name": "2",
      "source": {
        "category": "virtual",
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0,
        "controlElementIndex": "AS/Osc1Waveform"
      },
      "mode": {},
      "target": {
        "fxAnchor": "name",
        "fxName": "*J-8*",
        "paramIndex": 90,
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      }
    },
    {
      "id": "ea127192-172d-44aa-8588-06b00506314e",
      "name": "3",
      "source": {
        "category": "virtual",
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0,
        "controlElementIndex": "AS/Osc2Pitch"
      },
      "mode": {},
      "target": {
        "fxAnchor": "name",
        "fxName": "*J-8*",
        "paramIndex": 92,
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      }
    },
    {
      "id": "e4db2795-e589-41b6-9c5f-1cea4b3d068c",
      "name": "4",
      "source": {
        "category": "virtual",
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0,
        "controlElementIndex": "AS/Osc2Waveform"
      },
      "mode": {},
      "target": {
        "fxAnchor": "name",
        "fxName": "*J-8*",
        "paramIndex": 94,
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      }
    }
  ],
  "controllerMappings": [
    {
      "id": "729b9a7f-2100-4ade-aa21-21c5b232f093",
      "name": "1",
      "groupId": "2a39f666-254a-44ab-bd4b-402c7b61a6d7",
      "source": {
        "channel": 0,
        "number": 7,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "fxIndex": 2,
        "fxGUID": "9D583EEF-A410-AB47-8AD5-61369270D8C4",
        "paramIndex": 104,
        "controlElementIndex": "AS/Osc1Pitch",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },
    {
      "id": "855de773-60a5-49c6-8524-51accd277934",
      "name": "2",
      "groupId": "2a39f666-254a-44ab-bd4b-402c7b61a6d7",
      "source": {
        "channel": 0,
        "number": 10,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "controlElementIndex": "AS/Osc1Waveform",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },
    {
      "id": "6b27af41-2b56-496f-95dc-e7f51d11f46a",
      "name": "3",
      "groupId": "2a39f666-254a-44ab-bd4b-402c7b61a6d7",
      "source": {
        "channel": 0,
        "number": 11,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "controlElementIndex": "AS/Osc2Pitch",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },
    {
      "id": "8601d73e-ce9f-40e7-9076-1ea821fce480",
      "name": "4",
      "groupId": "2a39f666-254a-44ab-bd4b-402c7b61a6d7",
      "source": {
        "channel": 0,
        "number": 91,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "controlElementIndex": "AS/Osc2Waveform",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },
    {
      "id": "b17811c7-ce02-4ce0-902e-6ca94ca693b3",
      "name": "1",
      "groupId": "37ed3389-3c63-4618-91aa-c5c32cc33995",
      "source": {
        "channel": 0,
        "number": 7,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "fxIndex": 2,
        "fxGUID": "9D583EEF-A410-AB47-8AD5-61369270D8C4",
        "paramIndex": 104,
        "controlElementIndex": "AS/Osc1Level",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },
    {
      "id": "be73fa43-2ee6-4328-aac3-7b41d7f1cce0",
      "name": "2",
      "groupId": "37ed3389-3c63-4618-91aa-c5c32cc33995",
      "source": {
        "channel": 0,
        "number": 10,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "controlElementIndex": "AS/Osc2Level",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },
    {
      "id": "2020ed5a-a20c-4eed-9cc9-ca94890a6174",
      "name": "3",
      "groupId": "37ed3389-3c63-4618-91aa-c5c32cc33995",
      "source": {
        "channel": 0,
        "number": 11,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {},
      "target": {
        "category": "virtual",
        "fxAnchor": "id",
        "controlElementIndex": "AS/Osc3SubLevel",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      },
      "feedbackIsEnabled": false
    },
    {
      "id": "fe4560fb-af05-4c5e-b5af-a796993d2683",
      "name": "Osc Group",
      "source": {
        "channel": 0,
        "number": 57,
        "character": 1,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {
        "maxTargetValue": 0.0
      },
      "target": {
        "fxAnchor": "this",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      }
    },
    {
      "id": "56a46fb2-5639-45ea-8fe4-4419db62df1b",
      "name": "Mix Group",
      "source": {
        "channel": 0,
        "number": 64,
        "character": 1,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {
        "minTargetValue": 0.01,
        "maxTargetValue": 0.01
      },
      "target": {
        "fxAnchor": "this",
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      }
    }
  ],
  "activeControllerId": "midiplusx3mini",
  "activeMainPresetId": "j-8",
  "parameters": {
    "0": {
      "value": 0.01
    },
    "45": {
      "value": 0.34240195
    },
    "60": {
      "value": 0.6585366
    },
    "88": {
      "value": 0.70866144
    },
    "30": {
      "value": 0.45
    },
    "63": {
      "value": 0.68503934
    },
    "41": {
      "value": 0.35
    },
    "34": {
      "value": 0.89099264
    },
    "61": {
      "value": 0.5254902
    },
    "33": {
      "value": 0.9529412
    },
    "55": {
      "value": 0.4488189
    },
    "44": {
      "value": 0.17254902
    },
    "46": {
      "value": 0.6848039
    }
  }
}

**Comment by helgoboss** [comment]
Works for me. Maybe you have changed the main compartment parameter?

**Comment by vonglan** [comment]
Yes!
Thanks.
