### ISSUE TITLE
When I change the mapping target to "FX by name", in the Mappings list it is still displayed with the previous selection (by ID)

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#254]

**Comment by helgoboss** [comment]
This I don't understand. What's supposed to change? The FX selector is not showed in the mapping row target label, just the FX that it resolved to. So yes, if you switch from "By ID" to "By Name" and the FX exists, nothing will change. Intended.

**Comment by vonglan** [comment]
Ok. I assumes it would show the configuration. But of course if also (even more) makes sense that it shows the actual target.

**Comment by vonglan** [comment]
But the Track is displayed as <this> in the list, not the resolved track index.
