### ISSUE TITLE
Very Low Prio Bug: Changing a group's program does not activate the "save" button

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#266]
In the Controller Mappings (haven't tested in Main Mappings).

**Comment by helgoboss** [comment]
Can't reproduce. If you have a project, please attach.

**Comment by helgoboss** [comment]
Please reopen if you can attach a test project.

**Comment by vonglan** [comment]
I just removed a mapping while a mapping group of a Controller Mapping was displayed, and again "save" remained inactive.
I assume ReaLearn does not have a flag for remembering "something has been changed (maybe back and forth)", but compares the current and the saved state.

I assume this (my wrong reasoning about how ReaLearn works internally) was also the cause for reporting the original "issue".

Issue can remain closed.

**Comment by helgoboss** [comment]
Exactly, it compares the states.
