### ISSUE TITLE
Comment: Wording of Bank/Program

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#267]
I find this a bit confusing.
I think the following naming in the "Edit group" window would be better:
Active "When bank selected"
Bank Parameter "Ctrl P1"
Bank "1"

The "programs" are the individual mappings in a bank.

**Comment by helgoboss** [comment]
I think you are right. I wanted to stick to the MIDI Bank Select terminology in which you have banks and each bank has programs. But nearly every controller out there uses these words a bit differently and the analogy to MIDI Bank Select is not perfect.

The term "program" I would completely remove from ReaLearn. To say that the "programs" are the individual mappings in a bank would also be confusing. There are banks and each bank activates certain mappings. That's probably all the wording we need.
