### ISSUE TITLE
Utilise the preset name OR plugin name to autoload preset

### ISSUE THREAD

**Issue by STROUDICOUS** [helgoboss/realearn#272]
This is particularly useful for Kontakt instruments. Mappings vary a lot with different libraries, but ReaLearn will use the same mapping for all of them as it's loading based on the plugin, not the preset.

**Comment by helgoboss** [comment]
Hey @STROUDICOUS. Closing this because it's a duplicate of #220 .

**Comment by helgoboss** [comment]
Implemented in #220, part of upcoming 2.8.0-pre8.
