### ISSUE TITLE
Add targets "Send: Mono/stereo", "Send: Phase invert", "Track: Phase invert"

### ISSUE THREAD

**Issue by alfonso73** [helgoboss/realearn#280]
Hi! there are some track parameters that are not present in the destination menu.

1. Track Send mute
2. Track Send Mono/Stereo
3. Track Send Phase invert
4. Track Stereo Wideness
5. Track phase invert

thanks

**Comment by helgoboss** [comment]
1 and 4 exist

**Comment by alfonso73** [comment]
@helgoboss thanks. i didn't realized i was on 2.7.1...i've just updated to 2.8pre9. 
2, 3 and 5 would be great to,

**Comment by helgoboss** [comment]
2.8pre9 is a prerelease (for testing purposes). 1 and 4 exist since 2.1.0 already. I'll add the other targets at some point. Unfortunately they won't support automatic feedback - but that's the same for "Track send mute".

**Comment by alfonso73** [comment]
Thanks for adding this targets as future enhancements.
