### ISSUE TITLE
Some trouble using MIDI controller buttons for Track related parameters

### ISSUE THREAD

**Issue by alfonso73** [helgoboss/realearn#281]
Hi.
I was trying to automate a track send volume with a button for instant on/off since there's no Send Mute destination available.
So i noticed that using a MIDI button automating several Track related parameters works only in Trim/Read mode.
When in the other "writing" modes (touch, latch, etc.) it doesn't work reliably. Sometimes the automation is written but doesn't have any effect on the automated parameters.
thanks

**Comment by helgoboss** [comment]
Hi. It seems like you use an outdated version. There's definitely a send mute target for example. What version do you use?

**Comment by alfonso73** [comment]
I was 2.7.1...sorry i didn't realized it. Tomorrow i'll do some test with 2.8pre9

**Comment by helgoboss** [comment]
@alfonso73 Did you test this again already?

**Comment by helgoboss** [comment]
Closing for now. Can be reopened if still an issue.
