### ISSUE TITLE
Filtering of Matched Events seems not to work

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#284]
(pre9)
ReaLearn is in the track, before the VST.
Controller sends MIDI notes.
Notes arrive in VST, even though they were "consumed" in ReaLearn.
Here is one of the mappings where the note is not filtered:

    {
      "id": "fe4560fb-af05-4c5e-b5af-a796993d2683",
      "name": "Bank: Oscillators",
      "source": {
        "type": 1,
        "channel": 10,
        "number": 8,
        "character": 1,
        "isRegistered": false,
        "is14Bit": false,
        "oscArgIndex": 0
      },
      "mode": {
        "minTargetValue": 0.01,
        "maxTargetValue": 0.01,
        "outOfRangeBehavior": "min"
      },
      "target": {
        "fxAnchor": "this",
        "paramIndex": 100,
        "useProject": true,
        "moveView": true,
        "seekPlay": true
      }

**Comment by helgoboss** [comment]
That works here. Are you sure you have *Control input* set to `<FX input>`?

**Comment by vonglan** [comment]
No, until now I always have the Controller selected. Will try it later.

**Comment by vonglan** [comment]
Yes, of course it works. That is also how you described it in the User's Guide. And it is logical, because ReaLearn is not bound to the current track.

But: for other naive users, it would be nice to have the "let through" section greyed out and both checkboxes checked, in case a Control Input other than <Fx Input> is selected.

**Comment by ironirc** [comment]
I seem to have a similar issue with Realearn instance in the "In FX" chain. I have to put an extra cc filter after Realearn to filter out cc7.
![Scherm­afbeelding 2024-11-01 om 12 41 22](https://github.com/user-attachments/assets/ea09be1b-a7d0-44a2-b0fc-2c9df9ba1bd5)
![Scherm­afbeelding 2024-10-23 om 22 06 49](https://github.com/user-attachments/assets/5392a8de-210a-48d7-ba2a-b9837f2c23af)

**Comment by helgoboss** [comment]
Tested it again and it works here. Maybe it's a misconfiguration in the MIDI menu? Right-click "2 in" and make sure that MIDI output is set to "Replaces MIDI bus".

**Comment by ironirc** [comment]
Hi Benjamin,

I didn’t expect a reply so soon… thank you so much!
I’m now testing in an other setup… and it just works.
So the setting you mentioned was probably the cause of my problem (though I don’t remember messing with that setting).
Good to know about its existence.

Anyway, super super thanks for your help, and on the other hand sorry to have wasted your time.

Kind regards,
Ivo Roefs
