### ISSUE TITLE
How to best configure OB6 and X-Touch buttons (in Controller Mapping) to toggle a VST FX Parameter (in Main Mapping)

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#285]
I’m finished with the OB6 and TAL J-8 mappings (except for the incremental button details).
Now I am setting up the X-Touch Mini (which seems to be really good value - 44 Euros at Amazon).

I would like to go with its factory defaults as far as possible. The only adaption necessary so far is to set the encoders to Relative-1 as described in the ReaLearn User's Guide.
In the factory default, the buttons send note-on and note-off. I use 9 buttons to switch between banks. That works fine, also with feedback.
However, using some of them to switch „toggle“ parameters in the VST (like Oscillator Sync On/Off) seems difficult.  I could not get it to work (details below).
- Could "Incremental" with the upcoming "Rotation" in the Controller Mapping work?
- Or do I need to configure the buttons differently (instead of factory default)?

I am also wondering what the intended way is to configure the Controller Mapping for the OB6 for these buttons. I thought, the „Toggle“ mode would be important, but I could not get it to work for me.

Here are my experiments in detail:

**Part 1: OB6**
Controller Mapping for OB6:
Source: NRPN 14-bit, 0 or 1
Tuning/Source: Min=0, Max=1
Mode: Toggle Buttons
Target: Virtual Button

Main Mapping:
Source: Virtual Button
Mode: Toggle Buttons
Target: FX Parameter
—> Control does not work,  Feedback works

Changed Main Mapping Mode to „Normal“
—> still does not work

Changed both Modes (Contr+Main) to Normal
—> works!

Changed: Control Mode = Normal, Main Mapping Mode = Toggle
—> works partly (FX Parameter changes only every other time, I suppose because OB6 sends alternate NRPN values of 0 and 1 - see issue #269  )

**Part 2: X-Touch Mini**
Controller Mapping for X-Touch Mini:
Source: Note Velocity (The device sends note-on on press, then note-off on release)
Tuning/Source: Min=0, Max=127
Mode: Toggle Buttons
Target: Virtual Button

Main Mapping:
Source: Virtual Button
Mode: Toggle Buttons
Target: FX Parameter
—> Control does not work,  Feedback works. Signal is not filtered (note is sounded from VST), even though Control input is <FX Input>.

Changed: Control Mode = Toggle, Main Mapping Mode to „Normal“
—> still does not work

Changed both Modes (Contr+Main) to Normal
—> works, but as momentary switch (which I do not want)

Changed: Control Mode = Normal, Main Mapping Mode = Toggle
—> works, but Feedback does not work when changing the X-Touch (only when the VST GUI is changed)

I also tried setting them up as Virtual Multis instead of Virtual Buttons.
—> Did not change anything for the X-Touch (did not experiment with OB6 for this)

(By the way, when I changed from Button to Multi, it seemed to me that ReaLearn uses only the names of named virtual targets as key, and does not distinguish whether it is a Button or a Multi. Does not matter much, but I wanted to tell you.)

**Comment by vonglan** [comment]
Maybe I just have to reconfigure the X-Touch to send CCs from the buttons (instead of NoteOn/Off). Having Feedback for NoteOn/Off seems illogical anyway - although it did partly work.

**Comment by helgoboss** [comment]
> However, using some of them to switch „toggle“ parameters in the VST (like Oscillator Sync On/Off) seems difficult. I could not get it to work (details below).
> 
> * Could "Incremental" with the upcoming "Rotation" in the Controller Mapping work?
> * Or do I need to configure the buttons differently (instead of factory default)?

Most important thing: Configure your buttons as momentary buttons on hardware side. Everything else will give you a bad time. The "Toggle-button only" source character is the exception and should be avoided at all costs. It comes with disadvantages. Setting the button to "Incremental buttons" mode for the controller mapping should work. This is something I usually wouldn't recommend. It just makes sense in your #205 scenario.

> I am also wondering what the intended way is to configure the Controller Mapping for the OB6 for these buttons. I thought, the „Toggle“ mode would be important, but I could not get it to work for me.

Oh, I think I should hide "Toggle buttons" mode for virtual mappings. It doesn't make sense. Just use "Normal".

> Here are my experiments in detail:
> 
> **Part 1: OB6**
> Controller Mapping for OB6:
> Source: NRPN 14-bit, 0 or 1
> Tuning/Source: Min=0, Max=1
> Mode: Toggle Buttons
> Target: Virtual Button

Sorry, don't use "Toggle buttons" for virtual controller mappings. Oh wait ... and is this the OB6 "toggle-only" button? Then it wouldn't work anyway because you need to wait for the 14-bit side of #269.

> Main Mapping:
> Source: Virtual Button
> Mode: Toggle Buttons
> Target: FX Parameter
> —> Control does not work, Feedback works
> 
> Changed Main Mapping Mode to „Normal“
> —> still does not work

Both because of the invalid controller mapping.

> 
> Changed both Modes (Contr+Main) to Normal
> —> works!
> 
> Changed: Control Mode = Normal, Main Mapping Mode = Toggle
> —> works partly (FX Parameter changes only every other time, I suppose because OB6 sends alternate NRPN values of 0 and 1 - see issue #269 )

Exactly. Wait for #269. But *this* is the right setting in general.

> 
> **Part 2: X-Touch Mini**
> Controller Mapping for X-Touch Mini:
> Source: Note Velocity (The device sends note-on on press, then note-off on release)
> Tuning/Source: Min=0, Max=127
> Mode: Toggle Buttons
> Target: Virtual Button
> 
> Main Mapping:
> Source: Virtual Button
> Mode: Toggle Buttons
> Target: FX Parameter
> —> Control does not work, Feedback works. Signal is not filtered (note is sounded from VST), even though Control input is .
> 
> Changed: Control Mode = Toggle, Main Mapping Mode to „Normal“
> —> still does not work

Because of the invalid controller mapping.

> 
> Changed both Modes (Contr+Main) to Normal
> —> works, but as momentary switch (which I do not want)
> 
> Changed: Control Mode = Normal, Main Mapping Mode = Toggle
> —> works, but Feedback does not work when changing the X-Touch (only when the VST GUI is changed)

This is because the Behringer X-Touch devices are annoying. They try to handle LED lighting themselves AND by feedback. You need to activate "Send feedback after control". Activate that for the controller mapping.

> I also tried setting them up as Virtual Multis instead of Virtual Buttons.
> —> Did not change anything for the X-Touch (did not experiment with OB6 for this)
> 
> (By the way, when I changed from Button to Multi, it seemed to me that ReaLearn uses only the names of named virtual targets as key, and does not distinguish whether it is a Button or a Multi. Does not matter much, but I wanted to tell you.)

Really? This would be a bug. Created an issue.

**Comment by helgoboss** [comment]
> Maybe I just have to reconfigure the X-Touch to send CCs from the buttons (instead of NoteOn/Off). Having Feedback for NoteOn/Off seems illogical anyway - although it did partly work.

No, feedback for notes makes sense and is supported. Many feedback-enabled controllers use note on/off. See above why it doesn't work.

**Comment by helgoboss** [comment]
@vonglan BTW. I just enabled the "Discussions" tab. I think this is a more proper way to handle questions. If you are sure something is a request of a missing feature or a bug, feel free to open an issue. If not, please let's try the discussion tab from now on and see how it works out.

**Comment by vonglan** [comment]
Thanks for the detailed answer (and all the issues ...)!

> Most important thing: Configure your buttons as momentary buttons on hardware side. Everything else will give you a bad time. The "Toggle-button only" source character is the exception and should be avoided at all costs. It comes with disadvantages. Setting the button to "Incremental buttons" mode for the controller mapping should work. This is something I usually wouldn't recommend. It just makes sense in your #205 scenario.

Just to be sure: Should I also avoid the factory default (note on/off)? I am asking because this works similar to "momentary buttons", and you write that feedback works for it.
(I just configured the X-Touch Mini to send CCs only, and saved the Behringer configuration files. So there is no reason to keeping close to the factory defaults anymore.)

> Sorry, don't use "Toggle buttons" for virtual controller mappings. Oh wait ... and is this the OB6 "toggle-only" button? Then it wouldn't work anyway because you need to wait for the 14-bit side of #269.

Yes, these are also the OB6 "toggle-only" buttons.

> @vonglan BTW. I just enabled the "Discussions" tab. I think this is a more proper way to handle questions. If you are sure something is a request of a missing feature or a bug, feel free to open an issue. If not, please let's try the discussion tab from now on and see how it works out.

Makes sense, thanks.

**Comment by vonglan** [comment]
After trying out (no Toggle in Controller Mapping, set "Send Feedback after Control" for the X-Touch), it all works as expected. Thanks again.

I also saw that note on/off works just as well as CCs for the X-Touch Buttons.

Some suggestions regarding the wording in the User's Guide:
Maybe you want to change
> (but works correctly, thanks to the "Send feedback after control" 

to
> (but works correctly, if you switch on "Send feedback after control" in the mappings)

and
> Toggle: Toggle mode is a very simple mode that takes and optionally transforms absolute source control values. It's used to toggle a target between on and off states. Only makes sense for button-like control elements.

to
> Toggle: Toggle mode is used to toggle a target between on and off states, based on a momentary source (that means: 0 when button is pressed, higher than 0 as long as the button is pressed). Only makes sense for button-like control elements.

and maybe add somewhere in the X-Touch Compact section: "X-Touch Mini can be configured similarly".

**Comment by helgoboss** [comment]
> > Toggle: Toggle mode is a very simple mode that takes and optionally transforms absolute source control values. It's used to toggle a target between on and off states. Only makes sense for button-like control elements.
> 
> to
> 
> > Toggle: Toggle mode is used to toggle a target between on and off states, based on a momentary source (that means: 0 when button is pressed, higher than 0 as long as the button is pressed). Only makes sense for button-like control elements.

I guess you mean "0 when button is released"?

**Comment by vonglan** [comment]
yes
first part should be: 0 when button is not pressed

Unfortunately, the explanation (which should be simple) gets complicated because technically "button pressed" can mean 1 or 127 (or 0.01 on a different scale). Maybe leave that part in parentheses out.

**Comment by helgoboss** [comment]
I think this brings it to the point:

> Toggle: Toggle mode is used to toggle a target between on and off states. It only makes sense for momentary buttons (which fire a value > 0 on each press).

**Comment by vonglan** [comment]
Yes, that is simpler. Still, I would add something:

> which fire a value > 0 on each press, 0 when released

**Comment by helgoboss** [comment]
But the "0 when released" is actually optional in this case. Otherwise your "Toggle-only button" character would not work at all.

**Comment by helgoboss** [comment]
The button "release" event is (fortunately) in many use cases not required. At the top of my head it's only necessary for the fire modes.

**Comment by vonglan** [comment]
... or when a ReaLearn user actually want to use the "momentary" logic, e.g. for a real Shift-Button (not like the Shift function which I configured for the OB6, which is more like "Shift Lock").

> which fire a value > 0 on each press, optionally 0 when released

**Comment by helgoboss** [comment]
Oh, you are right. Totally forgot about the obvious case 😆

**Comment by helgoboss** [comment]
Adjusted user guide already.
