### ISSUE TITLE
Missing distinction between Multi and Button for named virtual control elements

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#287]

**Comment by helgoboss** [comment]
@vonglan You mentioned this in another ticket. I can't reproduce this. As far as I can see, ReaLearn distinguishes correctly e.g. between a Virtual Button named "main" and a Virtual Multi called "main". Closing.

**Comment by vonglan** [comment]
I think it had to do with changing from Multi to Button in one of the compartments, and then how that was visible in the list of mappings. But I cannot reproduce anything like that now either.
