### ISSUE TITLE
GUI wording: "Reload all"

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#291]
Can be misunderstood as "reload controller and main mapping".
Maybe change to "Reread Directory"?

**Comment by helgoboss** [comment]
Maybe just "Reload"? It's a more general issue. I guess I need to make more clear that everything right and below the Compartment dropdown relates to the compartment only. Maybe I will move this dropdown above everything else, introducing another row. This wastes screen space but it supports people who don't read the user guide.

**Comment by vonglan** [comment]
Maybe remove the button "Reload all" and show "<Refresh this list>" as the first or last item in the dropdown list? 

> ... supports people who don't read the user guide.

I think the majority of users don' read the user guide (at least not carefully), so I think the layout change would be good.

**Comment by vonglan** [comment]
... or two tabs

**Comment by helgoboss** [comment]
Tabs would be a good thing but there's no budget for that, see #233 (unless someone raises a reasonable bounty). Would need some research and experiments on my side to make that work, cross-platform.

Anyway, more of a nitpicking issue, I think there are more pressing ones. I think I will go for the layout change at one point.

**Comment by helgoboss** [comment]
I think I will completely remove that button and put it into the context menu.

**Comment by vonglan** [comment]
> Anyway, more of a nitpicking issue

definitely
