### ISSUE TITLE
Add support for compartment variables

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#298]
- For usage in `<Dynamic>` expressions.
- When accessing the variables in `<Dynamic>` expressions of a *main* mapping, main compartment variables should take precedence but it should fall back to controller compartment variables if no such main compartment variable exists. That way we a controller preset can offer good defaults, e.g. to let the main mappings know the number of channel strips in the controller.
- They should be saved as part of a preset but should also be editable ad-hoc.

**Comment by vonglan** [comment]
I assume you have already thought about using the existing parameters for this. 
(One problem with that would be that a convention "parameter 7 is always the number of channel strips" would be needed. This could be avoided if you have named parameters, e.g. v_nr_channel_strips.
Another problem might be that you cannot distinguish between "parameter is offered by main mapping, but currently 0" and "parameter is not offered".)

Are you sure it is always the main variable that should have higher priority?

(Just brainstorming, don't need answer/explanation.)

**Comment by helgoboss** [comment]
Yes, with parameters:

- Problem 1 is the non-existing naming
- Problem 2 is that their values are not supposed to be saved with the preset
- Problem 3 is that they can be changed too easily (by automation and stuff)
- Problem 4 is that they are private to the compartment from an expression point of view

... except problem 1 that's all by design. The compartment variables I have in mind (or maybe I should rather call them "compartment constants"?) are supposed to be rather constant and loaded as part of the preset.

The priority idea (and the idea that main mappings can also access controller compartment variables) is somewhat related to my specific use case. Which is that it should be possible for main mappings to access controller-specific information - in order to be able to adjust to specific traits of the controller, at least to a certain degree. Examples are "Number of channel strips" or "Does it have a shift button?".

But I think this order of precedence could also make sense in general. The usual case is that you have a handful of controller presets and much more main presets. So it seems natural that main presets overwrite stuff defined in controller presets rather than the other way around.

**Comment by helgoboss** [comment]
Mmh, but you are right, the question of priority is not that easy. One might want to use a variable in a main mapping as fallback if the controller doesn't define one ... maybe it would be better to let the expression itself decide by giving it access to both controller and main variables explicitly.

Issue with that:
- This would bring up the issue of 0 being equal to not defined (using the short-circuit logical operators e.g. `main_ch_strip_count || ctrl_ch_strip_count`)

Also, more brainstorming related to the parameter idea:

> Problem 1 is the non-existing naming

This could probably be solved because ReaLearn allows naming parameters.

> Problem 2 is that their values are not supposed to be saved with the preset

Well, I could save the values with the preset itself. But then the question of precedence comes up. When changing a preset, should the parameters coming from REAPER take precedence or the ones in the preset? Or maybe configurable on a per-parameter basis?

> Problem 3 is that they can be changed too easily (by automation and stuff)

Maybe not that relevant.

> Problem 4 is that they are private to the compartment from an expression point of view

This rule could be loosened, hoping that users don't abuse it. E.g. a main mapping could be allowed to access a controller compartment parameter by writing `ctrl_p1` (or if named properly: `ctrl_channel_count`).

Implementing "Compartment constants" in addition to parameters wouldn't be a big thing and I started already. I think I will put it to rest for now and give it more thought. One argument against "Compartment constants" could be that they are yet another concept users should know.

**Comment by vonglan** [comment]
> But I think this order of precedence could also make sense in general. The usual case is that you have a handful of controller presets and much more main presets. So it seems natural that main presets overwrite stuff defined in controller presets rather than the other way around.

I did not understand the use case for overwriting yet, only for reading controller characteristics (which makes sense to me).

> This would bring up the issue of 0 being equal to not defined

How about not allowing 0? Would be ok for number of channel strips. For shift, you would have to use 1 and 2 for yes and no. Not nice, but would be possible.

> Well, I could save the values with the preset itself.

Don't like this. Maybe use parameters 201 and up for these constants, and then only save/load these parameters with presets?
(By the way, I would prefer if there were fewer parameters, 20 or 50 per compartment; I dislike the scrolling in selection lists.)

> One argument against "Compartment constants" could be that they are yet another concept users should know.

I agree with that. But still, it seems like a valid use case that is currently not possible.

**Comment by helgoboss** [comment]
> (By the way, I would prefer if there were fewer parameters, 20 or 50 per compartment; I dislike the scrolling in selection lists.)

Too late. Once they are there, need to stick with it.

**Comment by vonglan** [comment]
Maybe ask the current users? I suspect that the number of users using that feature is still small. And I suspect that they also don't like the scrolling.
And I believe the number of users (maybe not of power users) will increase a lot.

But maybe I am wrong and someone has a use case where they need > 50 parameters.

**Comment by helgoboss** [comment]
I raised it up to 100 because of a user who had many modifiers. That's also the main use case where many might be needed. Either way, I have no way of reaching all users and ask them if they use all 100 parameters or not.

This might be improvable with a UI change one day.

**Comment by vonglan** [comment]
If there is a good use case, I would leave it as it is.

**Comment by helgoboss** [comment]
Note to self:

- In a broader sense, we already have compartment variables now: **Custom compartment data**. Custom compartment data was previously only usable in controller presets (for saving controller layouts used in the projection feature of the "ReaLearn Companion App") but at some point was made available for main presets as well. And not just for main presets. Also for the actual compartment data within ReaLearn. So one can also set it via Lua import. Custom compartment data that is not just a flat list of variables with integer values but an arbitrary formed JSON-like data structure. Introducing compartment variables in addition to that would be totally unnecessary now.
- I will start using custom compartment data now to satisfy the needs of Playtime: To save the column and row count of a control unit (which conforms to a ReaLearn unit). This is nicely in line with how custom compartment data was used so far: For an external/optional app to save custom data of arbitrary kinds. Plus, "ReaLearn Companion App" and "Helgobox App" will merge soon, anyway.
- Controller presets that want to expose the number of channel strips should also do it via custom compartment data in future. There's no way to access this data in expressions yet, but I could build one when the time comes (for the numeric properties only since expression are limited to numeric stuff).
