### ISSUE TITLE
Typo: Tuning / Source "Mi" instead of "Min"

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#299]
with rc.1
on OS-X Big Sur

<img width="284" alt="Bildschirmfoto 2021-04-07 um 22 30 06" src="https://user-images.githubusercontent.com/17814756/113929870-d5cf2600-97f0-11eb-943f-ef26fea3bd79.png">

**Comment by vonglan** [comment]
Also for "Speed"

**Comment by helgoboss** [comment]
Ah thanks, fixing.
