### ISSUE TITLE
Target variable evaluation in Control Transformation 

### ISSUE THREAD

**Issue by DLongoni** [helgoboss/realearn#3]
Currently in the Control Transformation y is not set to the target value right now before evaluating the formula. This means that formulas like 
y = x == 0 ? y : (y == 0 ? 1 : 0)
cannot work.

In Feedback transofrmation, on the other hand, a formula like x=x==0?62/127:60/127  for me works fine (colors are correct).

**Comment by helgoboss** [comment]
Implemented
