### ISSUE TITLE
Problem with "Learn Many" and feedback from another instance

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#303]
Just for information.

When I use "learn many", and turn the source button (which is correctly recognized as virtual source), suddenly multiple mappings are created for the same source. As target, they have the assigned target from a ReaLearn instance in a different track (track 1).

Track 1:
ReaLearn
Input: OB6
Feedback: OB6
Mapping includes OB6 Knob X --> Virtual X and Virtual X --> VST Param X

Track 3 (this is where I am learning):
ReaLearn
Input: FX Input
Output: None
Uses the same controller preset as track 1
When I use Learn Many in the Main Mapping, multiple mappings are created:
Virtual X --> Track 1 VST Param X

Maybe the "now touch the target" part is done by a feedback loop with the ReaLearn instance in track 1?

After I deactivated the ReaLearn instance, this problem did not reappear.

**Comment by helgoboss** [comment]
Sure this is not a duplicate of #232?

**Comment by vonglan** [comment]
of course ...
