### ISSUE TITLE
Add MIDI script source for LCD support

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#306]

**Comment by vonglan** [comment]
Is this for displaying text on a controller, like the Faderfox EC4?
That would be perfect for #205 , to have a controller with text fields for each encoder, and being able to send the texts from ReaLearn.
(On the other hand, I have the Maschine Mk3 which offers this functionality - and I was a bit underwhelmed when I actually used it. Might have to do with other disadvantages - no LED rings, "banks" only accessible with previous/next, and no standardized order of parameters.)

**Comment by helgoboss** [comment]
> Is this for displaying text on a controller, like the Faderfox EC4?

Yes. Provided that you know which MIDI messages have to be sent to the device. I use it e.g. with Mackie-style LCDs to display the position of the currently controlled track. Although you can send arbitrary MIDI messages to the device and therefore all kinds of display letters, ReaLearn supports only the current numerical target value as input, not something like "Track name" or "Target name". Definitely coming in future at some point.

**Comment by vonglan** [comment]
Good idea for the future.
Although the Faderfox EC4 only has 4 characters per button, and I did not find anything in the [manual](http://www.faderfox.de/PDF/EC4%20Bedienungsanleitung%20V02.pdf) about sending text to the device (only manual programming).

**Comment by helgoboss** [comment]
Faderfox EC4 LCD support is now implemented as MIDI Script Lua functions (experimental): https://github.com/helgoboss/helgobox/wiki/Faderfox-EC4
