### ISSUE TITLE
Separate virtual control element name picker into domains

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#307]
Domains:

- DAW (with all the Mackie-inspired names)
- Grid
- Linear (yes, I think we should remove the UI distinction between numbered and named and just consider numbers as strings, at least on user side)
- @vonglan Analog (when it's ready)

**Comment by helgoboss** [comment]
At this occasion, use the word ID rather than name?

**Comment by vonglan** [comment]
Not sure. In the virtual target drop down box, "<Named>" along with the list of numbers seems more intuitive than "<by ID>". Also, ID is already used (for the number or <Named>).

Maybe 
"ID Type" = "Number" or "Name"
"ID" = concrete number or 16-character-name

**Comment by helgoboss** [comment]
I'm going to remove the difference between number and name (at least in the UI). So actually I can use ID then.
