### ISSUE TITLE
Decoupling of Controller and Main Mapping / Problem with incremental buttons

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#311]
Now I looked in detail ( ;-) ) into the step and speed mechanism and documentation. And have lots of comments.

I will write something detailed under "Discussions".

For here, I think an important issue is:

If I use a controller like the OB6 that has a button for possibly continuous targets, e.g. "Cutoff Velocity Sensitivity", I want to use the "incremental button" mechanism to achieve something _more_ continuous (e.g. step through the range in 8 steps).
However, this forces me, in the Main (!) Mapping, to allow step size max of at least the speed min of the Controller Mapping.
Problem 1: Why should I have to configure something in the Main Mapping which only has to do with the controller?
Problem 2: If I alternatively want to use an encoder (on a different controller) for the same target, and do _not_ want acceleration, I cannot configure this because this requires step size max = 1.

**Comment by helgoboss** [comment]
> Now I looked in detail ( ;-) ) into the step and speed mechanism and documentation. And have lots of comments.
> 
> I will write something detailed under "Discussions".
> 
> For here, I think an important issue is:
> 
> If I use a controller like the OB6 that has a button for possibly continuous targets, e.g. "Cutoff Velocity Sensitivity", I want to use the "incremental button" mechanism to achieve something _more_ continuous (e.g. step through the range in 8 steps).
> However, this forces me, in the Main (!) Mapping, to allow step size max of at least the speed min of the Controller Mapping.
> Problem 1: Why should I have to configure something in the Main Mapping which only has to do with the controller?

Isn't this the same as we already discussed? The main mapping step max says what's *allowed* ... you used the right word there already. Even you make the controller mapping emit with high speed, if the main mapping doesn't allow it, it will not have an effect. It's just designed like this. For the main compartment, a virtual controller is no different than a real controller and i don't want there to be a difference.

So I suggest to live with it and increase the Step Size max of the main mapping. I can't imagine it's a big deal.

> Problem 2: If I alternatively want to use an encoder (on a different controller) for the same target, and do _not_ want acceleration, I cannot configure this because this requires step size max = 1.

You could also set the speed in the controller mapping of the encoder to 1x only.

Thoughts:
- If you have such fundamentally different control elements with such different behaviors, you might want to expose them as different virtual controls.
- You see everything very much from the perspective of your #205 use case which kind of bends ReaLearn already into a direction that's not its first goal, just a side goal.

**Comment by helgoboss** [comment]
I think the features you are looking for is actually 2:

1. Being able to override the Step Size Max setting of the main mapping from the controller mapping. (Similarly to rotate).
2. Being able to send absolute increments (e.g. increase by 5%) ... Which would be a completely new control value type because real-world controllers don't support this kind of control.

Just to name it. Not considering to implement that at the moment because you can use above mentioned alternatives to reach your goal.

**Comment by vonglan** [comment]
> So I suggest to live with it and increase the Step Size max of the main mapping. I can't imagine it's a big deal.

Correct.

> You could also set the speed in the controller mapping of the encoder to 1x only.

I hadn't thought of that. Good suggestion. And this also goes along with decoupling, keeping controller-related configuration in the Controller Mapping.

But I still do not see the use case for setting a "max step size" in the Main Mapping. Can be discussed under the "Discussion" topic (if you want to and have time).

> If you have such fundamentally different control elements with such different behaviors, you might want to expose them as different virtual controls.

No, I would not like that (and I think it is not needed). The virtual controls should be related to the domain (Analog Synth) not the way it is controller.

> You see everything very much from the perspective of your #205 use case which kind of bends ReaLearn already into a direction that's not its first goal, just a side goal.

That is a fair point.




> I think the features you are looking for is actually 2:
> 
> 1. Being able to override the Step Size Max setting of the main mapping from the controller mapping. (Similarly to rotate).

I am not sure whether I want that. I just don't feel comfortable with the concepts, see "Discussion".

> 2. Being able to send absolute increments (e.g. increase by 5%) ... Which would be a completely new control value type because real-world controllers don't support this kind of control.

Might be a new control type, not sure. I thought this was what ReaLearn means by incremental button.
Anyway, it is very useful for the use case "Hardware Synthesizer as controller", that only an on/off button is offered for some parameters like "Filter Cutoff Velocity Sensitivity", when the VSTs offer a continuous value for this parameter.

> Just to name it. Not considering to implement that at the moment because you can use above mentioned alternatives to reach your goal.

Perfectly ok. As said before, I like to discuss radically or brainstorm. But I am very grateful for what ReaLearn is able to do already, and these are minor points.
