### ISSUE TITLE
Make an accurate list of which mapping settings make sense for which kind of control elements

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#314]
- On/off only buttons
- Velocity-sensitive buttons
- Multis

**Comment by helgoboss** [comment]
A table which describes which settings make sense for which control element types: https://docs.google.com/spreadsheets/d/1gSWwbTB_lbjEREEwOpViSEOXNg0RJM2-ghBMS_cQhNI/edit?usp=sharing

It's how I think it should be, not necessarily how ReaLearn is already processing it (but I think in most cases it should be like this already).

Based on this, I can maybe implement some GUI element hiding. Of course that's only possible if I actually have some information about the control element, which is often not the case.

**Comment by vonglan** [comment]
I added some comments.
