### ISSUE TITLE
Fortin Hydra Midi Pedal

### ISSUE THREAD

**Issue by Jasonvander** [helgoboss/realearn#316]
Hello, I recently picked up the Fortin Hydra MIDI footswitch pedal hoping to get Reaper to replace my guitar pedal board.

When I use it with ReaLearn the PC change numbers are not recognized and 7 of the 8 buttons on the pedal will control the PC ReaLearn mapping instruction. I assume ReaLearn sees all buttons as one button rather than separating them? Note that PC 0 is not recognized but PC1 - 7 are and all 7 will activate the ReaLearn mapping instruction. This is not ideal.

What I'm trying to do is mute/disarm Track 1 with PC 0, mute/disarm Track 2 with PC 1, mute/disarm Track 3 with PC 2, etc., etc.

Any advice on how to achieve this with this simple footswitch?

The PC numbers are showing up in MIDI OX no problem and if I control the Fortin Amp simulator the PC numbers are showing up as well. Just in Reaper/ReaLearn they are not.
![5](https://user-images.githubusercontent.com/82330414/114313199-8f651a00-9ac3-11eb-950e-3e72a570590b.PNG)
![4](https://user-images.githubusercontent.com/82330414/114313201-8f651a00-9ac3-11eb-91fe-80d880c0917e.PNG)

![3](https://user-images.githubusercontent.com/82330414/114313104-2a112900-9ac3-11eb-8202-d527e3ed1097.PNG)
![2](https://user-images.githubusercontent.com/82330414/114313105-2a112900-9ac3-11eb-8d8d-e78eee49bac5.PNG)
![1](https://user-images.githubusercontent.com/82330414/114313107-2a112900-9ac3-11eb-86cc-0a425c196249.PNG)

**Comment by helgoboss** [comment]
It's important to understand that the *value* of a "Program change" MIDI message is a program number (a value between 0 and 127). It's a bit strange to use "Program change" MIDI messages to switch on/off things, but you can do it:

- Set "Source Min" and "Source Max" to the same program number (the specific program number that you want to "react" to).
- Set "Out-of range behavior" to "Ignore".

I'm closing this but you can comment if you have further questions.

**Comment by Jasonvander** [comment]
Thank you for the tips!

I'm curious how you would setup the Hydra pedal to toggle on/off Track FX, Arm Track/Mute Track, etc. in Reaper using ReaLearn? It sounds like there is a much simpler way to do this. Please let me know.

I really appreciate this advice, I've been spending weeks trying to figure it out.

**Comment by helgoboss** [comment]
If this pedal sends program changes, then no, there's no simpler way to do it - at least not for the initial setup.

BUT: If you plan to use ReaLearn's "Learn target" function a lot with your pedal (if you often want to change what the buttons should do), then I would recommend you:

- Create a controller preset that has a mapping for each button.
- Each mapping should have above settings for "Source Min/Max" and "Out-of-range behavior".
- The target should be Virtual Buttons with different numbers.

Then, whenever you select this controller preset in ReaLearn, the Hydra buttons will appear to the main mappings really as buttons and you will be able to learn them easily.

**Comment by Jasonvander** [comment]
This unbelievably helped me, thank you so much! It would have taken a million years to figure this out without your advice.
