### ISSUE TITLE
Various defaults in Mappings

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#318]
Low Prio.

If source is a Virtual Button, the default should be Mode „Toggle buttons“

For sources with character = relative, the default should be speed max = 5

For virtual multi sources with target FX parameter, the default _could_ be step/speed max = 5 (although for discrete FX parameters in VSTs, this needs to be adjusted to the specific value, e.g. 33.3333)

**Comment by helgoboss** [comment]
> If source is a Virtual Button, the default should be Mode „Toggle buttons“

Why? (I never do things without reasoning.)

> For sources with character = relative, the default should be speed max = 5

You mean "Speed max" = 5x for discrete targets and "Step size" = 5% for continuous targets.

Okay, here I guess the reason is what we discussed in the other issue (making users aware that acceleration is supported)?

> For virtual multi sources with target FX parameter, the default _could_ be step/speed max = 5 (although for discrete FX parameters in VSTs, this needs to be adjusted to the specific value, e.g. 33.3333)

If I change the default for "Step size Max" and "Speed Max", I will change it generally, not just for specific targets.

If the VST parameter is reported as discrete, "Speed Max" will apply, not "Step size Max". "Speed Max" will take the atomic step size into account, so 5x will mean "5x the atomic step size".

**Comment by vonglan** [comment]
> > If source is a Virtual Button, the default should be Mode „Toggle buttons“
> 
> Why? (I never do things without reasoning.)

I _thought_ that there is a natural 1:1 connection between the two things. Thinking about it again, one might also want to map a Virtual Button into a Momentary Button. But I assume "Toggle Button" is the 90% case.
 
> > For sources with character = relative, the default should be speed max = 5
> 
> You mean "Speed max" = 5x for discrete targets and "Step size" = 5% for continuous targets.

Yes. Actually, I was thinking of Controller Mapping only here, see below regarding Virtual Multis.

> Okay, here I guess the reason is what we discussed in the other issue (making users aware that acceleration is supported)?

Yes. Making them aware. And in 90% of cases I think this is what you want.
 
> > For virtual multi sources with target FX parameter, the default _could_ be step/speed max = 5 (although for discrete FX parameters in VSTs, this needs to be adjusted to the specific value, e.g. 33.3333)
> 
> If I change the default for "Step size Max" and "Speed Max", I will change it generally, not just for specific targets.

Yes. I wrote "could" because I think there will be more than just a few cases here, where the user wants something different than default.

> If the VST parameter is reported as discrete, "Speed Max" will apply, not "Step size Max". "Speed Max" will take the atomic step size into account, so 5x will mean "5x the atomic step size".

Yes. The intention is the same as above: make it default that acceleration is enabled.

**Comment by helgoboss** [comment]
> > > If source is a Virtual Button, the default should be Mode „Toggle buttons“
> > 
> > 
> > Why? (I never do things without reasoning.)
> 
> I _thought_ that there is a natural 1:1 connection between the two things. Thinking about it again, one might also want to map a Virtual Button into a Momentary Button. But I assume "Toggle Button" is the 90% case.

Would be careful with this kind of assumption. I use momentary style very often for example. Toggle would also be a bad default for trigger-like targets.

**Comment by helgoboss** [comment]
Closing this because step size / speed default will be changed as part of #300 already.
