### ISSUE TITLE
Always Preserve gap between values for <all selected> targets

### ISSUE THREAD

**Issue by ElVicente** [helgoboss/realearn#327]
For mixing purpose it'd be great to not be afraid of losing gap between values when moving targets values.

**Comment by ElVicente** [comment]
It would be more consistent if it keeped reaper's mixer behavior : eg: two volume tracks with a gap of 6 db, select both when going down both goes to -inf, but when going upper values the gap is still there.

**Comment by PucksEvilTwin** [comment]
This seems to work now?

I just tested with two selected tracks with "selection ganging" checked.  The two tracks both went down to -inf and still had the gap between them when brought back up.  Am I missing something?

**Comment by helgoboss** [comment]
> This seems to work now?
> 
> I just tested with two selected tracks with "selection ganging" checked. The two tracks both went down to -inf and still had the gap between them when brought back up. Am I missing something?

Selection ganging is different from "All selected". It uses REAPER's own way, which only works for track properties (not in general for each ReaLearn target) BUT preserves gaps. This was not available yet from ReaLearn at that time. Now it is and I think we could close the ticket. Unless someone wants this to work for all target types with "All selected" or " All named", but then they can open a new ticket.
