### ISSUE TITLE
Saving the Main  Mapping does not inactivate the "Save" Button

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#332]
Worked before.
Maybe something to do with the GUI hiding mechanism?

[Clipboard.txt](https://github.com/helgoboss/realearn/files/6353586/Clipboard.txt)
[Presets.zip](https://github.com/helgoboss/realearn/files/6353592/Presets.zip)

**Comment by vonglan** [comment]
While researching the JSON for another question, I noticed that sometimes there are lines
`        "oscArgIndex": 0
`
in JSON, sometimes not. Might have something to do with it (I do not use OSC).

**Comment by helgoboss** [comment]
Can't reproduce.

The `oscArgIndex` is normal. ReaLearn saves every setting which doesn't correspond to some internal default. Doesn't have any influence.

**Comment by vonglan** [comment]
Can't reproduce it now either. But it was definitely happening.

**Comment by vonglan** [comment]
Just observing that again. I made a diff on the main mappings from preset vs. main mappings from exported clipboard.
This is the difference:

clipboard has:
```
         "fxAnchor": "id",
         "fxIndex": 1,
         "fxGUID": "527318EF-CAE5-2846-B246-D47B93945D20",
```

main mapping preset has:
```
         "fxAnchor": "focused",
```

**Comment by helgoboss** [comment]
Finally I know what you mean. You are thinking the "conversion to project-independent mappings" happens on the current mappings. But it doesn't. It's only done for the preset. Hence, the current mappings deviate from the ones in the preset. Although working exactly as intended, I see that this can raise confusion. Probably I will apply the conversion to the current mappings as well.

**Comment by vonglan** [comment]
I have some thoughts about the FX selection defaults, will open a separate Issue as suggestion (could also be opened under "discussion", but there is so little traffic there I think it makes more sense here)
