### ISSUE TITLE
Organize clip slots in grid

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#336]
Allow choosing clip slot via 2 number fields (row, column). Also allow entering nothing , then all slots in that row/column are affected. Also allow dynamic expression, good for grid controller navigation buttons.

**Comment by patmaddox** [comment]
Is this a ReaLearn issue, or meant for Playtime? (there are a couple other issues that reference clips, which I don't _think_ is a ReaLearn concept...)
