### ISSUE TITLE
"Focussed" FX not working

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#338]
I do not normally use/need this feature so far, but as it is the default when first saving a preset (if I confirm the popup), some mappings temporarily have this.

When I reloaded the project later, I noticed that ReaLearn does not seem to find the focused FX anymore.

[Archiv.zip](https://github.com/helgoboss/realearn/files/6371340/Archiv.zip)

**Comment by helgoboss** [comment]
I don't understand what's the problem here. `<Focused>` means it will take whatever FX is currently focused. In your screenshot it's ReaLearn itself, so it seems to work. What would you expect?

**Comment by vonglan** [comment]
No, in the screenshot the VST is focused.
See the screenshot here, how it looks if ReaLearn is focused.
Anyway, even with this new screenshot, the parameter is correctly displayed. VST does not have the current focus, but the latest one before ReaLearn.

As I wrote, I do not use this feature. But it seems to me that something odd is going on.

<img width="1139" alt="Bildschirmfoto 2021-04-26 um 21 32 05" src="https://user-images.githubusercontent.com/17814756/116140337-7e2d2780-a6d7-11eb-9639-e00bb6664e72.png">

**Comment by helgoboss** [comment]
I invested quite some time to reproduce this but without success. I replaced the TAL stuff with ReaSynth because I don't have that plug-in. For reproduction I'm going to need detailed step-by-step instructions and a project that only uses ReaLearn and Cockos plug-ins.

**Comment by vonglan** [comment]
I just had this again, after I changed the JSON manually (copy&paste of about 8 mappings related to the same virtual source Osc1Waveform, to Osc2Waveform), then reloaded it.

When trying to reproduce it with ReaSynth, I encountered a different thing:

"Learn Target" does not work for ReaSynth (maybe the problem only occurs in combination with my X-Touch controller mapping?)

[Temp Bug.RPP 2.zip](https://github.com/helgoboss/realearn/files/6417697/Temp.Bug.RPP.2.zip)

**Comment by helgoboss** [comment]
Tried your project but can't reproduce anything strange of this kind.

Can you tell exactly (step by step, really detailed) what you did and what you would expect but didn't happen?

**Comment by vonglan** [comment]
- Load project "Temp Bug"
- Focus on ReaLearn window
- Press "Learn Target" for Mapping 1
- Focus on ReaSynth window
- Move "Tuning"
- --- Now it works as expected! Let's go on and see if I can reproduce any other problem
- Press "Save" for Main Mapping
- Answer Popup with "yes"
- "Save" button in ReaLearn is still active - I would expect it to be inactive   --- at least one problem reproduced :-)
- Editing JSON of Main Mapping in external editor: copy the one mapping, change source to Osc2Pitch
- ReaLearn: Reload all presets from disk
- Says "not present" this time???  --- Ah, reason is that I forgot to add a comma in JSON after the first mapping (could say "JSON syntax error" or "incorrect format")
- Added the comma in external editor
- ReaLearn: Reload all presets from disk
- ReaLearn: Reload SY reasynth preset
- Learn Target for the second Mapping: to ReaSynth "Release"
- Press "Save" for Main Mapping
- Answer Popup with "yes"
- Still, "Save" button is shown active
- In Overview, first mapping shows target FX <focused>, second one shows "FX 2. ReaSynth" --- seems strange
