### ISSUE TITLE
Automatic action on/off feedback doesn't work if it's a toggleable ReaScript AND triggered from toolbar button

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#347]

**Comment by helgoboss** [comment]
Just debugged this. Neither `hoostpostcommand` nor `hookpostcommand2` is called in that case - which I use to get informed about action invocation and sending corresponding feedback (without having to query action states *regularly* and *for all actions*). `toggleaction` is called as reaction to `RefreshToolbar`, but not for the ReaScript action button. Could be a bug in the REAPER API or by design (because why invoke C++ callbacks when it's clear that this is ReaScript only). Anyway, I have reported it to Justin. Let's see.

**Comment by helgoboss** [comment]
@rstockm Justin wrote he has fixed it so that `hookpostcommand2` gets called in this case. Then ... with the next REAPER release it should work without further ado. At least I hope so :) I'll keep the ticket open until confirmed.

**Comment by rstockm** [comment]
And here it is:

https://www.landoleet.org/whatsnew-dev.txt
+ API: run hookpostcommand2 hooks for reascripts and custom actions

Will test it soon.

**Comment by rstockm** [comment]
Works like a charm! Perfect.

**Comment by helgoboss** [comment]
Great, then I will close this.
