### ISSUE TITLE
Other defaults for target FX selection?

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#353]
Currently, when I "learn" an FX parameter, ReaLearn identifies the FX `by ID` ("Learn" default)
When I save a preset, ReaLearn offers to change this to `<focused>` (popup default)
Are these the best defaults?

From the way I use ReaLearn, the best default would be
`<This>` track + `by name` (maybe pattern - to allow VST or AU or ...)

(As a workaround, I always adapt these in VIM with a `:%s` command.)

For what use cases is `<focused>` FX better than  `By name` FX?
I can only think of the case that you have multiple instances of the _same_ FX in the _same_ track (e.g. multiple ReaLearns, or certain MIDI effects). I _assume_ this is a rare case, so then it should not be the "Learn" default, also not the popup default.

Are there other, more important use cases, or other disadvantages?
One central ReaLearn controlling "identical" FX in different tracks? But then, event filtering does not work.

Otherwise I think it would be an improvement to have `by name` as the default FX selector (with the exact name, to keep it simple; or optionally with a name pattern - maybe based on already existing mappings in the same instance/compartment).

**Comment by vonglan** [comment]
By the way, it seems FX selection `by Name` is missing in the current user guide (only explained for Track selection)

**Comment by helgoboss** [comment]
> Currently, when I "learn" an FX parameter, ReaLearn identifies the FX `by ID` ("Learn" default)
> When I save a preset, ReaLearn offers to change this to `<focused>` (popup default)
> Are these the best defaults?

All depends on the use case. I use ReaLearn mainly as performance tool for spontaneous ad-hoc mappings. That was its first purpose ever. For this "By ID" makes the most sense because I don't want any surprises when I move FX to other positions or rename them.

> From the way I use ReaLearn, the best default would be
> `<This>` track + `by name` (maybe pattern - to allow VST or AU or ...)

This satisfies other needs, yes.

> For what use cases is `<focused>` FX better than `By name` FX?

For "Auto-load: Depending on focused FX" which is a popular usage scenario. But this is something I want to change/generalize via #228 anyway.

> I can only think of the case that you have multiple instances of the _same_ FX in the _same_ track (e.g. multiple ReaLearns, or certain MIDI effects). I _assume_ this is a rare case, so then it should not be the "Learn" default, also not the popup default.

You are talking about "By ID" again I guess. Reason explained above.

> Otherwise I think it would be an improvement to have `by name` as the default FX selector (with the exact name, to keep it simple; or optionally with a name pattern - maybe based on already existing mappings in the same instance/compartment).

You should vote for #159. Seems like an unbiased solution where everybody's needs can be satisfied.

**Comment by vonglan** [comment]
Ok, you have a much better overview of the different usage scenarios.
