### ISSUE TITLE
"Prevent echo feedback" possibly broken in v2.8.2?

### ISSUE THREAD

**Issue by Hochaufloesend** [helgoboss/realearn#361]
After updating ReaLearn from v2.7.1 to v2.8.2, the "Prevent echo feedback" feature seems not to work anymore.
Turning the encoders on the BCR2000 has become "jumpy" again, same behavior like in v2.7.1 with said feature turned off.

**Comment by helgoboss** [comment]
You are right. Fixed already and coming in 2.9.0.
