### ISSUE TITLE
Add option to not let "Exclusive" switch everything else on if this is switched off

### ISSUE THREAD

**Issue by grnprplorngyllw** [helgoboss/realearn#365]
Hi!
Very happy with ReaLearn, thank you very much.
I have an issue. If I exclusive solo (within project) a track through ReaLearn, as soon as I remove the solo, all the other tracks get soloed and make my PC almost freeze haha. Please help!
I am trying to switch back and forth between a reference track and soloed tracks.

**Comment by helgoboss** [comment]
"Exclusive" works in both directions, solo and unsolo. Usually if you use "Exclusive", you have multiple buttons set to "Press only" (important) and each button soloes a different track.

Not sure what exactly you are trying to achieve.

**Comment by helgoboss** [comment]
I'm going to close for now because it seems to be more a question than an issue. You can still write replies. In future, better use the forum for questions.

**Comment by helgoboss** [comment]
I decided to add a small new feature that lets you choose if the exclusivity will only be applied when switching on or only when switching off. That makes some toggle-like scenarios possible that I didn't have in mind before. Maybe also yours.

**Comment by grnprplorngyllw** [comment]
Thank you so much man!
I will check it out today, to see if i manage to get it to work. Thanks!!!!!

**Comment by grnprplorngyllw** [comment]
Hello helgoboss. I just posted on the forum at GitHub and Reaper because I just cannot get this right lol.Thank you. From: Green prplSent: Sunday, May 16, 2021 9:52 AMTo: helgoboss/realearnSubject: Re: [helgoboss/realearn] Help with exclusive solo within project (#365) Thank you so much man!I will check it out today, to see if i manage to get it to work. Thanks!!!!! El dom., 16 de mayo de 2021 4:59, helgoboss ***@***.***> escribió:I decided to add a small new feature that lets you choose if the exclusivity will only be applied when switching on or only when switching off. That makes some toggle-like scenarios possible that I didn't have in mind before. Maybe also yours.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by grnprplorngyllw** [comment]
I just posted on Github forum and the reaper forum as well, cause I cant figure it out. Thank you!!

**Comment by helgoboss** [comment]
The new feature is not implemented yet. Concerning your specific issue, I'll reply in the REAPER forum where you posted the full story.

**Comment by helgoboss** [comment]
There are 3 places in which we should add this new form of exclusivity:

1. Track exclusivity
    - Within a tracks (on only)
    - Within folder (on only)
2. Group interaction
    - Inverse control (on only)
    - Inverse target value (on only)
3. "ReaLearn: ..." targets that support the "Exclusivity" dropdown
    - Exclusive (on only)

**Comment by helgoboss** [comment]
@grnprplorngyllw Finally implemented in upcoming ReaLearn v2.11.0-pre.2.
