### ISSUE TITLE
Add Nektar Panorama P6 controller preset

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#374]
Here is a second controller preset, this time for the Nektar Panorama P6 (https://nektartech.com/panorama-p4-p6/). I mapped the so-called Internal mode of this device. This device can quickly switch between multiple DAW controller modes and one plain MIDI controller mode with dedicated buttons for that, the Internal mode turns the device into a plain MIDI controller. 

Again, I included mappings for all the controllers of the device (in Internal mode) that do send some MIDI CC message, but also pitch bend. In other words, I left unmapped the control elements sending MIDI notes such as the keys and pads, but also special keys like [Shift] and [F-Keys], the two toggle buttons, the [Pads] button, the menu and mode buttons and data encoder. 

This controller preset assumes some minor modifications of the Internal mode. All the rotary controllers have been switched from absolute to relative CC mode. Also, the single motor fader at the right was switched from CC 7 to CC 11.

Note that the shift key is not mapped directly. Instead its effect is used, so that the plain and shifted navigation buttons are contained in the mapping with their own respective CC messages. 

Also note that this device does not support MIDI feedback. The keyboard connects to Reaper via ReWire and additionally with a single MIDI input port, but no output port. 

I think the actual mappings of the control elements could again be considered finished, but I am again not quite happy with the arrangement of the controller element representations in the projection. These elements are currently arranged in a way that is very similar to how they are laid out on the actual device, but this results in a rather wide projection view. I am currently considering to quasi split this view in the middle and arrange the right half below the left half or the other way round so all elements are more compactly shown on something like a tablet. Could that confuse other users? Any better idea?

Anyway, below is the link. Again, comments for improvements are most welcome.

[nektar-panorama-p6.json.zip](https://github.com/helgoboss/realearn/files/6518422/nektar-panorama-p6.json.zip)

_Originally posted by @tanders in https://github.com/helgoboss/realearn/discussions/373#discussioncomment-765232_

**Comment by helgoboss** [comment]
Thanks a lot for the contribution. I finally managed to make this available [here](https://github.com/helgoboss/realearn/tree/master/resources/controllers/unofficial). Not in ReaPack because unfortunately I can't find enough time to look into those presets and check if they adhere to the standards.

> I am currently considering to quasi split this view in the middle and arrange the right half below the left half or the other way round so all elements are more compactly shown on something like a tablet. Could that confuse other users? Any better idea?

I guess that's the best approach so far.

**Comment by tanders** [comment]
Dear Benjamin,

Thanks for your continued maintenance. 

> Not in ReaPack because unfortunately I can't find enough time
No problem. 

Feel free to use in the table of the Readme my full name (Torsten Anders) or a link to my tanders Github profile (http://github.com/tanders/).

https://github.com/helgoboss/realearn/tree/master/resources/controllers/unofficial

Noch einen schönen Tag,
Torsten

**Comment by helgoboss** [comment]
>  Feel free to use in the table of the Readme my full name (Torsten
Anders) or a link to my tanders Github profile (http://github.com/tanders/).

Done :)
