### ISSUE TITLE
System exclusive raw midi as mapping source

### ISSUE THREAD

**Issue by LukasLUH** [helgoboss/realearn#376]
Loving your work mate.
Are you planning on adding system exclusive raw midi data as a source? More precise, I´m using the Minilab mkii as main midi controller and want to map the "shift" or "octave up/down" buttons with specific features disregarding or complementing their initial functions. Would this be possible at all?

**Comment by helgoboss** [comment]
It would be possible. The only reason I didn't add it was because I was not sure if there are even controllers out there which send sys-ex messages for *control* purposes (not just *save my data* purposes). Are you sure the MiniLab sends sys-ex `data when pressing Shift?

**Comment by LukasLUH** [comment]
![image](https://user-images.githubusercontent.com/40164928/119572401-f4927780-bdb2-11eb-94a6-b1e1fa7e907e.png)

Thanks for quick reply. I´ve attached a file:
This is what ReaControl logs for pressing and releasing the shift key on my mkii.

**Comment by helgoboss** [comment]
Okay, looks convincing :) I'll see when I can add this feature. A bit much other stuff to do at the moment.

**Comment by LukasLUH** [comment]
Thanks a ton! Looking forward to it :)

**Comment by Ex8ey** [comment]
Confirmed. Arturia KeyLabs send SysEx to the host. This is how it communicates with Arturia software while still acting as a generic controller otherwise.

Would be great to see SysEx as a source, even if not accepting a range of SysEx but one specific SysEx event.

**Comment by helgoboss** [comment]
In upcoming 2.11.0-pre.1 this will be possible, including range support, learning and logging.
