### ISSUE TITLE
Zebra: How to learn 'OSC 1: SpectraFX1 Type'

### ISSUE THREAD

**Issue by SteffenPL** [helgoboss/realearn#381]
I cannot use 'OSC 1: SpectraFX1 Type' in Zebra as a target.
It isn't one of the parameters 'by position' and I cannot 'learn' it with ReaLearn as well.

Is there any trick or is that a VST specific problem?

(I first posted here: [kvraudio u-he](https://www.kvraudio.com/forum/viewtopic.php?f=31&t=566147) )

![Capture (1)](https://user-images.githubusercontent.com/4634605/120982965-8b7b0e80-c779-11eb-822d-8ec97504bd32.PNG)

**Comment by helgoboss** [comment]
Zebra doesn't seem to expose this parameter as VST parameter. However, if Zebra lets you control this paramter via MIDI (as suggested in the KVR thread), then use the "MIDI: Send" target. This is one of its main purposes. I'll close this issue for now.

**Comment by SteffenPL** [comment]
Thanks! That works for me :)
