### ISSUE TITLE
Please support feedback for Anymute, Anysolo, and Anyrecarm.

### ISSUE THREAD

**Issue by Poofox** [helgoboss/realearn#382]
The SWS toolbar toggle actions for record-arm, mute and solo don't report their state immediately to ReaLearn or OSC when arming, soloing or muting a track; only when toggling those actions directly.

Any chance you could support such a feature?  E.g. blinking lights on a controller would be a most obvious indicator that a track somewhere is armed, muted or soloed and a convenient way to toggle all armed, soloed or muted tracks at once.

Thanks.

**Comment by helgoboss** [comment]
Could you outline how these "anyX" stuff works? Don't know it. But I guess it wouldn't be hard to add.

Yes, REAPER actions are not very reliable when it comes to reporting feedback, this needs to be handled within ReaLearn.

**Comment by Poofox** [comment]
Oh Sorry, it's just an indicator when any track in a project is muted, soloed or armed.  Make sense?  The toolbar actions are convenient for toggling the state of all tracks based on what is currently armed, muted or soloed but they don't seem to provide reliable feedback outside the toobar buttons...

________________________________

**Comment by Poofox** [comment]
In case it wasn't clear, these actions should trigger an "on" state for feedback as a soon as any track in the project is soloed, muted or armed.

________________________________
