### ISSUE TITLE
selected_track_index variable 

### ISSUE THREAD

**Issue by dissofiddle** [helgoboss/realearn#386]
Hello, 

I am adding "first_selected_track_index" variable for dynamic "expression" as seen in reaper forum 

https://forum.cockos.com/showpost.php?p=2454189&postcount=1403

**Comment by patmaddox** [comment]
Evidently there are more variables than p1 etc (`this_track_index` is one mentioned in the forum thread). Is that the only one besides the parameters? Are they documented anywhere?

**Comment by helgoboss** [comment]
Documented in user guide in the "Target" section (`<Dynamic>`).
