### ISSUE TITLE
Allow conditional activation based on target state

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#392]
Example use case: Map encoder to transpose function only if sound mapping switched on.

**Comment by patmaddox** [comment]
Would this be like a virtual parameter, where the parameter value is whether the mapping is active or not? And then you'd reference it in the "Active when EEL result > 0" section?

**Comment by helgoboss** [comment]
It will be something like an additional option "When target value of mapping X is > 0" in the "Active" dropdown. Another dropdown will appear next to it which lets you choose that mapping X. If this is implemented, you can make the activation state of a mapping (on/off) depending on all kinds of factors, e.g. values of FX parameters of totally different plug-ins ... or mute state of a track.

**Comment by helgoboss** [comment]
In this context, conditional activation of the complete instance would be nice. It provides a non-global alternative to "Auto-load depending on focused FX". The beauty of this is that we can have a completely self-contained project (which doesn't rely on any global presets being installed) with ReaLearn instances, each of which turns active only when a specific FX is focused. This feature would be complete if we provide one more FX selector "By FX ID" (the same FX ID that drives our "Auto-load depending on focused FX).

**Comment by helgoboss** [comment]
Target-value based conditional activation is now implemented, yeah!
