### ISSUE TITLE
Confusing conversion behavior/display for min/max step size

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#397]
Release 2.9.1
In Main Mapping, target: Monark, Parameter Key Tracking (values: 0 or 10,000).
In tuning / step size, after I choose „make absolute“, when I enter Step Size Min = 33.33, ReaLearn changes this to 0 % 0. When I enter 3333, ReaLearn changes this to 33.33 % 33.33.

**Comment by helgoboss** [comment]
That's a feature actually. If the controlled plug-in supports parsing parameter values (which Reaktor/Monark seems to do, great!), ReaLearn lets you enter these values directly, not percentages. If the plug-in does this parsing in a nonsense way (which Reaktor/Monark seems to do, not great!), ReaLearn can't know.

What would you suggest to deal with this issue?

**Comment by vonglan** [comment]
If the faulty/confusing logic is in the NI area, then leave ReaLearn as it is.
