### ISSUE TITLE
Improvements to conditional activation

### ISSUE THREAD

**Issue by jackmau** [helgoboss/realearn#43]
Hi @helgoboss ,
first of all congratulation for including this feature, I found it really useful for my workflow. It overall works well but there are a couple of issues on my end (Reaper 5.99, Windows x64).

1. Realearn (and reaper) crash every time I try to visualise automation lane for the new Parameters.
2. When using conditional activation with program selected (the one I found more useful for my purposes) I am annoyed by the mismatch created by the 0-indexing structure of Rust (or reaper C++ API?), i.e. a parameter with program 1 selected is actually seen as 0, 2 as 0.01 and so on, this makes assigning parameter value from another realearn instance painful, as I always have to remember to add 1 to get to my target. It would be helpful if either parameter program would start from 0 or the underlying parameter values would start from 1.

**Comment by helgoboss** [comment]
@jackmau I could reproduce the crash. Looking into it.

**Comment by helgoboss** [comment]
Concerning number 2, I agree this is confusing. I will let the program numbers start with 0. Letting the parameter start from 1 (0.01) would be a breaking change and would raise the question what parameter value 0.00 is supposed to mean then.
