### ISSUE TITLE
Set FX param / Track * / FX by name - should this work?

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#430]
I would like to access multiple, identically named FX (ReaLearn instances that filter out a range of events, but that does not really matter) in multiple tracks. I thought this should be possible with just one mapping, with target:
Track = All by name with *
FX = By name with explicit name

However, it does not work. It works if I select just one track at a time with its position.

**Comment by helgoboss** [comment]
Not supposed to work right now. Using "Track: All by name" works for track targets only at the moment. I consider this a feature request then.

**Comment by vonglan** [comment]
Would be nice, but of course it can also be achieved by duplicating the mapping.

**Comment by vonglan** [comment]
Don't need this any more. I wrote a small JSFX to filter events. That is even more straightforward, than a "/dev/null" ReaLearn instance.

**Comment by helgoboss** [comment]
This actually works now in 2.13.0-pre.2 (called combinatorial explosion in the changelog). So I'll close it.
