### ISSUE TITLE
Bring back Action Targets on Reaper 5.X

### ISSUE THREAD

**Issue by jackmau** [helgoboss/realearn#44]
Hi @helgoboss,
I was surprised when I found that in the current version of realearn (and I suspect in any since 1.10) action can only be picked from Reaper 6.13. I am on reaper 5.99 and I make extensive use of SWS cycle actions, is there any chance of realearn supporting again actions in 5.99?

If not would I be able to load a project in 6.X create my action bindings and go back to 5.99 and find them there?

**Comment by helgoboss** [comment]
I think I won't integrate the dropdown at least. It was a bit hacky to get that right. But I could quite easily add a text field in which you can enter the command ID.

**Comment by jackmau** [comment]
that would be good, it's mostly for SWS action, other actions are still assignable by learn action, as spotted in #46

**Comment by helgoboss** [comment]
@jackmau Is this still relevant?

**Comment by jackmau** [comment]
@helgoboss It is, but not very high priority as I am using learn as mentioned in #46 which works just fine. I am not updating to Reaper 6 until Playtime 2 for sure ;)

**Comment by helgoboss** [comment]
I think this will not happen ;) Closing.
