### ISSUE TITLE
Midi Reset on Play

### ISSUE THREAD

**Issue by CLVMTT** [helgoboss/realearn#458]
Similar to the already solved issue #96 (NOTE OFF on play) it could be useful to remove the Reset on Play option (not selectable on reaper for a single MIDI device, but for all)

![immagine](https://user-images.githubusercontent.com/92969443/138398162-92e61a24-d5a5-442f-975f-14539fa3f79f.png)

**Comment by helgoboss** [comment]
Mmh, you are right. This is counter-productive with control-surface-like devices. This resets faders on play/stop which we don't want. I asked Justin if there's a way to prevent the reset for certain devices. Right now I don't know of any way, so the only workaround for now is to globally disable this flag.

**Comment by CLVMTT** [comment]
Not a big issue for me actually, maybe for someone could be a deal-breaker... Thanks for your reply

**Comment by helgoboss** [comment]
Good news, Justin maybe will make this option device-specific. I'll leave this issue open for giving updates on this and eventually update the controller setup documentation.

**Comment by helgoboss** [comment]
Even better news, Justin implemented it already, in the latest REAPER pre-release. This solves the issue. Now it just needs some docs on my side.

**Comment by helgoboss** [comment]
Now mentioned in user guide
