### ISSUE TITLE
Automation Touch State doesn't update motorized fader value when released

### ISSUE THREAD

**Issue by CLVMTT** [helgoboss/realearn#459]
When writing an automation in "Touch Mode", everything works fine, but when the fader is released (and it regularly returns to his previous position) the value of the automation to which it returns is not sent as feedback, so when the fader is touched a second time, it send the last value registered when it was released the first time, even if it's phisical position is on the new value.
This DOESN'T happen if you pause/stop between the first and the second automation

![immagine](https://user-images.githubusercontent.com/92969443/138431592-9e26c4ac-baaa-4b49-a710-61516da4fd95.png)

Thanks, don't know if it's a real bug or something wrong in the programming

**Comment by helgoboss** [comment]
Will be fixed in upcoming 2.10.4 (and 2.11.0-pre.12).
