### ISSUE TITLE
Repeatedly getting an error when trying to pick an Action as a Target (when clicking on the "pick" button)

### ISSUE THREAD

**Issue by chords-chords** [helgoboss/realearn#46]
95 % of the time ReaLearn throws an error when I click on the “pick” button. It also doesn’t proceed to open or change the action list as it does when it happens to work. It doesn’t matter if the action list is already open or not. When the error comes up, I can’t proceed with anything and have to restart Reaper (as advised in the text of the Error message). I’ve tried ignoring the error and tried to save the mappings set until that point as a preset but when I reloaded Reaper, they weren’t there.

This is what happens:
![ReaLearn action pick bug](https://user-images.githubusercontent.com/71832442/95664028-6380d000-0b44-11eb-830d-04b278b89eac.gif)

Also, here’s the error message:

Sorry, an error occurred in a REAPER plug-in. It seems that a crash has been prevented. Better save your project at this point, preferably as a new file. It's recommended to restart REAPER before using the plug-in again. 

Please report this error:

1. Copy the following error information.
2. Paste the error information into an email and send it via email to info@helgoboss.org, along with the RPP file, your REAPER.ini file and some instructions how to reproduce the issue.

Thank you for your support!

--- cut ---
Message: already mutably borrowed: BorrowError

   0:     0x7ffca03dcb6d - Extended
   1:     0x7ffca03dc229 - Extended
   2:     0x7ffca02ea801 - MAIN
   3:     0x7ffca03f0798 - Extended
   4:     0x7ffca03f02ef - Extended
   5:     0x7ffca0400d10 - rust_eh_personality
   6:     0x7ffca0400b63 - rust_eh_personality
   7:     0x7ffca018b725 - NSEEL_HOSTSTUB_EnterMutex
   8:        0x140825a3d - <unknown>
   9:        0x140343f34 - <unknown>
  10:        0x140365455 - <unknown>
  11:        0x140365353 - <unknown>
  12:        0x140770a51 - <unknown>
  13:        0x1405105f4 - <unknown>
  14:        0x1405103d1 - <unknown>
  15:        0x140510314 - <unknown>
  16:          0xa5c0271 - ReaperPluginEntry
  17:          0xa465ad9 - <unknown>
  18:          0xa4646cf - <unknown>
  19:          0xa507a23 - png_get_current_pass_number
  20:          0xa5b1bb9 - png_get_current_pass_number
  21:        0x1404209bf - <unknown>
  22:        0x14041dc8f - <unknown>
  23:        0x140541352 - <unknown>
  24:        0x1405412cc - <unknown>
  25:        0x14017282e - <unknown>
  26:        0x1401787e8 - <unknown>
  27:        0x140178565 - <unknown>
  28:     0x7ffca01df352 - DllMain
  29:     0x7ffca02bacb5 - MAIN
  30:     0x7ffca02ba287 - MAIN
  31:     0x7ffcd0d8802e - IsWindowInDestroy
  32:     0x7ffcd0d877f2 - IsWindowInDestroy
  33:     0x7ffcd0d876ff - IsWindowInDestroy
  34:     0x7ffcd0d85c7d - CallWindowProcW
  35:     0x7ffcd0d8528c - SendMessageW
  36:     0x7ffcd0d84ff8 - SendMessageW
  37:     0x7ffcbf366459 - ImageList_LoadImageW
  38:     0x7ffcbf39df0c - Ordinal342
  39:     0x7ffcd0d85c7d - CallWindowProcW
  40:     0x7ffcd0d85672 - DispatchMessageW
  41:        0x1403a50f5 - <unknown>
  42:        0x140864b01 - <unknown>
  43:     0x7ffcd09b7bd4 - BaseThreadInitThunk
  44:     0x7ffcd182ce51 - RtlUserThreadStart
--- cut ---

**Comment by hartmays** [comment]
I'm experiencing this problem also.  One interesting thing is that after it starts happening, it seems to persist even if you open a difference project or a different preset in Realearn.  It's definitely a showstopper trying to create mappings.

**Comment by chords-chords** [comment]
@hartmays, I realized later that it isn’t exactly a complete showstopper. Intuitively I thought the only way to assign an action as the target is to pick it from the list, by clicking on the pick button first, waiting for the action list to open and then selecting it from there. There’s another way however and so far it worked for me with no errors popping up. Here’s how you do it: You open the action list in Reaper the normal way (via Reaper’s own hotkey or menu). In Realearn you then click on the “Learn target” button. Then you **run the action** you want to assign **from the action list** and voila! It assigns the action as the target.

**Comment by jackmau** [comment]
well spotted @chords-chords , I was not aware of that, that would serve as a workaround for #44 , but unfortunately it doesn't support SWS cycle actions. I suppose with conditional actiaviton I should be able to replicate something similar...

**Comment by helgoboss** [comment]
Sorry for this annoying error, this thing was totally unusable. It didn't happen to me because I was running in debug mode.

Will be fixed in upcoming version.

**Comment by helgoboss** [comment]
Thanks for the report. Will be fixed in upcoming pre-release 1.12.0-pre1,
see https://github.com/helgoboss/realearn/issues/46 (your issue :)
