### ISSUE TITLE
OSC Send string message not working

### ISSUE THREAD

**Issue by jackmau** [helgoboss/realearn#467]
Hi @helgoboss,

Since #448 has been closed I was expecting OSC string feedback to be implemented now. However whenever I try to select a string argument, realearn seems to ignore string inputs in the `Value` field. `Trigger!` always yields a feedback of 100 (in string).

![image](https://user-images.githubusercontent.com/43683722/139691397-13d1a131-146a-49ca-8b06-dffab7a0e415.png)

Naturally I have tested my OSC setup and I ca nconfirm that float feedback, via send osc message/normal control feedback is working properly on my system. 

I am on windows 10, realearn 2.11-pre11 (I have had the same problem with 2.11-pre3) and Reaper 5.99/x64.

**Comment by helgoboss** [comment]
OSC string feedback is implemented, yes. However, "OSC: Send message" is not the same as OSC feedback, it's just a utility target to be able to send some OSC messages in response to incoming source messages, suitable for MIDI-to-OSC or OSC-to-OSC conversion.

If you want OSC string feedback, you must use the OSC source. Then you can choose textual feedback in the tuning section and use constant text plus expressions such as `{{ target.track.name }}` to build the text output of your liking.

**Comment by jackmau** [comment]
> If you want OSC string feedback, you must use the OSC source. Then you can choose textual feedback in the tuning section and use constant text plus expressions such as `{{ target.track.name }}` to build the text output of your liking.

thanks, this does work indeed. I think this should be explained a bit better in the manual, though.
