### ISSUE TITLE
Track Solo Function Improvement

### ISSUE THREAD

**Issue by ChocolateHawkins** [helgoboss/realearn#47]
As mentioned on the Cockos forum, I've found that when using the Realearn function to Solo the selected track, any of the tracks it sends to or are nested under do not solo. My assumption is this is an issue between "exclusive solo" and "solo". Exclusive Solo appears to carry any routing with it while regular Solo does not.

For example, I will have something like the following: 

_DRUM CONTAINER
-- DRUM BUS_ [Realearn here]
_-- DRUM FX BUS_

_FX CONTAINER
-- FX BUS
--- GLOBAL REVERB_ 

In this scenario, the _DRUM BUS_ and _DRUM FX BUS_ are nested in the _DRUM CONTAINER_ folder. The _FX CONTAINER_ folder holds an _FX BUS_ which holds a _GLOBAL REVERB_ 

My _DRUM BUS_ will send through the _DRUM CONTAINER_ to the _MASTER_. It will also send to the _DRUM FX BUS_ and the _GLOBAL REVERB_. 

If I use my mouse on the MCP and hit the Solo button on the _DRUM BUS_, it will solo the DRUM BUS and anything it sends to (as clicking on it appears to activate the solo in Exclusive Solo mode). 

If I map Realearn to the Solo of the track it sits on, it will solo just the track. If I have it nested in a folder or bus, no audio is passed to the _MASTER_. There is no option in the drop down in Realearn for Exclusive Solo. 

Having said all that, Exclusive Solo is not available from the Actions. So I'm not sure if that will be a hurdle.

**Comment by RobU23** [comment]
Hi, 

Just to add another voice to the 'change of solo behaviour' request.  As stated, ReaLearn solo currently does not respect routing. If I have a number of tracks bused to another track with master/parent disabled, soloing one of the bused tracks results in silence.   Using the individual numbered track solo option works, to a point, but if you move tracks around, the association is lost. 

Regards
Rob

**Comment by helgoboss** [comment]
I'll fix this for the next release.
