### ISSUE TITLE
Make array for "selected_track_indexes"

### ISSUE THREAD

**Issue by BryanChi** [helgoboss/realearn#470]
A quick recap of our conversation on Reaper forum:

> I know you can set it so that the 1st fader controls the 1st selected track, but is it possible to have 2nd fader controlling 2nd selected tracks volume and so on, even if the two tracks are not beside each other?
So for example:
cc1 -> adjust 1st selected tracks(say track 0) volume
cc2 -> adjust 2nd selected tracks(whichever track that's also selected) volume

> What you want is currently not possible but it wouldn't be hard to add it. In addition to "selected_track_index" (which resolves to the index of the first selected track) I could probably make available an array "selected_track_indexes" which you can access like "selected_track_indexes[0]" or "selected_track_indexes[i + 5]" ... Please create a feature request issue on GitHub if you are interested in this.

**Comment by helgoboss** [comment]
Available in upcoming pre-release 2.11.0-pre.15 or full release, let's see.

Lua example for using it:

```lua
{
    kind = "MainCompartment",
    value = {
        mappings = {
            {
                name = "1",
                source = {
                    kind = "Virtual",
                    id = "ch1/fader",
                },
                target = {
                    kind = "TrackVolume",
                    track = {
                        address = "Dynamic",
                        expression = "selected_track_indexes[0]",
                    },
                },
            },
            {
                name = "2",
                source = {
                    kind = "Virtual",
                    id = "ch2/fader",
                },
                target = {
                    kind = "TrackVolume",
                    track = {
                        address = "Dynamic",
                        expression = "selected_track_indexes[1]",
                    },
                },
            },
            {
                name = "3",
                source = {
                    kind = "Virtual",
                    id = "ch3/fader",
                },
                target = {
                    kind = "TrackVolume",
                    track = {
                        address = "Dynamic",
                        expression = "selected_track_indexes[2]",
                    },
                },
            },
        },
    },
}
```
