### ISSUE TITLE
Add "FX parameter: Set automation touch state" and "Send: Set automation touch state"

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#474]

**Comment by helgoboss** [comment]
FX parameter: TrackFX_EndParamEdit
Send: SetTrackSendUIVol and SetTrackSendUIPan with isend = 1.

**Comment by emkayg** [comment]
A very key feature for me! Would be a dream setup to have freely assignable parameter that I can automate (the primary use for controllers for me).

**Comment by cjewellstudios** [comment]
I would love this feature as well!

**Comment by Vagalum3** [comment]
Would be much appreciated :)

**Comment by helgoboss** [comment]
Working on it.
