### ISSUE TITLE
Add directory for unchecked 3rd-party presets in ReaLearn repository and add a link

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#475]
Because it turned out that checking and polishing 3rd-party presets takes too much time, so at the end they never appear, which is sad.

**Comment by vonglan** [comment]
What do you mean with 3rd-party presets? Would this affect my SY presets?

**Comment by helgoboss** [comment]
This is only about presets that users send to me as a contribution. I often don't find the necessary time to do a quality check and to publish them on ReaPack. Which is a pity. Therefore I'm planning to add the extra folders `resources/controllers/unsorted` and `resources/main-presets/unsorted` where I can put these neglected presets. They won't appear on ReaPack but users can download them directly from GitHub.

So no, it doesn't affect your SY presets because you taking care of publishing yourself.

**Comment by helgoboss** [comment]
https://github.com/helgoboss/realearn/tree/master/resources/controllers/unofficial and https://github.com/helgoboss/realearn/tree/master/resources/main-presets/unofficial
