### ISSUE TITLE
Provide variable for "source value" in <Dynamic> track selection

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#489]
In combination with target "Track: select/unselect" and "Exclusive within folder (on only)", it would be nice to be able to use the source value in the formula for the track number.

(This only makes sense if the action does not need the source value, as in this case.)

**Comment by helgoboss** [comment]
What's your particular use case?

**Comment by vonglan** [comment]
The "inner" use case is as described above.
The "outer" use case is to control Super8 using ReaLearn (and a small JSFX, that converts from "trigger parameters" to the note numbers that Super8 expects).
Using a knob or a button used as iterator, I want to select one of 4 source tracks, via one Virtual target/source that has the track number (0-3) in it.

I solved it with 4 main mappings, one for each track, so this is more a suggestion than a requirement. But I thought that it would be nice to able to use the source value (track number) in the <Dynamic> formula, then only one mapping would be needed.

**Comment by helgoboss** [comment]
Please see issue #469 why this will not be implemented and the proposed alternative (ReaLearn Script).

**Comment by helgoboss** [comment]
I will close this for now because ReaLearn Script provides a scalable alternative. If in future it turns out that there are more and more users that don't want to go the scripting way but still want to save mouse clicks, I might give it another shot. But currently, there are so many more important things to work on.

**Comment by vonglan** [comment]
Fine with me. Thanks for all your work!
