### ISSUE TITLE
Lua Import Error

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#495]
I get an error 
`syntax error: [string "Import"]:1: syntax error near '<\194>'`
from ReaLearn when I try the following:

1. copy 

```
mappings = {}

for i=1,10 do
    mapping = {
        name = "Volume Track " .. i,
        source = {
            kind = "MidiControlChangeValue",
            channel = i - 1,
            controller_number = 7,
            fourteen_bit = false,
        },
        target = {
            kind = "TrackVolume",
            track = {
                address = "ByIndex",
                index = i - 1,
            },
        },
    }
    mappings[i] = mapping
end

return mappings

```
into buffer

2. in an empty, initial ReaLearn instance, call "Paste from Lua (replace all in group)"

Maybe something to do with OSX? Or is it not intended to paste multiple mappings via Lua like this?

**Comment by helgoboss** [comment]
This works. Have a look at the return statement at the bottom (this tells ReaLearn how the content of the clipboard should be interpreted). BTW, if possible, use Discussions or REAPER forum if it's rather a question than a bug report.

```lua
mappings = {}

for i=1,10 do
    mapping = {
        name = "Volume Track " .. i,
        source = {
            kind = "MidiControlChangeValue",
            channel = i - 1,
            controller_number = 7,
            fourteen_bit = false,
        },
        target = {
            kind = "TrackVolume",
            track = {
                address = "ByIndex",
                index = i - 1,
            },
        },
    }
    mappings[i] = mapping
end

return {
    kind = "Mappings",
    value = mappings
}
```

**Comment by vonglan** [comment]
Thanks!
It works fine when I start with right-click on a dummy mapping Advanced / Paster form Lua (insert below).

(When I try instead, right-click on the empty area to the right of "Mapping group", Advanced / Paste from Lua (replace all in group), nothing happens.)
