### ISSUE TITLE
"Navigate between presets" target issue

### ISSUE THREAD

**Issue by alfonso73** [helgoboss/realearn#498]
Hi, when the input controller goes to zero the switching between presets does not work anymore and the preset remain fixed to the "Reset to factory default" entry in the preset list of the target fx. This is the first entry in the menu. The issue is somewhat solved if the target Min level is set to 1 instead of 0.

**Comment by helgoboss** [comment]
@alfonso73 I cannot reproduce this. Could you post a minimal test project?

**Comment by alfonso73** [comment]
Hi checked again. Everything seems to work for Reaper stock plugins. But the issue is definitely present for every VST3 i tried.

**Comment by helgoboss** [comment]
Oh, so maybe it's a VST3 issue. I will look into it.

**Comment by helgoboss** [comment]
I tried with ValhallaRoom VSTi and the behavior is indeed strange. As soon as one switches to "No preset", it seems to detect a parameter count of 0, which makes it stop working.

**Comment by alfonso73** [comment]
I have exaclty the same behavior.

**Comment by helgoboss** [comment]
Looking into it now. Checking back with Justin if this is a REAPER API bug.
