### ISSUE TITLE
Option to log virtual target values (like incoming/outgoing MIDI)

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#501]
for the Controller Mappings that are triggered, as an optional debug help.

Also, logging which mapping was triggered (maybe separate for Control and Main Mappings), would be useful.

**Comment by helgoboss** [comment]
I'm implementing logging of virtual target invocations (in the controller compartment), including the info if there's a match in the main compartment or not.

To find out which mappings are triggered, there's already a better way: "Filter source".
