### ISSUE TITLE
realearn failed to scan / plugin not loading

### ISSUE THREAD

**Issue by JRSV** [helgoboss/realearn#503]
Hello,

I have downloaded realearn and installed it in all ways I can possibly think of (manually and via reapack).  ReaPack installs and says to reboot reaper, but reaper fails to load the plug in every single try. I have also cleared the cache and rescanned for plugins.

how can I troubleshoot what is going wrong?

I am running it on latest reaper (6.42) in an AVL-MX machine (debian 10)
and I am trying to install realearn 2.10.4.

any advice?

**Comment by helgoboss** [comment]
Which processor architecture? Native or Wine?

**Comment by JRSV** [comment]
native... 
I have it running perfectly in 2 machines already (those are ubuntustudio 20.04)

**Comment by helgoboss** [comment]
And processor architecture?

**Comment by JRSV** [comment]
`[code]
Snapshot created on: 20210617_0214
System:    Host: <filter> Kernel: 5.9.1-rt20avl1 x86_64 bits: 64 compiler: N/A 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.9.1-rt20avl1 
           root=UUID=<filter> ro quiet threadirqs noresume 
           efi=runtime 
           Desktop: Openbox 3.6.1 info: xfce4-panel dm: LightDM 1.26.0 Distro: AVL-MXE 
           base: Debian GNU/Linux 10 (buster) 
Machine:   Type: Laptop System: Dell product: Latitude E6430 v: 01 serial: <filter> Chassis: 
           type: 9 serial: <filter> 
           Mobo: Dell model: 0CPWYR v: A00 serial: <filter> UEFI: Dell v: A07 date: 10/08/2012 
Battery:   ID-1: BAT0 charge: 49.4 Wh condition: 51.5/62.2 Wh (83%) volts: 11.9/11.1 
           model: Sanyo DELL NH6K92A type: Li-ion serial: <filter> status: Discharging 
CPU:       Topology: Dual Core model: Intel Core i5-3210M bits: 64 type: MT MCP arch: Ivy Bridge 
           family: 6 model-id: 3A (58) stepping: 9 microcode: 21 L2 cache: 3072 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19935 
           Speed: 1834 MHz min/max: 1200/3100 MHz Core speeds (MHz): 1: 1687 2: 2208 3: 2515 
           4: 1365 
           Vulnerabilities: Type: itlb_multihit status: KVM: VMX disabled 
           Type: l1tf mitigation: PTE Inversion; VMX: conditional cache flushes, SMT vulnerable 
           Type: mds mitigation: Clear CPU buffers; SMT vulnerable 
           Type: meltdown mitigation: PTI 
           Type: spec_store_bypass 
           mitigation: Speculative Store Bypass disabled via prctl and seccomp 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 mitigation: Full generic retpoline, IBPB: conditional, IBRS_FW, 
           STIBP: conditional, RSB filling 
           Type: srbds status: Vulnerable: No microcode 
           Type: tsx_async_abort status: Not affected 
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: Dell driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0166 
           Display: x11 server: X.Org 1.20.10 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 20.3.4 
           compat-v: 3.0 direct render: Yes 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1e20 
           Sound Server: ALSA v: k5.9.1-rt20avl1 
Network:   Device-1: Intel 82579LM Gigabit Network vendor: Dell driver: e1000e v: kernel 
           port: f080 bus ID: 00:19.0 chip ID: 8086:1502 
           IF: eth0 state: down mac: <filter> 
           Device-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi v: kernel 
           port: f040 bus ID: 02:00.0 chip ID: 8086:0082 
           IF: wlan0 state: up mac: <filter> 
Drives:    Local Storage: total: 447.13 GiB used: 354.57 GiB (79.3%) 
           ID-1: /dev/sda vendor: Kingston model: SA400S37480G size: 447.13 GiB block size: 
           physical: 512 B logical: 512 B speed: 6.0 Gb/s serial: <filter> rev: 61K1 scheme: GPT 
RAID:      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 
           port: f060 bus ID: 00:1f.2 chip ID: 8086.282a rev: 04 
Partition: ID-1: / raw size: 61.77 GiB size: 60.55 GiB (98.02%) used: 27.12 GiB (44.8%) fs: ext4 
           dev: /dev/sda5 
           ID-2: /home raw size: 367.77 GiB size: 361.00 GiB (98.16%) used: 327.43 GiB (90.7%) 
           fs: ext4 dev: /dev/sda3 
           ID-3: swap-1 size: 16.00 GiB used: 256 KiB (0.0%) fs: swap 
           swappiness: 10 (default 60) cache pressure: 100 (default) dev: /dev/sda4 
Sensors:   System Temperatures: cpu: 45.0 C mobo: 33.0 C sodimm: 32.0 C 
           Fan Speeds (RPM): cpu: 2667 
Repos:     Active apt repos in: /etc/apt/sources.list 
           1: deb http://liquorix.net/debian/ buster main
           2: deb http://www.bandshed.net/kernels/apt/ buster main
           3: deb [trusted=yes] https://cinelerra-gg.org/download/pkgs/debian10/ buster main
           4: deb https://dl.winehq.org/wine-builds/debian/ buster main
           No active apt repos in: /etc/apt/sources.list.d/christian-boxdoerfer-ubuntu-fsearch-stable-jammy.list 
           No active apt repos in: /etc/apt/sources.list.d/connectify.list 
           Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list 
           1: deb http://deb.debian.org/debian/ buster-updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/debian.list 
           1: deb http://deb.debian.org/debian/ buster main contrib non-free
           2: deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free
           3: deb-src http://deb.debian.org/debian/ buster main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/dropbox.list 
           1: deb [arch=i386,amd64] http://linux.dropbox.com/debian buster main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/kxstudio-debian-ppas.list 
           1: deb http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu/ bionic main
           2: deb http://ppa.launchpad.net/kxstudio-debian/music/ubuntu/ bionic main
           3: deb http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu/ bionic main
           4: deb http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/ bionic main
           5: deb http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu/ bionic main
           Active apt repos in: /etc/apt/sources.list.d/kxstudio-external.list 
           1: deb [arch=amd64,i386] https://kx.studio/repo/ stable free
           2: deb [arch=amd64,i386] https://kx.studio/repo/ gcc5 free
           Active apt repos in: /etc/apt/sources.list.d/megasync.list 
           1: deb https://mega.nz/linux/MEGAsync/Debian_10.0/ ./
           No active apt repos in: /etc/apt/sources.list.d/mixxx-ubuntu-mixxx-impish.list 
           Active apt repos in: /etc/apt/sources.list.d/mx.list 
           1: deb http://mirror.cedia.org.ec/mx-workspace/mx/repo/ buster main non-free
           2: deb http://mirror.cedia.org.ec/mx-workspace/mx/repo/ buster ahs
           Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list 
           1: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
           Active apt repos in: /etc/apt/sources.list.d/skype-stable.list 
           1: deb [arch=amd64] https://repo.skype.com/deb stable main
           Active apt repos in: /etc/apt/sources.list.d/sonobus.list 
           1: deb http://pkg.sonobus.net/apt stable main
           No active apt repos in: /etc/apt/sources.list.d/spotify.list 
           Active apt repos in: /etc/apt/sources.list.d/teams.list 
           1: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
           No active apt repos in: /etc/apt/sources.list.d/various.list 
Info:      Processes: 288 Uptime: 3h 59m Memory: 7.65 GiB used: 3.63 GiB (47.4%) Init: SysVinit 
           v: 2.96 runlevel: 5 default: 5 Compilers: gcc: 8.3.0 alt: 8 Shell: quick-system-in 
           running in: quick-system-in inxi: 3.0.36 
[/code]
`

**Comment by helgoboss** [comment]
Mmh okay. This kind of scanning issue is hard to troubleshoot. I also don't have a good recipe for that. Usually what I do is running REAPER with a debugger and putting some breakpoints there and going they get hit and then see where's the issue. You could also use the REAPER command line argument that writes plugin scanning logs to a file.

**Comment by JRSV** [comment]
" You could also use the REAPER command line argument that writes plugin scanning logs to a file."
how would I do that? I run repaer in the terminal but no log generated when scanned the vsts

**Comment by helgoboss** [comment]
I think you can run REAPER with -h to see its command line options. At least on Windows it outputs something related to logging. Can't try these days, I'm AFK.

**Comment by JRSV** [comment]
ok, so this is what I get form that command line tool, but I don't find anything mentioning the failed plugins.

REAPER 6.42/linux-x86_64 log file writing begin (build Nov 16 2021 19:26:45; current time Thu 16 Dec 2021 10:37:40 AM -05)
exe = /opt/REAPER/reaper, ini = /home/jrsv/.config/REAPER/reaper.ini
Thu 16 Dec 2021 10:37:40 AM -05 [0]: splash window created
Thu 16 Dec 2021 10:37:42 AM -05 [2020]: Initializing ReWire
Thu 16 Dec 2021 10:37:42 AM -05 [2]: Initializing...
Thu 16 Dec 2021 10:37:42 AM -05 [0]: Loading Configuration...
Thu 16 Dec 2021 10:37:43 AM -05 [218]: Initializing Registration Info...
Thu 16 Dec 2021 10:37:43 AM -05 [12]: Scanning VST plug-ins...
Thu 16 Dec 2021 10:37:43 AM -05 [0]: Scanning LV2 plug-ins...
Thu 16 Dec 2021 10:37:43 AM -05 [908]: Loading élastique Pro...
Thu 16 Dec 2021 10:37:43 AM -05 [1]: Loading élastique 2 Pro...
Thu 16 Dec 2021 10:37:43 AM -05 [0]: Loading élastique 3 Pro...
Thu 16 Dec 2021 10:37:43 AM -05 [2]: Loading SoundTouch...
Thu 16 Dec 2021 10:37:43 AM -05 [0]: Loading JS...
Thu 16 Dec 2021 10:37:43 AM -05 [4]: Scanning MIDI hardware...
Thu 16 Dec 2021 10:37:44 AM -05 [56]: Initializing Application...
Thu 16 Dec 2021 10:37:44 AM -05 [1]: Initializing Main Window...
Thu 16 Dec 2021 10:37:44 AM -05 [1]: Loading native plug-ins...
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Loading plug-in: reaper_mp3dec.so
Thu 16 Dec 2021 10:37:44 AM -05 [1]: Loading plug-in: reaper_flac.so
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Loading plug-in: reaper_opus.so
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Loading plug-in: reaper_explorer.so
Thu 16 Dec 2021 10:37:44 AM -05 [1]: Loading plug-in: reaper_cd.so
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Loading plug-in: reaper_ogg.so
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Loading plug-in: reaper_wavpack.so
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Loading plug-in: reaper_video.so
Thu 16 Dec 2021 10:37:44 AM -05 [81]: Loading plug-in: reaper_csurf.so
Thu 16 Dec 2021 10:37:44 AM -05 [2]: Loading plug-in: reaper_ddp.so
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Loading plug-in: reaper_wave.so
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Loading plug-in: reaper_midi.so
Thu 16 Dec 2021 10:37:44 AM -05 [1]: Initializing Main Window...
Thu 16 Dec 2021 10:37:44 AM -05 [15]: Initializing Control Surfaces...
Thu 16 Dec 2021 10:37:44 AM -05 [3]: Initializing Main Window...
Thu 16 Dec 2021 10:37:44 AM -05 [87]: Loading AG-DELL-rescue.RPP...
Thu 16 Dec 2021 10:37:44 AM -05 [53]: Loading project...
Thu 16 Dec 2021 10:37:44 AM -05 [3]: Project: loading effect: LV2: Calf X-Over 4 Band (Calf Studio Gear)
Thu 16 Dec 2021 10:37:44 AM -05 [6]: Project: loaded: LV2: Calf X-Over 4 Band (Calf Studio Gear)
Thu 16 Dec 2021 10:37:44 AM -05 [1]: Project: loading effect: LV2: Calf Limiter (Calf Studio Gear)
Thu 16 Dec 2021 10:37:44 AM -05 [2]: Project: loaded: LV2: Calf Limiter (Calf Studio Gear)
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Project: loading effect: LV2: Calf Limiter (Calf Studio Gear)
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Project: loaded: LV2: Calf Limiter (Calf Studio Gear)
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Project: loading effect: LV2: MDA Limiter
Thu 16 Dec 2021 10:37:44 AM -05 [2]: Project: loaded: LV2: MDA Limiter
Thu 16 Dec 2021 10:37:44 AM -05 [1]: Project: loading effect: LV2i: Surge (Surge Synth Team)
Thu 16 Dec 2021 10:37:44 AM -05 [55]: Project: loaded: LV2i: Surge (Surge Synth Team)
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Project: loading effect: LV2i: Helm (Matt Tytel)
Thu 16 Dec 2021 10:37:44 AM -05 [58]: Project: loaded: LV2i: Helm (Matt Tytel)
Thu 16 Dec 2021 10:37:44 AM -05 [0]: Project: loading effect: LV2i: ZynAddSubFX (ZynAddSubFX Team)
Thu 16 Dec 2021 10:37:44 AM -05 [132]: Project: loaded: LV2i: ZynAddSubFX (ZynAddSubFX Team)
Thu 16 Dec 2021 10:37:44 AM -05 [3]: Project: loading complete
Thu 16 Dec 2021 10:37:44 AM -05 [7]: (empty)
Thu 16 Dec 2021 10:37:45 AM -05 [915]: splash window destroyed

It seems it only creates logs for some specific in house plugins at startup and the ones loaded in the file. I tried copying realearn to /opt/ folder with the native plugins from reaper to see if it generated any logs but no luck.

**Comment by helgoboss** [comment]
There should be a line mentioning ReaLearn in the vstplugins64.ini file in the REAPER resource dir (or similar name). You can delete it and REAPER will rescan.

**Comment by helgoboss** [comment]
@JRSV Any new insights on this one?

**Comment by JRSV** [comment]
sorry for the delay, just had time now.

this is what I have (I marked it in bold, realearn is there):

[vstcache]
reacast.vst.so=0014252EDCF1D701,1919246691,ReaCast (Cockos)
reacomp.vst.so=0014252EDCF1D701,1919247213,ReaComp (Cockos)
reacontrolmidi.vst.so=0014252EDCF1D701,1919118692,ReaControlMIDI (Cockos)
readelay.vst.so=0014252EDCF1D701,1919247468,ReaDelay (Cockos)
reaeq.vst.so=0014252EDCF1D701,1919247729,ReaEQ (Cockos)
reafir.vst.so=0014252EDCF1D701,1919247986,ReaFir (FFT EQ+Dynamics Processor) (Cockos)
reagate.vst.so=0014252EDCF1D701,1919248244,ReaGate (Cockos)
reainsert.vst.so=0014252EDCF1D701,1919250281,ReaInsert (Cockos)
**ReaLearn_x64.so=8089A90DDDF1D701**
realimit.vst.so=0014252EDCF1D701,1919708532,ReaLimit (Cockos)
reaninjam.vst.so=0014252EDCF1D701,1919250026,ReaNINJAM (Cockos)
reapitch.vst.so=0014252EDCF1D701,1919250531,ReaPitch (Cockos)
reasamplomatic.vst.so=0014252EDCF1D701,1920167789,ReaSamplOmatic5000 (Cockos)!!!VSTi
reastream.vst.so=0014252EDCF1D701,1920169074,ReaStream (Cockos) (8ch)
reasurround.vst.so=0014252EDCF1D701,1920168548,ReaSurround (Cockos)
reasurround2.vst.so=0014252EDCF1D701,1920168498,ReaSurroundPan (Cockos)
reasyndr.vst.so=0014252EDCF1D701,1919251300,ReaSynDr (Cockos) (4 out)!!!VSTi
reasynth.vst.so=0014252EDCF1D701,1919251321,ReaSynth (Cockos)!!!VSTi
reatune.vst.so=0014252EDCF1D701,1919251566,ReaTune (Cockos)
reaverb.vst.so=0014252EDCF1D701,1919252066,ReaVerb (Cockos)
reaverbate.vst.so=0014252EDCF1D701,1920361016,ReaVerbate (Cockos)
reavocode.vst.so=0014252EDCF1D701,1919252068,ReaVocode (Cockos)
reavoice.vst.so=0014252EDCF1D701,1919252067,ReaVoice (Cockos)
reaxcomp.vst.so=0014252EDCF1D701,1919252579,ReaXcomp (Cockos)
Stochas.vst3=00B67882D248D701,1377263251,Stochas (Surge Synth Team)!!!VSTi
tonespace.so=009411FC3CE5CB01

**Comment by helgoboss** [comment]
If you delete that line and restart REAPER with log file writing on, REAPER should rescan and maybe it will print some reason why ReaLearn couldn't be loaded. Or maybe not, it's unfortunately hard to troubleshoot.

**Comment by JRSV** [comment]
that is what I did. :(
annoying, I can see reaper scan it, but it just wont load it, which is a shame because the plugin is fantastic

**Comment by helgoboss** [comment]
I'll leave that ticket as a marker to do two things:

- Test ReaLearn on Debian (because it sounds like you have this error with Debian only, not with Ubuntu)
- Try to research and improve error logging on initial scan

I can't give this too much priority now because other things are in the pipeline already. Let's see.

**Comment by JRSV** [comment]
Thanks @helgoboss

**Comment by helgoboss** [comment]
Ok, I tested latest REAPER + latest ReaLearn on a Debian VM and it works. Mmh. I don't know what to do about this one.

**Comment by helgoboss** [comment]
@JRSV Justin recommends to check if ReaLearn appears in prefs/vst as a failed plug-in when clicking the rescan button? I think we already made sure that it does. So, if it appears there, do this:

1. Re-run REAPER from the terminal.
2. Select ReaLearn in above mentioned failed plug-in list.
3. Check what it prints to the terminal and send that to me.

**Comment by helgoboss** [comment]
Oh no. You don't happen to have this system as a kind of VM, do you? Probably not.

Alternative: Are you a bit familiar with programming? You could actually build ReaLearn yourself (that part is pretty easy) and use debugging to find out what's wrong (that part is a bit less easy but I could help you with it).

**Comment by JRSV** [comment]
No, not a VM
lets hold on that idea, I am first going to upgrade my AVlinux - MX (debian 10) to the latest (debian 11) and see if that fixes this problem. I have it on my agenda for this week. Will get back to you then.

I am a bit familiar with programming, so that is also an option, but lets go through that bridge when it really comes to it.

cheers

**Comment by helgoboss** [comment]
Hey @JRSV, still having this issue? I know something that you can try to at least get a small clue what the error could be.

I suspect that REAPER can't load ReaLearn in your case because a dependency is missing on your particular Linux installation (a shared library or just a symbol in a shared library). For some reason, REAPER doesn't report details about such errors, it just seems to swallow them (at least on macOS I just made this experience). However, we can try to load the ReaLearn SO file outside of REAPER and see what's the problem. So if you still get this error, please do the following:

**Comment by JRSV** [comment]
Dear @helgoboss 

I now finally have updated my OS (just last week). and the plugin loads now in reaper, I havent had a chance to test it, but this looks much more promising than before. I will close this issue, and let you know if it works when I can properly test it.

**Comment by helgoboss** [comment]
Thanks @JRSV. I asked another user in the REAPER forums who had the same issue and he already tried this on his system (https://forum.cockos.com/showpost.php?p=2615278&postcount=13). Now the cause is clear. I'll reopen this and see if we can do something about it or not.

**Comment by helgoboss** [comment]
This is the cause, at least on the system of akademie:

`/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./realearn.so)mint@mint /tmp/realearn-test`

**Comment by JRSV** [comment]
@helgoboss 

yes, I think that:
 /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29'

might indeed be the cause, Debian 10 had this outdated, Debian 11 has it updated, so I would also think that is the issue

**Comment by helgoboss** [comment]
Some things to look into (not enough knowledge about glibc stuff at the moment):

- Quick search shows that it could help to build against an older glibc version (https://github.com/rust-lang/rust/issues/57497), e.g. within a container. We already use containers for cross compilation to arm targets, maybe it makes sense for x64 as well.
- Quick search shows that targeting musl could be interesting as well (https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html).
- It's not necessarily the Rust standard library which requires such a high glibc version, it could be any of the dependencies. Maybe good to find out which one.

**Comment by lion-artiste** [comment]
Hey, thank you, this helped, it's working now !
For the record, this was the output of my test program, as described in the thread above : 

libxdo.so.3: cannot open shared object file: No such file or directory

After googling this, I installed the missing library on my Ubuntu Studio with this command that I found online : 

sudo apt-get install -y libxdo-dev

I restarted my shell, and the test program had no more errors. And the plugin scanned correctly in Reaper !

Thank you very much, hope this helps.

**Comment by helgoboss** [comment]
Oh right, libxdo-dev! I remember someone mentioned this in the past. I need to document that somehow. Will do it.

I don't think this will fix the glibc error mentioned in this ticket, so it's more related to your other ticket, #797.

**Comment by helgoboss** [comment]
Note to self: Try linking libc statically and check negative side effects.

**Comment by JRSV** [comment]
hello @helgoboss ,

today for some strange reason I couldn't load realearn in the middle of a seminar which I wanted to showcase it... such a shame... anyway it is strange because after updating my OS to debian 11 [as in this response](https://github.com/helgoboss/realearn/issues/503#issuecomment-1321191504)  the problem stopped. 

So I compiled and ran the ./test program with the prompt returning:
 $ ./test
Test
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./realearn.so)

I also checked my version and it is 

ldd --version
ldd (Debian GLIBC 2.31-13+deb11u5) 2.31

so I don't know why was I able to find it when I update the OS, I suspect that it maybe has to do to updates compiled against your version of glibc? How is that container idea going? would realearn work if I compile it against my system?

**Comment by helgoboss** [comment]
Hi. I feel you, this is becoming a problem. I just read this: https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html

So compiling it on your system should indeed make it work. But of course I should fix this on my side, probably by compiling it within a container. Will look into it.

**Comment by helgoboss** [comment]
Let's continue discussing the latest Linux scan issues here: https://github.com/helgoboss/realearn/issues/829
