### ISSUE TITLE
Crashing with new pre

### ISSUE THREAD

**Issue by arthurmcarthur1** [helgoboss/realearn#515]
Hi Helgo, I'm having intermittent crashes on the latest pre. REAPER occasionally quits to desktop (I haven't nailed down when it happens), looking at the Event Viewer I can see 3 events related to the crash:

**1)**

The description for Event ID 1 from source NVIDIA OpenGL Driver cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

The GPU has been disconnected and this application may become unresponsive.

Error code: 10
 (pid=21736 tid=22592 reaper.exe 64bit)

Visit http://www.nvidia.com/page/support.html for more information.

The message resource is present but the message was not found in the message table

**2)**

Faulting application name: reaper.exe, version: 65.181.199.252, time stamp: 0x61cf7a27
Faulting module name: ReaLearn-x64.dll, version: 0.0.0.0, time stamp: 0x61ccfff8
Exception code: 0xc000001d
Fault offset: 0x0000000000abe6ec
Faulting process id: 0x54e8
Faulting application start time: 0x01d80177c259225e
Faulting application path: C:\Program Files\REAPER (x64)\reaper.exe
Faulting module path: C:\Users\redbu\AppData\Roaming\REAPER\UserPlugins\FX\ReaLearn-x64.dll
Report Id: 3433a400-9d96-402e-859a-0921469979d6
Faulting package full name: 
Faulting package-relative application ID: 

**3)**

Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program REAPER because of this error.

Program: REAPER
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0

**Comment by helgoboss** [comment]
@arthurmcarthur1 Thanks for the report. If you find out more about this error, that would be great. I think it's hopeless unless I can recreate it somehow.

**Comment by arthurmcarthur1** [comment]
I’ll stay on it and see if I can recreate

**Comment by helgoboss** [comment]
Closing. This pre is very old now.
