### ISSUE TITLE
"Save" of Controller Preset does not grey-out the "Save" button

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#516]
in 12.0-pre.2
[Temp VProm 2022 01 04.RPP.zip](https://github.com/helgoboss/realearn/files/7810372/Temp.VProm.2022.01.04.RPP.zip)

**Comment by helgoboss** [comment]
I could reproduce this with pre.2 but it's gone with pre.4. While testing this, I realized that the save button isn't greyed out for non-existent presets (I don't have your presets), so I fixed this instead :)
