### ISSUE TITLE
Lua import of poll_for_feedback not working

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#517]
- When I import from Lua, with no mention of poll_for_feedback, the mapping exports as poll_for_feedback = false
- When I set „poll for feedback“ via the GUI, the mapping exports without a mention of poll_for_feedback
- When I set poll for feedback=true in Lua, then import this, the "pol for feedback" in the GUI is still unticked

rc.4

By the way:
Why are some defaults (e.g. step_size_interval, step_factor_interval) part of the Lua Export?

**Comment by vonglan** [comment]
Also, the Import of glue /            absolute_mode = "ToggleButton",
does not work.

**Comment by helgoboss** [comment]
> * When I import from Lua, with no mention of poll_for_feedback, the mapping exports as poll_for_feedback = false
> * When I set „poll for feedback“ via the GUI, the mapping exports without a mention of poll_for_feedback
> * When I set poll for feedback=true in Lua, then import this, the "pol for feedback" in the GUI is still unticked
> 
> rc.4
> 

Thanks, will look into it in a few days.

> By the way: Why are some defaults (e.g. step_size_interval, step_factor_interval) part of the Lua Export?

They are not the defaults for Lua, just for the GUI. Because I don't like this 1-to-5 default, at least for programming, which is supposed to be precise and where defaults usually are something like 0 or 1. It sounds too arbitrary.

**Comment by helgoboss** [comment]
> * When I import from Lua, with no mention of poll_for_feedback, the mapping exports as poll_for_feedback = false
> * When I set „poll for feedback“ via the GUI, the mapping exports without a mention of poll_for_feedback
> * When I set poll for feedback=true in Lua, then import this, the "pol for feedback" in the GUI is still unticked

Good catch. This was a missing assignment. Fixing.
