### ISSUE TITLE
X32 OSC

### ISSUE THREAD

**Issue by rwallingford** [helgoboss/realearn#518]
The X series of Behringer mixers (such as X32) will not send any OSC messages to ReaLearn, until the X32 receives an "/xremote" message from ReaLearn first.
Also, the X32 must receive the "/remote" message every 9 seconds or less in from ReaLearn so that the X32 wont stop sending OSC messages. 

Basically, Realearn sending the "/xremote" is telling the X32 "I am subscribing to you for 10 seconds".

To support the X32, Realearn must be able to send 'xremote" every 9 seconds.

**Comment by helgoboss** [comment]
Hi, good to know! I will add a possibility then to send an arbitrary OSC message regularly.

**Comment by rwallingford** [comment]
Thanks,

Without this capability, The X32 series, will not function with ReaLearn.

**Comment by helgoboss** [comment]
ETA: Now ;)

ReaLearn v1.13.0-pre.1 will feature a new source called "Timer" (category "REAPER") that fires every n milliseconds. When you map this to the "OSC: Send message" target, you can regularly send relatively arbitrary OSC messages.

**Comment by rwallingford** [comment]
ReaLearn v2.13.0-pre.1  does not show up when I goto extentions->reapeack->browse, then right click on realearn, to look at the versions available.

2.12.0 is the highest version number available.

I did synchronize Reapack first.

How am I able to 2.13.0-pre.1 ?

**Comment by helgoboss** [comment]
You can't, it's not released yet. Wait 2 hours or so.

**Comment by helgoboss** [comment]
Now available.

**Comment by rwallingford** [comment]
Thanks @helgoboss

WIll try it out his weekend and let you know my findings.
