### ISSUE TITLE
 OSC → MIDI conversion with FX output

### ISSUE THREAD

**Issue by jackmau** [helgoboss/realearn#526]
Hi @helgoboss,

As usual realearn evolves much more quickly than I am able to keep pace with. One thing that is not clear to me, at the moment, is how to use realearn as an  OSC → MIDI converter. My aim is to convert OSC messages to midi so they can be recorded in playtime and then feed to another realearn instance.  Reading the documentation, I found that MIDI: Send Message Target on <FX output> only works if control input is set to <FX input>, but that is not possible for OSC sources (if I am not mistaken). My current workaround is to load a (bunch of) reacontrolmidi to be used as a target to generate midi messages, but this is not a particularily pretty and easy to manage solution. Is there any particular reason OSC controllers cannot generate MIDI to FX output? Maybe there is a better way to manage  OSC → MIDI I am not aware of...

**Comment by helgoboss** [comment]
That question came up recently in the forum. https://forum.cockos.com/showpost.php?p=2521176&postcount=1967

I can consider this issue as an FR then.

**Comment by helgoboss** [comment]
Sounds good. You can contribute to the adoc instrument (preferably via fork and pull request).

BTW, I fear you will have to rethink your setup soon ;) Playtime 2 [is in the making](https://forum.cockos.com/showthread.php?t=262395). It will be much more integrated with ReaLearn by itself already.

**Comment by jackmau** [comment]
> Playtime 2 [is in the making](https://forum.cockos.com/showthread.php?t=262395)

+9000 
I have been waitingfor a long time for it. Where can I write my wishlist of request for playtime 2? 😏 

> preferably via fork and pull request

that was my idea (also github is smartl enough not to allow me to freestyle on your main)

**Comment by helgoboss** [comment]
The linked forum thread is the best place for features wishes (although I will definitely concentrate on the very basics for the first release).
