### ISSUE TITLE
UI blacked out on Reaper 6.49 and 6.48

### ISSUE THREAD

**Issue by monocent** [helgoboss/realearn#535]
Updated to Reaper 6.49, Realearn 2.11.1 UI displays all black as in the attached image. Rolled back to 6.48, same issue. Went back to 6.47 where Realearn is displaying properly. Tried updating to Realearn 1-12-0 pre4, same results. I'm running 64bit Universal Reaper in all cases on Big Sur 11.6.4 with a 2018 mac mini.

I love Realearn by the way. So thankful for this project! 

![Screen Shot 2022-02-24 at 8 52 59 PM](https://user-images.githubusercontent.com/100394791/155644956-55ac34d5-e055-4565-8393-8d44ce922237.png)

**Comment by vonglan** [comment]
Same here, after upgrade from Reaper 6.46 to 6.51.
Realearn 1-12-0 pre4
64bit Universal Reaper on Big Sur 11.6 with a 2020 M1 MBP.

**Comment by helgoboss** [comment]
Looking into it.

**Comment by helgoboss** [comment]
Will be fixed in upcoming 1.12.0 or REAPER v6.52+ (fixed both on REAPER side and ReaLearn side).

**Comment by monocent** [comment]
Thank you helgoboss
