### ISSUE TITLE
How to build realearn?

### ISSUE THREAD

**Issue by muziker** [helgoboss/realearn#538]
After checking out tag v2.11.1, running cargo build gives:
> failed to run custom build command for 'core-error v0.0.0'
> thread 'main' panicked at 'Rustc to give us its version' 

How can i compile a version of realearn?

**Comment by helgoboss** [comment]
What OS?

**Comment by muziker** [comment]
My mistake, i should have mentioned. Linux ubuntu 20.04

**Comment by muziker** [comment]
Maybe rust needs to be a certain version ? Mine is rust 1.57

**Comment by helgoboss** [comment]
Sorry, took me a bit to try this. I just checked on a Ubuntu 20.04 VM:

```sh
rustup default 1.57.0
git checkout master
git submodule update
cargo clean

# Succeeds (at least at the current master branch tip 2afd3c3f1)
cargo build

git checkout v2.11.1
git submodule update
cargo clean

# Succeeds
cargo build
```

So it looks like it works here.

That said, the `core-error` crate is a bit of a hack, used to make `helgoboss-midi` usable even in no-std environments (very constrained devices). I might have to find an alternative for that.

**Comment by helgoboss** [comment]
Another note: Rust 1.57 is known to take ages compiling ReaLearn. Use 1.55 or 1.59+ to compile. Upcoming ReaLearn versions will need 1.59+ anyway because they use Rust 2021 edition features.

**Comment by muziker** [comment]
I wasn't familiar with rustup so had a quick look. The installation of it by way of curl to a piped shell seems pretty iffy

**Comment by helgoboss** [comment]
That's the official rustup way of doing it.

**Comment by muziker** [comment]
Turns out i didn't have nasm, and rustc 1.57.0 seems to hang on a futex wait. But upgrading to rustc 1.59.0 seems to work.

**Comment by muziker** [comment]
Also using the non repo rust seems to make the build work too

**Comment by helgoboss** [comment]
This should not occur anymore with ReaLearn >= v2.13.0-pre.5. It gets rid of the core-error crate.
