### ISSUE TITLE
Increase value sequence's precision one digit more

### ISSUE THREAD

**Issue by ElVicente** [helgoboss/realearn#540]
Hi Helgoboss.

I make this request following my question about the aurora fm synth, so I'd be able to set a coarse ratio properly for operators.
Cheers to you and your work !

**Comment by helgoboss** [comment]
Forgot to ask: Which unit, which target? Percentages? dB?

**Comment by ElVicente** [comment]
Sorry, I should have been more precise.

The taget is FX: Set parameter value,
The value is in percentage (I only have that available for this taget ).

If I'm correct the value sequence seems limited xx.xx numbers, with only two digits below the point, but I'd one need more digits to set the list correctly as this synth parameter goes from 0 to 30.995.
Hope it's clear enough!

**Comment by helgoboss** [comment]
Okay. I guess I will just increase the display/parse precision globally to 4 digits.

**Comment by ElVicente** [comment]
Thanks helgoboss !
