### ISSUE TITLE
Problems with the GUI in Linux (Manjaro)

### ISSUE THREAD

**Issue by SoliDeoGloria2** [helgoboss/realearn#542]
Hi!

I'd like to point out a certain issue with Realearn's GUI in Linux Manjaro. First of all, I've found a report in the issue tracker which coincides with this, although it's focused on Windows and MacOS :

https://github.com/helgoboss/realearn/issues/136

Since the issue is closed, I'd like to ask here first not to annoy with a mistaken post. The thing is this... on my notebook, I see Realearn's GUI like this :

<a href="https://imgur.com/7Pd6Tqp"><img src="https://i.imgur.com/7Pd6Tqp.png" title="source: imgur.com" /></a>

So, everything is fine (except for an important detail that I'll comment below * ).

But then, on my desktop PC, I see the same Realearn setup like this :

<a href="https://imgur.com/5150m7r"><img src="https://i.imgur.com/5150m7r.png" title="source: imgur.com" /></a>

And if I edit the first mapping, then the characters of it in the main GUI dissapear :

<a href="https://imgur.com/LCjNDji"><img src="https://i.imgur.com/LCjNDji.png" title="source: imgur.com" /></a>

It's good to remark that on both machines the OS and theme are the same. I use the libswell.so thing ([https://forum.cockos.com/showpost.ph...90&postcount=1](https://forum.cockos.com/showpost.php?p=2026790&postcount=1)) to have a dark appearance in the windows and menus of the theme I use. Regarding this issue, any insight will be deeply appreciated.

* And one more thing, this time on the notebook : when I have many mappings assigned, I cannot get to the last ones; the vertical slider on the right does not reach past a certain number of mappings. That's really serious, since I've been having to leave the mapping work for the desktop PC due to not being able to use Realearn to its full extent on the notebook.

**Comment by helgoboss** [comment]
> * And one more thing, this time on the notebook : when I have many mappings assigned, I cannot get to the last ones; the vertical slider on the right does not reach past a certain number of mappings. That's really serious, since I've been having to leave the mapping work for the desktop PC due to not being able to use Realearn to its full extent on the notebook.

This might be a matter of screen resolution. What's your resolution?

> It's good to remark that on both machines the OS and theme are the same. I use the libswell.so thing ([https://forum.cockos.com/showpost.ph...90&postcount=1](https://forum.cockos.com/showpost.php?p=2026790&postcount=1)) to have a dark appearance in the windows and menus of the theme I use. Regarding this issue, any insight will be deeply appreciated.

Could you try without any adjustments? Just pure REAPER for Linux, no `libswell.so` thing. Actually it's supposed to look like on your desktop PC (the one you think is wrong). The rows should be bright (there's no dark mode detection implemented for Linux). But of course, the text shouldn't disappear. So something weird is going on.

Also: What REAPER version and what ReaLearn version?

**Comment by geekositalia** [comment]
> > * And one more thing, this time on the notebook : when I have many mappings assigned, I cannot get to the last ones; the vertical slider on the right does not reach past a certain number of mappings. That's really serious, since I've been having to leave the mapping work for the desktop PC due to not being able to use Realearn to its full extent on the notebook.
> 
> This might be a matter of screen resolution. What's your resolution?
> 
> > It's good to remark that on both machines the OS and theme are the same. I use the libswell.so thing ([https://forum.cockos.com/showpost.ph...90&postcount=1](https://forum.cockos.com/showpost.php?p=2026790&postcount=1)) to have a dark appearance in the windows and menus of the theme I use. Regarding this issue, any insight will be deeply appreciated.
> 
> Could you try without any adjustments? Just pure REAPER for Linux, no `libswell.so` thing. Actually it's supposed to look like on your desktop PC (the one you think is wrong). The rows should be bright (there's no dark mode detection implemented for Linux). But of course, the text shouldn't disappear. So something weird is going on.
> 
> Also: What REAPER version and what ReaLearn version?

Same issue here, is related to modded color. 


I assume that the background of realearn is hard-coded white? if it is based on libswell which entry is it referring to? let me explain, the problem is that realearn captures the color of the characters from libswell, but not the background which appears to be white in a forced way. in this way the character which is white from libsweell, is on a white background.

if you have any solution, since the swell theme works perfectly everywhere, it is appreciated :)

**Comment by geekositalia** [comment]
Best solution for me is background captured from libswell config file (like any another gui, if possibile)

**Comment by geekositalia** [comment]
thread of ilogic theme https://forum.cockos.com/showthread.php?t=214879

**Comment by helgoboss** [comment]
I added a change that keeps the original background on Linux. I don't have the capacity to test this with other themes than the default theme at the moment but you can give it a try as soon as v1.13.0-pre.1 is out (today or tomorrow).

**Comment by geekositalia** [comment]
> 

nice! as soon as it comes out I take the test and let you know

**Comment by geekositalia** [comment]
@helgoboss nice! solved
![Screenshot_20220326_163915](https://user-images.githubusercontent.com/55261197/160246770-23ed6da0-32d5-490a-9d8a-80c64b8d34cf.png)

**Comment by SoliDeoGloria2** [comment]
Thanks so much for the fix, Helogoboss! It looks perfectly fine everywhere, now!
