### ISSUE TITLE
FX set offline/online - Track "all by name" not working when using "*"

### ISSUE THREAD

**Issue by Matt37137** [helgoboss/realearn#549]
Reaper takes cpu when fx are online, even when You mute the track they are on or take fx off. You implemented set fx online, but only one by one. It's great, but it would be awesome, if we could do it faster, with all fx on a track.

**Comment by helgoboss** [comment]
You can do that already. Just use "All by name" and enter "*".

**Comment by Matt37137** [comment]
Actually I don't... I tested it, and it doesn't work. It works only if I give relearn exact name of the track. Every character must be the same. If i use "*" or "?" it won't do the action, even when I select "by name" not "all by name". The "*" works great in "fx all by name", but not track.

**Comment by helgoboss** [comment]
Not the track selector (you already know which track). The FX selector. Check this out: https://imgur.com/a/8eFjTFu

**Comment by helgoboss** [comment]
Or do you want to do that on multiple tracks at once? In that case, please adjust the description.

**Comment by Matt37137** [comment]
Ok, I understand. That's why I thought about using something like Track: offline/online all FX, just like Track: enable/disable all FX. In this case, It could be used with only one "All by name" for tracks, because You can't change FX. 

Now I'm using, select tracks: all by name, and then use reaper action: fx offline, which is very slow. So I get that it wont be lightning fast, but everything will be faster than my current approach.

As I can see, using "all selected tracks" in FX offline doesn't work either.

With that limitation on board, I would need to make like 30 of those mappings :)

**Comment by helgoboss** [comment]
Yes, "All selected tracks" shares the same limitation.

Well, I think building extra targets would result in too much target bloat, so I guess I will just lift this limitation. But it will probably not be considerably faster than your current solution ... maybe it will save some time because it doesn't need to select the tracks that it affects.

**Comment by Matt37137** [comment]
Best way would be, that reaper actually unload CPU and ram, when using "disable all fx", but we have, what we have :) Selecting multiple tracks at once is actually quite a long process. Would very appreciate if You would lift this limitation! :)
