### ISSUE TITLE
OSC: Support "Respond to sending port" scenario

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#551]
At the moment, ReaLearn uses two different UDP sockets, one for sending and one for receiving.

In order to support devices which send responses to the port from which they received OSC messages (e.g. XR18), we should change that. Idea: Use one UDP socket only.

**Comment by Goodeeny** [comment]
Hi! I don't know much about sockets, but as I understand it, when creating a socket, the port is assigned automatically (the port number is probably random, I don't know ...), but a socket can be assigned a specific port when it is created (in theory, the port number that ReaLeran "Local Port" listens to) or, alternatively, ReaLearn should listen the port that was assigned by the system when creating a socket for sending UDP, unless another listening port is specified in the ReaLearn settings.

**Comment by Goodeeny** [comment]
I started WireShark and looked at the packets sent by ReaLearn. For the first time, UDP data is sent from port 64456 (local port 53277 is specified in the settings). I closed the Reaper, opened it again - UDP data is sent from port 51432, and in the settings (the local port 53277 is specified in the settings.

as I indicated above, it may help: Realearn listened to the port that was assigned when creating the socket, or ReaLearn should create a socket with a port that is specified as a "local port".

Maybe I'm wrong, but there are no other ideas ... :)

**Comment by helgoboss** [comment]
It's solved already. I must have referred the wrong commit.

**Comment by Goodeeny** [comment]
> Это уже решено. Должно быть, я сослался на неправильную фиксацию.

It is version 2.13.0-pre.1?
if so, there is no result yet..I'm sorry...

**Comment by helgoboss** [comment]
> > Это уже решено. Должно быть, я сослался на неправильную фиксацию.
> 
> It is version 2.13.0-pre.1?
> if so, there is no result yet..I'm sorry...

No, in the upcoming pre-release.

**Comment by Goodeeny** [comment]
> > > Это уже решено. Должно быть, я сослался на неправильную фиксацию.
> > 
> > 
> > Это версия 2.13.0-pre. 1? если да, то результата пока нет .. Извините...
> 
> Нет, в предстоящем предварительном выпуске.

Oh.. I get it... Really looking forward... thanks...
