### ISSUE TITLE
Store text (notes, resources like Lua scripts) with presets

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#555]
It would be nice to be able to store text with each preset.
This could be used for

- what is this preset good for?
- work-in-progress notes (what is not working yet, what could  be improved, ...)
- Lua snippets used in creating the preset

**Comment by tompad2** [comment]
Yes!

+1

**Comment by helgoboss** [comment]
I could offer a text field for storing small preset information, no problem. Where and when to display it?

As for storing Lua code used to build the preset: My plan is still to add an alternative way of storing and modifying a compartment: As Lua code. Then the single source of truth for that compartment would be the Lua code. Persistent changes would then only be possible by changing the Lua code (changes in the GUI would have a temporary effect only). I think that's a better solution than to store Lua code in the preset info field.

**Comment by vonglan** [comment]
Ah, I forgot about those plans for Lua.
Which means that the text field does not need >50 lines.

So then it could either be one long line, which might be displayed all the time in the window. But that would take up valuable GUI space - maybe not worth it.
Or a couple of lines, then it should be behind a button "preset info" (under "auto-load"; might change to "write preset info" if empty) or accessible via right-click menu.

My main intention was storing those Lua snippets, but as that is not required mid-term, I am not sure what is the best design.

**Comment by vonglan** [comment]
I just noticed an important use case:
Storing details about the mapping, e.g. "Bank 1 = Oscillators, Bank 2 = Mix, ..." or "use Button X to switch between upper and lower panel".

**Comment by helgoboss** [comment]
There's an undocumented feature that lets you assign labels to specific parameter values (for parameters which have a value count configured). It's accessible via Lua only. I use it in some upcoming presets to name banks. You'll see them in ReaLearn itself but also in REAPER (instead of something like 0.5). Interested?

Still probably useful to have a place where give some general instructions. So it should be multi-line I guess.

**Comment by vonglan** [comment]
a) Values for "countable" parameter values sound good, and already makes the use case above possible
b) Still, I am sure now a multi-line text field per preset would be useful. Maybe store it as a different file (same name, different extension e.g. .txt), so it doesn't come in the way when you edit the JSON manually or via VIM etc.

By the way, I just discovered the SiniCon device via the ReaLearn User Guide yesterday.
Looks very promising to me, except the price tag and that it's not (yet) built by an established manufacturer.
Maybe they make a smaller version one day (8 encoders, 16 buttons and 8 OLEDs would be sufficient for me).

**Comment by helgoboss** [comment]
Note to self: This should be not just part of the preset but the compartment itself. I want to display notes without having to save a preset.
