### ISSUE TITLE
Add advanced context menu action "Dry-run Lua script from clipboard"

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#556]
The way Lua import works in ReaLearn is:

1. ReaLearn executes Lua script (from clipboard)
2. ReaLearn attempts to interpret the return value as ReaLearn API object
3. ReaLearn loads the API object (after converting it into a data object, but that's a story for another day)

If step 1 fails, ReaLearn currently displays an error message that (hopefully) contains a line number. That's okay.

If step 2 fails, ReaLearn currently shows some validation error. This is sometimes not enough to know what went wrong.

The main problem about step 2 is that we don't even see the result of step 1 (= the data that the Lua script generated). That's why I'm going to add an action that executes the script and opens the result of step 1 in a browser or text editor - formatted as JSON.

**Comment by vonglan** [comment]
... or it could be put into the clipboard

**Comment by helgoboss** [comment]
Thought about that, too. But it needs that extra step of pasting.
