### ISSUE TITLE
Make textual feedback value available in EEL MIDI script

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#558]
This opens up more flexible MIDI feedback based on the text that one builds with textual feedback expressions.

**Comment by helgoboss** [comment]
Note: While this is still open for EEL, it's very much possible already now for the new Lua MIDI script. So not urgent!

**Comment by mycroftsnm** [comment]
> Note: While this is still open for EEL, it's very much possible already now for the new Lua MIDI script. So not urgent!

Hi, im looking for a way to send textual values such as track name or fx name to the LCD screen of an arturia keylab mk2 (the preset dont cover it, and the Display type feedback seems to not work with this one), so i need to convert these strings into HEX values, is this possible with Lua? Can u provide an example? i already readed the documentation (the [bcda] thing and stuff and i been trying for various hours but i dont get it .
If i send F0 00 20 6B 7F 42 04 00 60 01 <text here in hex> 00 F7 , as raw midi sysex, it works, but i want to make it work dinamically, probably this is no the best place to ask but i dont know where . thanks for your work, i hope i can contribute some day.

**Comment by helgoboss** [comment]
You need to use the MIDI script target, not the Raw MIDI target. It's explained in the user guide.

**Comment by mycroftsnm** [comment]
It took me several hours becaused i never used lua before but i almost have it,
```
return{
    messages = {
    {0xf0, 0x00, 0x20, 0x6b, 0x7f, 0x42, 0x04, 0x00 ,0x60, 0x01, 0x02, string.byte(y,1), string.byte(y,2) ,string.byte(y,3), string.byte(y,4) or 0 ,string.byte(y,5) or 0, string.byte(y,6) or 0, 0x00, 0xf7 }
}

}
```
now if i set the text expression to {{target.text_value}} it would show the fx parameter value in the lcd screen, nice!
 it is possible to send 2 variables to the Y variable? i would like to show the fx parameter name in line 1, and the value on line 2 of the lcd, but the sysex for editing the lcd must be one big message

**Comment by helgoboss** [comment]
Mmh, if it really needs to be one big message and the device doesn't let you set just a range of text, then I don't see a way to accomplish it at the moment. Let me think about that. Can you add that as new issue? Then it won't be forgotten.

**Comment by helgoboss** [comment]
I think this issue is not important anymore because Lua supports accessing the textual feedback value and it works wonderfully.
