### ISSUE TITLE
Track Peak (Stereo meters) affected by multichannel

### ISSUE THREAD

**Issue by AlbertoV5** [helgoboss/realearn#560]
Hello again Helgoboss,

![realearnPeakMultichannel5](https://user-images.githubusercontent.com/58243333/162842144-5bb3c4a3-c2fd-4d11-93e7-5b3f5022a69c.gif)

We already talked a bit about the peaks [here](https://forum.cockos.com/showpost.php?p=2532277&postcount=2077) and the solution for that one was [here](https://forum.cockos.com/showpost.php?p=2532285&postcount=2078). 

I was just wondering if there was a way to check for Stereo Peaks metering so it doesn't sum them all always.

EDIT: Just found it on the API

reaper.GetMediaTrackInfo_Value also has:

> I_VUMODE : int * : track vu mode, 
> &1:disabled, 
> &30==0:stereo peaks, 
> &30==2:multichannel peaks, 
> &30==4:stereo RMS, 
> &30==8:combined RMS, 
> &30==12:LUFS-M, 
> &30==16:LUFS-S (readout=max), 
> &30==20:LUFS-S (readout=current), 
> &32:LUFS calculation on channels 1+2 only

EDIT 2: Made a pull request about it.

Thank you!

**Comment by helgoboss** [comment]
@AlbertoV5 Cool, thanks for the PR. I'm quite busy with other changes at the moment but hope to look into it soon.
