### ISSUE TITLE
Logging function for values sent to targets (VST etc.)

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#572]
When debugging presets, this might be helpful.
So there would be three kinds of messages logged:
- real (e.g. MIDI) from/to physical controllers
- virtual (passed between Controller and Main Mappings)
- target (e.g. values sent to a VST, and requested or simply received from it)

**Comment by helgoboss** [comment]
Yes, that would be good. I also just debugged an issue where one mapping sent something to a target and the other one kind of undid it. Was hard to know what's going on.
