### ISSUE TITLE
Problem with virtual routing (multiple virtual targets)

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#573]
The following presets logic does not work as expected (or not reliably - I think I already saw it working):

Use case: a press of a specific button should reset all values in one "area" (e.g. Operator 1 Envelope).

- In the Controller Mapping, when the button is pressed, 8 virtual targets are addressed, called "EncoderPress1" to "...8"
- (when the encoders are pressed physically, individually, the reset parameter action works)
- In the Main Mapping, there are 24 different banks, for different areas
- In each bank, there are mappings that receive the "EncoderPress_i" virtual sources, and set a VST parameter to a fixed value

In the log, I do not see any "Virtual control input"s when I press the "reset area" button.

**Comment by helgoboss** [comment]
Do you have a test project?

**Comment by vonglan** [comment]
I can prepare one.
Just did a quick re-test this morning, after restarting the Computer:
Now the "reset" works (see below), but the feedback for some buttons does not work (that also seemed unstable yesterday evening).

1650606828.406 | ReaLearn 8LNE2BU7 | Virtual control input | Button DX/EncoderPress1 with value 127/127 at Instant { t: 3113642715 } (matched)
1650606828.410 | ReaLearn 8LNE2BU7 | Virtual control input | Button DX/EncoderPress2 with value 127/127 at Instant { t: 3113642715 } (matched)
1650606828.413 | ReaLearn 8LNE2BU7 | Virtual control input | Button DX/EncoderPress3 with value 127/127 at Instant { t: 3113642715 } (matched)
1650606828.416 | ReaLearn 8LNE2BU7 | Virtual control input | Button DX/EncoderPress4 with value 127/127 at Instant { t: 3113642715 } (matched)
1650606828.418 | ReaLearn 8LNE2BU7 | Virtual control input | Button DX/EncoderPress5 with value 127/127 at Instant { t: 3113642715 } (matched)
1650606828.421 | ReaLearn 8LNE2BU7 | Virtual control input | Button DX/EncoderPress6 with value 127/127 at Instant { t: 3113642715 } (matched)
1650606828.424 | ReaLearn 8LNE2BU7 | Virtual control input | Button DX/EncoderPress7 with value 127/127 at Instant { t: 3113642715 } (unmatched)
1650606828.427 | ReaLearn 8LNE2BU7 | Virtual control input | Button DX/EncoderPress8 with value 127/127 at Instant { t: 3113642715 } (unmatched)

**Comment by helgoboss** [comment]
There are some known issues (fixed in upcoming pre.4) related to feedback if you use conditional activation in the controller compartment (with virtual targets).

**Comment by vonglan** [comment]
Hm, if this problem is solved with  pre.4, I would not want us to put any effort in.
I do not use conditional activation in the controller compartment, but I set two main parameters for "bank" and "area" from the controller compartment. The main compartment has conditional activation of groups from these parameters.
Other special circumstances are:
One physical button triggers several virtual targets (as described above), AND the same virtual target is triggered by several physical buttons.
It seems there are three problems
- Feedback sometimes not working
- Virtual targets sometimes not addressed
- It also seemed to me that the feedback LED rings on the encoder flicker, but I have not checked this in detail (might also be something completely different)

If you think, that these things might be improved by changes in pre.4, I will wait until then.

**Comment by vonglan** [comment]
Just saw this again, in discussions: #502 
One part of that was virtual targets not being triggered.
The other part was incorrect usage of NRPN source max. Didn't you already fix this?

**Comment by helgoboss** [comment]
If you use target "FX: Set parameter value", #574 could explain some of the issues. Just discovered this bug.

**Comment by vonglan** [comment]
I think, "FX: Set parameter value" is not essential to these problems here, because the virtual targets are not addressed (judging by the log), before even reaching the "FX: set parameter value".

The problem description above, under
> Hm, if this problem is solved with pre.4, ...
is pretty accurate.

If I have time (not the next few evenings), I can investigate further, and try to create a "minimal" project which is able to reproduce the problems.
Unfortunately, it seemed that these are "instable" problems (the next day, I could not reproduce the phenomena in a quick test).

**Comment by vonglan** [comment]
Tried to recreate it today. Found some bugs in my mappings ("Send Feedback after Control" was missing in some places, some unnecessary Feedbacks were on for encoder presses). After fixing the bugs, I could not reproduce any of the problems. So I close this issue.
