### ISSUE TITLE
Target maximum value can be exceeded in relative mode

### ISSUE THREAD

**Issue by valankar** [helgoboss/realearn#577]
I have setup a relative encoder to set volume for a selected track. I've set the target max to 0 db. However, the actual maximum becomes 0.17 dB. If I set the max to 1 dB, it actually goes to 1.09 dB

Please see the following screen capture:

https://i.imgur.com/wrnAjt4.gif

Have I setup something wrong?

The device I'm using is:

https://intech.studio/shop/modules/en16

and I have set it to relative mode via:

https://intech.studio/support/docs/reference-manual/control-element-functions/encoder#encoder_mode

**Comment by helgoboss** [comment]
Looks like it obeys the maximum but not 100% accurate. Not sure why. Will look into it, approximately in some weeks. Until then you can work around the issue by simply entering a smaller value.

Oh, and I need a test project (no 3rd-party plug-ins).

**Comment by valankar** [comment]
Sorry, but entering a smaller value where? In Target Max? I tried putting some value there but I can't figure out what maps to 0 dB. For example, setting target max to -0.15 results in a max value of -0.29. 

https://i.imgur.com/91IzWFi.jpg

I've attached an example project.

[realearn volume issue.zip](https://github.com/helgoboss/realearn/files/8717990/realearn.volume.issue.zip)

**Comment by helgoboss** [comment]
Yes, I meant in Target Max. Just had a quick look. It only happens with relative control. Seems like it doesn't obey Target Max when doing the last step before reaching the Target Max. If the step size is large, it will just "step over" Target Max.

Workaround is to lower Step Min/Max, but this is obviously not desired in most cases. Or use "Make absolute", but then you lose the advantages of relative control.

So the only real fix - if you need that amount of accuracy - is that I fix it on ReaLearn side. It's a bug.

**Comment by helgoboss** [comment]
This happened because ReaLearn was adjusting the target min/max interval so it's a multiple of the step size. This makes sense for targets with discrete values - in order to not end up on a value in-between its discrete values. It doesn't make sense for continuous targets such as yours (track volume), so I disabled that behaviour for continuous targets. It should now obey target min/max 100% accurate. (in upcoming 2.13.0-pre.5)

**Comment by valankar** [comment]
Thanks!
