### ISSUE TITLE
'Edit mapping' window not fully visible/cut off vertically 

### ISSUE THREAD

**Issue by nofishonfriday** [helgoboss/realearn#589]
On my laptop (Thinkpad T420, Win10, resolution: 1920*1080, native, Windows display scaling: 150%, recommended, no other scaling settings active) I can't fully see/access the 'Edit mapping' window vertically.

Related forum posts: [2278](https://forum.cockos.com/showpost.php?p=2566651&postcount=2278), [2282](https://forum.cockos.com/showpost.php?p=2567270&postcount=2282), [2287ff](https://forum.cockos.com/showpost.php?p=2567302&postcount=2287).

Screenshot:
https://i.imgur.com/bvs6GKL.png

**Comment by helgoboss** [comment]
I'll wait with this until https://github.com/helgoboss/realearn/pull/576 is through.

**Comment by helgoboss** [comment]
@nofishonfriday I managed to decrease the size of the mapping window by reducing the vertical spacing and button heights.

Does the main window fit on your screen? The mapping window is now even a bit smaller than that one: https://i.imgur.com/5zjZ71i.png

**Comment by nofishonfriday** [comment]
Main windows does fit on screen vertically in default size (though a bit tight, so screenshot), so I guess mapping window should now too with this change.
Thank you!

https://i.imgur.com/9DraD7x.png

**Comment by helgoboss** [comment]
It really is smaller than the main window. You just get the impression that it isn't because you don't see the complete main window 😆

**Comment by helgoboss** [comment]
In pre.7, the main panel should be smaller as well. I decided to give it 5 rows only instead of 6 to make sure it fits. I also made improvements regarding the layout/sizes on Windows, macOS and Linux.

**Comment by nofishonfriday** [comment]
It's good now since pre7, thank you!
https://i.imgur.com/PIiptVz.png

**Comment by helgoboss** [comment]
Awesome. Happy the effort worked out. These changes luckily made the GUI more maintainable in general.
