### ISSUE TITLE
Increasing number of ReaLearn parameters

### ISSUE THREAD

**Issue by thricedotted** [helgoboss/realearn#60]
https://github.com/helgoboss/realearn/blob/a425f25954048405425d2c7727c6094a1ff4f318/main/src/domain/main_processor.rs#L27

Right now the plugin is hardcoded to have 20 parameters. Could this be increased to, say, 64? Or more?

My extremely specific use case is that I would like to toggle the knobs on a MIDI Fighter Twister, but I don't have enough parameters to store the toggle state of my 64 virtual knobs. I can get around this with multiple ReaLearn instances -- say, one for each bank of 16 -- but that makes my plugin chain rather cluttered.

(Also -- ReaLearn is awesome, thank you!)

**Comment by helgoboss** [comment]
Finally a request that is very easy to implement 😅 No problem, will raise it for the next pre. I guess 100 will do it for now.

**Comment by thricedotted** [comment]
Yay! Thank you so much 😄
