### ISSUE TITLE
Copied mappings that get duplicated are placed in original group

### ISSUE THREAD

**Issue by arthurmcarthur1** [helgoboss/realearn#609]
Found a minor bug: when copying and pasting a mapping from mapping group Default into another group and then duplicating, it duplicates it in the original group and not the new one. 
![2](https://user-images.githubusercontent.com/79480466/174505289-47d7c70e-990a-4f5e-ad14-6b8d38cce5b3.gif)
.

**Comment by arthurmcarthur1** [comment]
Easy to work around by duplicating in the original group and then using 'Move to group' from right click context menu

**Comment by helgoboss** [comment]
This is probably #608.

**Comment by helgoboss** [comment]
Fixed in #608 already.
