### ISSUE TITLE
How to tell if any Fx is currently in focus

### ISSUE THREAD

**Issue by IOphonics** [helgoboss/realearn#625]
Hi, 
just a little question.

I would love to:
 - use my Midi Fighter twister to control the focused FX in auto-load mode
 - with the same device, control different Reaper parameters (like track volumes, pan, sends, etc.) when no FX is in focus

Therefore I'd obviously need a way to tell if any FX is currently in focus. But I just can't find a clean solution to that. Could you possibly point me in a fruitful direction? I have the feeling that I'm missing something obvious here, but I'm running out of ideas and places to look for answers...

Just a quick thought:
Wouldn't it be convenient being able to add an option for an FX-to-preset link for when no FX is focused? Something like a selectable default preset for auto-load mode. That would help me big time.

**Comment by helgoboss** [comment]
The way to do this at the moment is to use 2 instances. One auto-load instance and one normal instance (the one with the fallback mappings). You need to make the auto-load instance superior so the fallback mappings are disabled as soon as a supported plug-in is focused.

Please don't create issues for questions. Either use the discussion section or post in the ReaLearn thread at the REAPER forum.

**Comment by helgoboss** [comment]
Closing this now because there's a solution (and a similar FR #408 for achieving the same with just one instance).
