### ISSUE TITLE
Improvements for vice versa control (Reaper as controller, device as target)

### ISSUE THREAD

**Issue by GassnKlang** [helgoboss/realearn#658]
I'm using reaper to control a mixing desk (Behringer x32 via OSC). It generally works with the current realearn functions but some behaviours are unwanted. Bypassing ReaLearn leads to weird values on the x32 (faders move to -infinity, mutes are being activated, pannings jump to hard left and so on).
It would be nice to have the possibility to use Reaper as a live show controller.

**Comment by helgoboss** [comment]
Note to self about naming this new option: "Reset feedback when releasing source" (should be unchecked when using REAPER itself as a remote).
