### ISSUE TITLE
ReaLearn stays active when bypassing it via automation

### ISSUE THREAD

**Issue by GassnKlang** [helgoboss/realearn#659]
Manually bypassing ReaLearn works as expected but if it is bypassed via automation, it stays active and connected all the time even if reaper shows its bypassed state.

**Comment by jamesd256** [comment]
I maybe 'mis-remembering', but I would like to add the comment that when ReaLearn is in the monitoring FX, bypassing manually leaves it active, while when in a track FX, it behaves as expected.

Not an issue for me, just an observation

**Comment by helgoboss** [comment]
I reproduced the issue. ReaLearn doesn't observe changes of its Bypass parameter so far. It only observes explicit enable/disable events. Internally, these are apparently two different things. I will fix this.

**Comment by helgoboss** [comment]
It works with the "Bypass" parameter now, but turns out it doesn't yet work when the "Bypass" parameter is automated via envelope.

**Comment by helgoboss** [comment]
REAPER doesn't call CSURF_EXT_SETFXPARAM for the special BYPASS parameter. I asked Justin if this is intended or not. Let's see. If it's a bug, it should be fixed on REAPER side. If not, I must resort to polling :/

**Comment by helgoboss** [comment]
Justin confirmed it will be fixed in REAPER itself.
