### ISSUE TITLE
A bug appeared in the last version of realearn for Feedback of "Markers/Region : go to "

### ISSUE THREAD

**Issue by dissofiddle** [helgoboss/realearn#663]
A new issue appeared in the last version of realearn for the feedback of "Markers/Region : go to".
It used to work as expected but does not  any more.

here is what is happening :
- when playback is stopped : feedback is not sent when changing region.
- when playback is on :  feedback is sent corretly until playback is stopped. In that case, feedback is sent as if the sequencer was still going on. 
    Exemple : let say we have 4 ordered regions and playback is started at region 1, and stopped before the end of  region 2. On the controler, feedback of region 3 and 4 will be sent anyway as if the sequencer was never stopped, which should not happen.

**Comment by helgoboss** [comment]
Thanks, could reproduce. Attempting to fix.
