### ISSUE TITLE
Add mouse target (e.g. for controlling currently hovered parameter)

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#686]

**Comment by helgoboss** [comment]
This is going to be possible, soon. At least with plug-ins that allow mouse wheel control of parameters. Maybe I also get mouse dragging to work, but let's see.

**Comment by helgoboss** [comment]
Tested on macOS so far.

Known issues:

- "Move cursor to/by": Fast repeated invocations can actually result in less distance because the OS doesn't process each movement. Ideas:
    - Don't report the actual mouse position as current value but the last set one.
    - Throttle
- "Move cursor to/by": Using a high-res fader with "Make relative" seems to do pretty large steps even if invoked very softly.
- "Turn scroll wheel": Appeared to have a similar issue as with moving the cursor. Investigate.
- Simulating a drag works on REAPER's faders but not on REAPER's circular controls (but using wheel scroll simulation should be preferred anyway because the mouse cursor doesn't leave its initial position - not all plug-ins make sure the mouse cursor stays at position)
- Not having "Accessibility" privilege granted will make ReaLearn panic (`device_query` crate issue)

**Comment by helgoboss** [comment]
A new issue has been created for the remaining issues. Not that important right now. The basics work quite well so far and users like it.

**Comment by orivej** [comment]
Thank you for your work!
I have noticed that now (since v2.14.0) the Linux plugin ReaLearn-x64.so has a dynamic dependency on libxdo3: it is not just a build time dependency — end users have to install it too, otherwise Reaper fails to enable the plugin. It seems worth mentioning this in the installation instructions and in the changelog.
