### ISSUE TITLE
Mapping source: MIDI channel display only updates intermittently

### ISSUE THREAD

**Issue by MonkeyBars3k** [helgoboss/realearn#699]
[macOS Catalina]

Sending MIDI (CC2 in this case) through Learn Source on a Mapping detects correctly for usage, but the UI doesn't display the correct channel, neither in the Mappings list nor in the Edit Mapping window. Less than half the time when changing MIDI channels in the source, the ReaLearn UI updates to display the correct channel. But usually it defaults to MIDI channel 1. Also, upon changing channels, often the displayed MIDI channel number will incorrectly change to channel 1.

**Comment by helgoboss** [comment]
I can't reproduce this. Any detailed instructions that can reproduce the problem? Maybe it's related to something that you do before/after setting the channel?

**Comment by helgoboss** [comment]
Also, a video/gif would help.

**Comment by MonkeyBars3k** [comment]
https://i.imgur.com/61eLnKl.gif

**Comment by MonkeyBars3k** [comment]
In that LICEcap, the signal source is ReaRack3 Signal Processor and you can see the ReaControlMIDI log showing the MIDI data outputting with the correct channel above, but the ReaLearn Mapping Channel doesn't update as the data comes in.

**Comment by helgoboss** [comment]
Which ReaLearn version? Can't reproduce in latest pre-release. Tried pretty much the same, but with ReaControlMIDI itself as the signal source. It works as expected, the channel visually changes in both windows.

**Comment by MonkeyBars3k** [comment]
I just realized ReaControlMIDI is changing the incoming signal channel to its set channel! Thanks for chiming in so quickly. You're a legend sir. By the way, do you know of a simpler MIDI logger for Reaper? ReaControlMIDI is obviously not a safe choice for simple data stream monitoring.

**Comment by helgoboss** [comment]
You can set ReaControlMIDI's channel to "All" and it shouldn't cause this issue. I always use it for MIDI logging.
