### ISSUE TITLE
Target track number not saved with preset

### ISSUE THREAD

**Issue by DLongoni** [helgoboss/realearn#7]
If I save a preset with reaper "save preset" function and then I reload it on another project the track numbers are replaced sometimes with <This> and sometimes with seemingly random numbers. The same is true for "Send effect" number with target set to "Track send volume".

Am i doing something wrong?

**Comment by helgoboss** [comment]
Not implemented. See https://bitbucket.org/helgoboss/realearn/issues/136/make-it-possible-to-find-track-also-by.

**Comment by helgoboss** [comment]
Related (same with FX): https://bitbucket.org/helgoboss/realearn/issues/164/make-it-possible-to-address-fx-by-name

**Comment by DLongoni** [comment]
I see, sorry, I didn't look for it on bitbucket. I really think this could be very useful!

**Comment by helgoboss** [comment]
Combinations that make sense in my opinion:

Id, name, pos ×
Id, pos, name ×
Name, id, pos ×
Name, pos, id ×
Pos, name, id ×
Pos, id, name ×

Id, name × CURRENT (keep for compatibility)
Id, pos ×
Name, id ×
Name, pos ×
Pos, name ×
Pos, id ×

Id ✓
Name ✓
Pos ✓

... fallback combinations are not really useful. So a single dropdown for saying what anchor to use to lookup the track should be sufficient.

**Comment by DLongoni** [comment]
Totally agreed. Personally, this is the most useful feature I am currently missing, thank you so much for looking into it.

**Comment by DLongoni** [comment]
Hello, sorry to annoy you again on this. Been using relearn for quite some time, the lack of this feature is becoming more and more of a limit for me, I just wonted to know if you had any plan of looking into this sooner or later, cause otherwise I have to look for another solution. Just for info, not to pressure. Thanks a lot.

**Comment by helgoboss** [comment]
I will look into this in the next days. Probably simple for me to fix, difficult for you to migrate to something else.

**Comment by DLongoni** [comment]
True that for me it would be a mess. Don't know about how easy it could be for you, but that would be awesome, thanks a lot.

**Comment by helgoboss** [comment]
Implemented in upcoming v1.12.0-pre6 including a better handling of non-present tracks

**Comment by DLongoni** [comment]
Looking forward to this!
