### ISSUE TITLE
Conflicts with reablink package

### ISSUE THREAD

**Issue by mantsar** [helgoboss/realearn#705]
Hello,

I am using Reaper on linux with pipewire and reablink package https://github.com/ak5k/reablink built directly from source (because for me version from reapack does not work) + realearn (from reapack).

I post it here because I get realearn crash message (hope its correct way to do things).

Crashes on transport stop with error:

```
REAPER version:      6.68/linux-x86_64
Module name:         ReaLearn
Module version:      v2.13.1/x86_64 rev bf74f7 (2022-07-09 14:32:54 UTC)
Module base address: -
Module size:         -

Message: this function must be called in the main thread

   0:     0x7fc30b5ca947 - <unknown>
   1:     0x7fc30b5cc9b5 - <unknown>
   2:     0x7fc30b4a9a57 - <unknown>
   3:     0x7fc30b614e00 - <unknown>
   4:     0x7fc30b614bf9 - <unknown>
   5:     0x7fc30b612ff4 - <unknown>
   6:     0x7fc30b614969 - <unknown>
   7:     0x7fc30a771793 - <unknown>
   8:     0x7fc30b48960c - <unknown>
   9:     0x7fc30ad75a06 - <unknown>
  10:     0x7fc30a94b1c0 - <unknown>
  11:           0x55655c - <unknown>
  12:     0x7fc338039f2a - _ZN5blink11BlinkEngine13AudioCallbackERKNSt6chrono8durationIlSt5ratioILl1ELl1000000EEEE
  13:     0x7fc33803b8d2 - _ZN5blink11BlinkEngine6WorkerEv
  14:     0x7fc38c2d62f3 - execute_native_thread_routine
                               at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82:18
  15:     0x7fc38c09f8fd - <unknown>
  16:     0x7fc38c121a60 - <unknown>
  17:                0x0 - <unknown>
```

**Comment by helgoboss** [comment]
Thanks for the report. Mmh, this could actually be a bug in ReaBlink. Looks like the REAPER stop function is called in the audio thread which is undefined behavior according to REAPER SDK as far as I know. I'll check back with Justin.

**Comment by helgoboss** [comment]
@mantsar This must be solved in ReaBlink. It's an unsafe usage of the REAPER API (which can lead to crashes in worst case) and ReaLearn's error reporting just made it visible. Closing.
