### ISSUE TITLE
add control command to YAML

### ISSUE THREAD

**Issue by alanleedev** [helgoboss/realearn#718]
This is both a request and a question on if this is possible.
When I use my controller (nanoKontrol 2) for basic mixing to control channel faders/pan and switching banks, I would like an easy way to tell which channels can be controlled without looking at the external projection screen. 
Even if after looking at the projection, it is not straight forward to figure out which channels are being controlled if I have many tracks.

So my idea is this, If I arm the tracks that can be controlled then I have a easy visual indicator on which are controlled by the controller.
So I am asking if you can add sending MIDI control commands to reaper via YAML when a group is active so I can set the arm button.
Let me know if this is not possible.

**Comment by helgoboss** [comment]
Hi. I'm not entirely sure what you mean. So you want that ReaLearn arms tracks for you, but not for the sake of arming them, just for the sake of having a visual indication of which tracks are under control?

Maybe we can take a step back. How does your setup look like?

**Comment by alanleedev** [comment]
That is right, as a visual indicator.

I have Korg nanoKontrol2 and have mapping with multiple banks so I can switch from Ch1~Ch8, Ch9~Ch16, ... so forth.
It is bit of a hassel to figure out which channels I am controlling.

**Comment by helgoboss** [comment]
I assume by channels you mean tracks? 

How did you implement these banks? Using conditional activation (the "Active" dropdown)? Or do you make your nanoKontrol2 send MIDI on different MIDI channels?

**Comment by alanleedev** [comment]
Yes, I mean tracks. I am using conditional activation so I have a multiple banks each mapped to a group.

**Comment by helgoboss** [comment]
Someone else came up with a similar goal: Automatically hiding all tracks that are not under ReaLearn's control. I came up with an idea how to allow both goals to achieved elegantly: #740. Yours would be the same, you would just use target "Track: (Dis)arm" instead. So I'll close this for now and you can follow progress at #740.
