### ISSUE TITLE
Offer control transformation template that makes linear control of logarithmic ReaPlug parameters possible

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#725]

**Comment by helgoboss** [comment]
Note to self: ReaComp's Threshold parameter is such a "logarithmic" parameter. Its dB value appears to be calculated using the formula `dB = log10(x * 2) * 20.0`, where `x` is the incoming normalized value between 0.0 and 1.0. This results in a target value range from -inf to 6 dB.

Some notable values (x to dB):

- 0.0 => -inf
- 0.5 => 0 dB
- 1.0 => 6 dB

**Comment by fbeauvaisc** [comment]
Hey thank you so much for helping me. While testing I've come to realized that even when using the "adjust last touch parameter" action. The Threshold of ReaComp is kind of oddly mapped.

**Comment by MonkeyBars3k** [comment]
Is there a default Reaper volume (fader) curve available somewhere in ReaLearn?

**Comment by helgoboss** [comment]
> Is there a default Reaper volume (fader) curve available somewhere in ReaLearn?

For all volume-related targets, ReaLearn just delegates to REAPER when it comes to converting a normalized value (0 to 1) to an actual dB value. And for FX parameter target it's similar, it just delegates to the FX (the plug-in). So whatever you see is the native REAPER/plug-in behavior. ReaLearn doesn't interfere.

As it turns out, some of this native REAPER/plug-in behavior is not what you want/expect. So what we  we are trying to do in this issue is finding a control transformation formula that changes/reverses the native curve in order to get the curve that you want/expect. I'm pretty bad at basic math to be honest, haha, so this is not trivial for me.

> I don't understand is why this formula does not result in a linear progression from -inf to +6
> 
> It still jumps from -inf to -26.5 ![image](https://user-images.githubusercontent.com/45170893/198356439-36d5d37e-d6a7-4933-8d2c-f51ed6f9badb.png)

Well, you can simplify your formula: `y = x` ;) So your control transformation doesn't change the original value at all. And that's the whole issue: We need to change it in order to reverse the unwanted curve that ReaComp gives you.

**Comment by helgoboss** [comment]
@fbeauvaisc Check this out. This gives you something linear in terms of dB, starting at -120 dB and ending at 6 dB.

```
// Parameters

min_db = -120;
max_db = 6;

// Code

shift = -min_db;
compress = max_db - min_db;
y = (10.0 ^ ((compress * x - shift) / 20)) / 2
```

This creates an exponential curve which is essentially the opposite of the logarithmic curve ReaComp uses to interpret the incoming parameter values. The result is that the curve is "cancelled out", so you get a linear line (in terms of dB).

I think this is as linear as it can get. Whether you really want a linear dB scale (or just think you want) is another story ;) Keep in mind that dB is a logarithmic scale for a reason (see for example https://physics.stackexchange.com/questions/6588/why-is-the-decibel-scale-logarithmic).

Controlling it in a linear fashion over a large range (such as 126 dB in above example) of course gives you less resolution in the higher value range (e.g. over 0 dB). Most absolute MIDI controls have only 7-bit resolution, that is 127 possible values. So you will end up having quite coarse-grained control (1 dB) per fader/knob movement). So you should pick the sub range that's of most interest to you! Some faders support 10-bit resolution (1024 possible values), which gives you more fine-grained control over a large range.

**Comment by helgoboss** [comment]
Some more considerations:

- If you are looking for a very specific mapping from your 128 possible MIDI control values to particular dB, you can use a "Value sequence" consisting of 128 dB values :) Then it's completely up to you and you don't even need to find a formula for it.
- With a 10-bit fader, a value sequence of up to 1024 values would make sense.
- If you want **real relative control** (using an encoder that emits relative messages and without "Make absolute"), then "Value sequence" is probably also the best possibility. It supports relative movements within that sequence. Then you can have arbitrary precision!

**Comment by helgoboss** [comment]
@fbeauvaisc Let me know if that solves your problem. Then I would add this formula as template.

**Comment by fbeauvaisc** [comment]
The last formula works very well. There's a "fine adjust" shift key on the Console 1 and when pressed, I can now turn smoothly through every single dB. Without holding the fine adjustment, it jumps in 3 dB steps and that's fine.

Yes, I though about the value sequence and am already using it for specific ratios. For 128 values, maybe doing it in sublime first and then just copying it in the entry box but your formula is doing great.

Thanks a lot!

**Comment by helgoboss** [comment]
Cool. I will add this as "ReaComp Threshold linearization" template in upcoming ReaLearn v2.14.0-pre.8.
