### ISSUE TITLE
FX Parameter : Set Value is not responding to controller after being set Online

### ISSUE THREAD

**Issue by fbeauvaisc** [helgoboss/realearn#730]
I'm having a weird issue. I'm trying to have a controller turn an FX from it's offline to online state so that I can save CPU on a custom channel strip.

That same controller is also sending a parameter value. So when I turn the knob, I want the FX to be turned from offline to online and also start tweaking values in a single motion.

It works perfectly well with Enable/Disable plugin but not with Offline/Online for some reason.

It does switch the FX state from offline to online but once online, the FX is not responding to "FX parameter : set value". I need to unselect the track then re-select it for the FX to respond.

Thanks,

**Comment by helgoboss** [comment]
More input from you on the forum: https://forum.cockos.com/showpost.php?p=2610294&postcount=2775

**Comment by fbeauvaisc** [comment]
Well it's a different thing but yes, it's a similar issue. The first issue mentioned above is about some parameter changes being ignored or not being registered. The second post on the forum is about the midi feedback not sending the parameter state on some plugins vs others. 

Basically I kind of went around the first issue with the second approche where I want to have a single button triggering Online/Offline state instead of being automatically turned online when I change a parameter. 

But ran into another issue where when inserting a new track, sometimes it will register as if it was Online so when I press the button (toggle), is want to turn itself Offline thus doing nothing on the first press and I need to press twice to turn the FX from Offline to Online.

For some reason, ReaGate is always working properly but ReaEQ and ReaComp are not.
