### ISSUE TITLE
"Learn Many" assigns fake target from source movement

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#732]
v2.14-pre.9
Reaper 6.68

In Main compartment, with the virtual SY parameters as source
when I start "Learn many"
turning my X-Touch Mini encoders by one click, ReaLearn correctly detects the virtual source. When I turn it one click more (sometimes only when it is in the other direction), a wrong target is assigned (from a different track), without having touched any VST GUI.

Maybe some GUIDs are confused?

Example mappings (with wrong targets) created like this:
{
    kind = "Mapping",
    value = {
        id = "2GFd4Vw4TMUsX2tziSzdv",
        name = "57",
        source = {
            kind = "Virtual",
            id = "SY/Cutoff",
        },
        glue = {
            step_size_interval = {0.01, 0.05},
            step_factor_interval = {1, 5},
        },
        target = {
            kind = "FxParameterValue",
            parameter = {
                address = "ById",
                fx = {
                    address = "ById",
                    chain = {
                        address = "Track",
                        track = {
                            address = "ById",
                            id = "CA0073F4-663C-7646-803E-4595CE3B5F0A",
                        },
                    },
                    id = "21FE274A-1732-B94C-87FF-DC4FE702F682",
                },
                index = 145,
            },
        },
    },
}

on subsequent track:
{
    kind = "Mapping",
    value = {
        id = "CL9iue6YV9-7hICOyaOmg",
        name = "51",
        source = {
            kind = "MidiControlChangeValue",
            channel = 10,
            controller_number = 2,
            character = "Relative1",
            fourteen_bit = false,
        },
        glue = {
            step_size_interval = {0.01, 0.05},
            step_factor_interval = {1, 5},
        },
        target = {
            kind = "FxParameterValue",
            parameter = {
                address = "ById",
                fx = {
                    address = "ById",
                    chain = {
                        address = "Track",
                        track = {
                            address = "ById",
                            id = "CA0073F4-663C-7646-803E-4595CE3B5F0A",
                        },
                    },
                    id = "21FE274A-1732-B94C-87FF-DC4FE702F682",
                },
                index = 51,
            },
        },
    },
}

**Comment by vonglan** [comment]
I checked with some older versions. It also happens with 2.13.1 and 2.12

**Comment by helgoboss** [comment]
Could be a bug. Just to be sure: Do you maybe have another instance (e.g. on monitoring FX) which reacts to the same source?

**Comment by vonglan** [comment]
No FX in Monitoring. And only one track selected and record-armed.

If that saves you some time, I could check successively with older version.

**Comment by vonglan** [comment]
ok, I will try to find out something
maybe I will look if the GUID is duplicate

I can also check whether it can be reproduced with an all-new project.

Not sure whether I can send you a reproducible project.

**Comment by vonglan** [comment]
I found the reason:
I had another track, with the same, dedicated Control Input = X-Touch Mini.
After I cleaned up all ReaLearn instances in that project to use <fx input>, I could not reproduce the problem.

> Just to be sure: Do you maybe have another instance (e.g. on monitoring FX) which reacts to the same source?

I should have read that more thoroughly ;-)

I could reproduce it as follows:
First track: Controller Input and Feedback Output = X-Touch Mini
Second track: Controller Input and Feedback Output = X-Touch Mini
Start "learn many"
Twist encoder by more than 1 click
--> Target is found, belonging to first track VST

The Target is exactly the one, that is addressed by the ReaLearn mapping in the First Track ReaLearn mapping setup.

Maybe it would be good if ReaLearn displayed some kind of warning (or a count), if more than one ReaLearn instance in a project use the same dedicated control input (and don't pass through all events).

**Comment by vonglan** [comment]
or ReaLearn could show a warning popup, when "Learn many" is called by the user, and there are multiple instances with the same dedicated control input

**Comment by helgoboss** [comment]
I would prefer #232 instead. Closing this. Let me know if this wouldn't solve it.

**Comment by vonglan** [comment]
Sounds good.
