### ISSUE TITLE
Ability to create Reaper Actions for Realearn's controls. Specifically,  the "Learn Target" Function

### ISSUE THREAD

**Issue by cldswm** [helgoboss/realearn#744]
In the forum we discussed whether if there was a possibility to have the ability for the user of Realearn to be able to access the learn target function for any Mappings they desire.

I've thought about 2 possible methods for this to happen:

1. With the current ability to target another instance of Realearn, allowing user to activate/ deactivate instances , mappings, save & load snapshots as well as navigating within the Realearn UI. Was there also a possibility to create Target Controls for the Learn Target function ? This would be achieved by using TAGS. But the problem is that currently its not possible to use TAGS from another instance of Realearn if I'm correct.

2. Another way of doing this could be just to allow users to create Reaper ACTIONS that refer to Realearn's functions, such as Learn Target.

Am not sure which one would be easier to implement, but would be interesting  for a discussion.

Thanks!

**Comment by helgoboss** [comment]
Okay, so you want ReaLearn instance A to switch "Learn target" of a particular mapping in ReaLearn instance B. Correct?

Then I think it would make sense to add a new target "ReaLearn: Learn target of mapping" that allows you to choose a ReaLearn instance (This or a particular one or all tagged) and a mapping (particular one or first one tagged).

**Comment by cldswm** [comment]
Yes this would be fantastic!

Would it be easy and quick to implement :-)

Many Thanks !

**Comment by cldswm** [comment]
HI was wondering if this will get implemented any time soon. thanks!

**Comment by helgoboss** [comment]
Starting to work on it now. It would enable a bunch of cool stuff, such as FX parameter pinning.

**Comment by helgoboss** [comment]
I will implement it in a slightly more simple way. Learning source/target for multiple mappings at once is not possible (nor desirable, I think) - only one mapping can be in learn mode for one ReaLearn instance at a time. Mapping tags are a technique to refer to multiple mappings at once, it's overkill and confusing to use it to refer to just one specific mapping. So I think a simple mapping picker would be better suited here. This also implies that we shouldn't use tags to refer to a ReaLearn instance - because the tag could match multiple instances. So I will provide an instance picker instead.

**Comment by cldswm** [comment]
Fantastic ! Really looking forward to this, thank you! 👍👍😄

**Comment by cldswm** [comment]
Yes I think making it simple is the best !

**Comment by helgoboss** [comment]
Woah, a bit tricky to implement, the part talking to other instances. But getting there.

**Comment by cldswm** [comment]
🫡 🌞 thank you!

**Comment by helgoboss** [comment]
This will be available in upcoming version 2.15.0-pre.1.

**Comment by cldswm** [comment]
Thanks again!  Excited to find out how it works :)

**Comment by cldswm** [comment]
Yes learn last touched would be awesome !
