### ISSUE TITLE
FR:  Allow for additional activation conditions

### ISSUE THREAD

**Issue by RattlesnakeLodge** [helgoboss/realearn#752]
Would it be possible to implement multiple activation conditions on groups and/or individual mappings?

For instance, in the group edit window, where the "Active" selection is, add a "+" box to set additional conditions.  Same with the individual mappings, a "+" icon to select to add more conditions.  With each addition, another "+" icon could be generated, to offer a great number of conditions.

Here's an example of how that would help...

-  I have mappings in a group that should only be active when "Encoder Mode" parameter has a value of 0.  That is set at the group level.
-  Some mappings in that group should be turned off when a modifier is pressed.  (By modifiers, I mean Shift, Option, Control, and Alt")  I also have some mappings that should be turned off when NO modifier is pressed.   I have the four main modifiers set, so when none are pressed, a fifth modifier "No Modifier" is activated.   That is all taken care of by the first modifier selection box in activation conditions.
-  Some of the mappings listed above should only be active when a fader is touched.  That is handled by my collection of compartment parameters toggled when their respective fader is touched.  Some other mappings should inversely be deactivated with the same fader touch.  This is all handled by the second modifier selection box.
-  NOW, I want to incorporate a third "Flip" modifier into the mix.  Flip is set as a special modifier, separate from the four standard modifiers (Shift, Option, Control, Alt).  Therefore I cannot incorporate Flip in my setup of "No Modifier Pressed".  And the problem arises, I've run out of potential activation conditions.

Does that make sense?

Sorry for potentially adding more to your to-do list.  ;-)

Robert

**Comment by helgoboss** [comment]
Have you looked into "When expression met"? This allows to logically combine any modifiers bank, even with the wildest and/or mixes.

**Comment by RattlesnakeLodge** [comment]
Aha!  Just got into "When expression met".  It does exactly what I was looking for, brilliant!  Vielen Dank!
