### ISSUE TITLE
textual feedback target.panwidth.mcu

### ISSUE THREAD

**Issue by PucksEvilTwin** [helgoboss/realearn#756]
Like target.pan.mcu but for Stereo width.

**Comment by helgoboss** [comment]
How should it be formatted?

**Comment by PucksEvilTwin** [comment]
Sorry for the incompleteness!

How Reaper does it is good.  I forget what input range you start with (iirc it defaults to 0 - 100, I used 0 to 1 below) but the output range should be -100 to 100 and Concatenated with a "W" for width.
0 = -100W
.5 = 0W
1 = 100W
