### ISSUE TITLE
Unmatched events still being sent through

### ISSUE THREAD

**Issue by valankar** [helgoboss/realearn#758]
I have the following setup on my monitoring FX to have a knob controlling the volume of a track, as well as being able to control an effect:

![global](https://user-images.githubusercontent.com/31250800/201286717-4984068b-d667-4b7f-a3bc-70fdb157e17a.jpg)

![effect](https://user-images.githubusercontent.com/31250800/201286763-53f4bd18-afe2-484c-b7fa-cc965d1b2460.jpg)

The first realearn is set to only send unmatched events. However, it seems my effect is also getting the event as well. Turning the knob changes both the track volume as well as the effect parameter:

https://imgur.com/Dm6D8du

I'm not sure if this was working in the past. Is there a proper way to do this or is this a bug? Thanks.

**Comment by helgoboss** [comment]
All ReaLearn instances that use a MIDI hardware device as input are unaffected of the filtering. All such instances have "equal priority", there's no order between them. After the incoming MIDI message has reached ALL ReaLearn instances with a MIDI hardware device input and matched at least one, it gets filtered out. It never reaches the tracks or other FX.

If you want to build a chain of ReaLearn instances where the one below doesn't receive the messages that the one above filtered out, you need to use "FX input". This works the way you want. (On the monitoring FX chain, this is not possible though.)

**Comment by valankar** [comment]
I see, thanks. I guess I will switch to track FX instead of monitoring for something like this.

I think what I really want is a Realearn instance that is controlling global things, such as selected track volume, transport, etc. (that's what the Global one does on my monitoring FX), and also a Relearn instance hat overrides the global one if an effect is selected.

I see that is possible by using track FX and ordering the Relearn instances properly. But I'm not sure how I could have the global controls still working when I don't have that track selected. Is that possible?

**Comment by helgoboss** [comment]
Ah. Then filtering MIDI is not the best approach. I think what you want is the auto-load feature! At the moment, it automatically loads presets depending on what FX is currently focused. And in the latest beta 2.14.0-pre.10, it falls back automatically to the memorized normal mappings as soon as the FX loses focus.

However, I think you want to "overwrite" normal mappings as soon as you select a track, correct? Then it's time to add a second entry to the auto-load menu called "Depending on selected track", wanted to do that for ages already. I guess the best would be to have a complete stack of overrides: Focused FX overrides selected track overrides global mappings.

But hey, there's also a completely different way to achieve what you want! You can put the global mappings in one group and the track mappings in another group.

Now we tell the first group that it should be active only if no track is selected. Edit the group, use "Active: When target value met" and refer to a (previously created) mapping with target "Track: Select/unselect" that addresses track via "Named" = "*". In the expression next to the mapping picker, enter "y <=0".

Next, we need to tell the second group that it should be active only in the opposite case: If a track is selected, no matter which one! The procedure is the same, but the expression should be "y > 0".

Both of these can be done completely in the monitoring FX chain, so globally. Solution 1 needs a new feature from my side, solution 2 is possible now already.

Let me know how it works.

**Comment by valankar** [comment]
> However, I think you want to "overwrite" normal mappings as soon as you select a track, correct?

More like "select an effect which has mappings defined."

> Now we tell the first group that it should be active only if no track is selected. Edit the group, use "Active: When target value met" and refer to a (previously created) mapping with target "Track: Select/unselect" that addresses track via "Named" = "*". In the expression next to the mapping picker, enter "y <=0".

I think this comes close. However, one of my global mappings is to control the volume of the selected track. If there is no track selected, it seems that can't work. What I am thinking is, if an effect is open which has mappings, use those and override the default mappings. This would mean the knob would no longer control the track volume if it were mapped to an effect. Once I close the effect, the knob would go back to controlling the selected track volume.

I thought your example might work with "FX: Open/close", but I couldn't figure out how to.

**Comment by helgoboss** [comment]
> > However, I think you want to "overwrite" normal mappings as soon as you select a track, correct?
> 
> More like "select an effect which has mappings defined."
>
> > Now we tell the first group that it should be active only if no track is selected. Edit the group, use "Active: When target value met" and refer to a (previously created) mapping with target "Track: Select/unselect" that addresses track via "Named" = "*". In the expression next to the mapping picker, enter "y <=0".
> 
> I think this comes close. However, one of my global mappings is to control the volume of the selected track. If there is no track selected, it seems that can't work. What I am thinking is, if an effect is open which has mappings, use those and override the default mappings. This would mean the knob would no longer control the track volume if it were mapped to an effect. Once I close the effect, the knob would go back to controlling the selected track volume.
> 
> I thought your example might work with "FX: Open/close", but I couldn't figure out how to.

Then it's more simple than I thought. "Depending on focused FX" should do exactly what you need. See the "auto-load" tutorial in the user guide.

I'll close this. Feel free to comment if you can't make it work.
