### ISSUE TITLE
Crash with modifier keys

### ISSUE THREAD

**Issue by TheSoundOfOneHandClapping** [helgoboss/realearn#762]
Reaper crash with Realearn, veryfied on a portable install with a fresh install of ReaLearn as well.

Can this be reproduced by someone else or is it just my specific system?
I can reproduce this behaviour 100% of the time.

Details:

MacOS Mojave 10.14.6
Reaper V6.70
ReaLearn 2.14.0-pre.10/x86_64

How to reproduce:
In a fresh project instantiate ReaLearn on a new track, now press one of the following keys: Shift, Ctrl, Alt or CMD, result: Reaper crashes.

Variation (if presets already exist in ReaLearn):
In a fresh project instantiate ReaLearn on a new track, click "Add Mapping" and then click "Edit". Press one of the following keys: Shift, Ctrl, Alt or CMD, result: Reaper crashes.

--- cut ----
Version:               6.70.0_309480d (6.70.0_309480d)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           REAPER [2801]
User ID:               501

Date/Time:             2022-11-16 14:56:18.322 +0100
OS Version:            Mac OS X 10.14.6 (18G9323)
Report Version:        12
Bridge OS Version:     6.6 (19P6067)
Anonymous UUID:        92E1EB44-26F7-7C2F-FECB-AAB13C5E01D7

Time Awake Since Boot: 16000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  reaper  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: reaper  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff625ac2c2 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff62667bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff625166a6 abort + 127
3   ReaLearn-x64.vst.dylib        	0x0000000120e11839 0x11fc6e000 + 18495545
4   ReaLearn-x64.vst.dylib        	0x0000000120e0b4e9 0x11fc6e000 + 18470121
5   ReaLearn-x64.vst.dylib        	0x0000000120e18bc2 0x11fc6e000 + 18525122
6   ReaLearn-x64.vst.dylib        	0x0000000120e8c619 0x11fc6e000 + 18998809
7   ReaLearn-x64.vst.dylib        	0x000000011ffa0f09 0x11fc6e000 + 3354377
8   com.cockos.reaper             	0x000000010deb07a8 translateLocalAccelerators(MSG*) + 120
9   com.cockos.reaper             	0x000000010db0477d -[REAPERapp sendEvent:] + 2781
10  com.apple.AppKit              	0x00007fff33970ccc -[NSApplication run] + 755
11  com.apple.AppKit              	0x00007fff339601c0 NSApplicationMain + 777
12  com.cockos.reaper             	0x000000010d716334 start + 52

---- cut ----

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000011d8f35c0  rcx: 0x00007ffee24ea6f8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee24ea730  rsp: 0x00007ffee24ea6f8
   r8: 0x0000000000000065   r9: 0x00000000000007fb  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x0000000000000000  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff625ac2c2  rfl: 0x0000000000000206  cr2: 0x00007fff98a96188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

---- cut ----

**Comment by helgoboss** [comment]
Interesting. I have a suspicion. Could you check if 2.14.0-pre.5 still works and 2.14.0-pre.6 breaks it? That would confirm my suspicion. Thanks!

**Comment by TheSoundOfOneHandClapping** [comment]
Good instinct!
Indeed pre.5 works as expected and pre-6 exhibits aforementioned behaviour.

**Comment by helgoboss** [comment]
Trying to reproduce it on my ancient MacBook (El Capitan). It doesn't even scan successfully on it. Last working version is 2.12.0.

**Comment by TheSoundOfOneHandClapping** [comment]
Never had a problem here on MacOS Mojave, let me know if I can help somehow.

**Comment by helgoboss** [comment]
Good news. Could make it scan on El Capitan again and reproduced the crash. Fixing.

**Comment by TheSoundOfOneHandClapping** [comment]
@helgoboss Yes, it works now as expected in v2.14.0-pre.11 (in OSMojave), thank you!
