### ISSUE TITLE
BUG: transmission of parameter to script, byte inversion ?

### ISSUE THREAD

**Issue by DaveInDev** [helgoboss/realearn#766]
Hi, just a reminder for you about the probable inversion of byte orders in the transmission of parameters to a reascript
See here 
https://forum.cockos.com/showpost.php?p=2613376&postcount=2879

**Comment by helgoboss** [comment]
Ah thanks. That's already fixed locally. Just waiting a bit until
publishing the next release.

DaveInDev ***@***.***> schrieb am Do., 17. Nov. 2022, 08:22:

**Comment by DaveInDev** [comment]
great ! have a nice day.
