### ISSUE TITLE
Reaper hangs when switching tabs with particular mapping (Playtime?)

### ISSUE THREAD

**Issue by seantypedthis** [helgoboss/realearn#768]
Discovered this bug on 2.14 pre-10 running on Windows 10 , but found it holds for 2.13 stable. 
REAPER consistently hangs when switching tabs when I have a certain Main compartment preset active referencing Playtime 1, I have attached it in json format, as well as the reaper project it is used in. 
I have 6 instances of realearn in this particular project, all insert fx, as well as one in monitoring fx, and they do not hang/freeze the application if the included  Playtime mapping is not active .

I've also gone through the mapping groups and found that if I delete all of them except for the one labeled "MISC," which does not reference Playtime,there is no freeze when switching tabs. I also tried Realearn 2.12.0, and it seemed to load a new project tab fine, but within a minute or so Reaper freezes and I must force close.

The Realearn and Playtime in question are on track 55 in the projec
[Playtime Realearn Crash.zip](https://github.com/helgoboss/realearn/files/10045198/Playtime.Realearn.Crash.zip)
t.

**Comment by helgoboss** [comment]
This looks more like a Playtime 1 issue, which I unfortunately can't maintain anymore because my focus shifted to Playtime 2 development. Sorry.

**Comment by seantypedthis** [comment]
No worries, I figured as much. I'll miss the clip launcher in Playtime 1, but really looking forward to integrating the clip engine in Playtime 2, and you're right, definitely time to move forward instead of troubleshooting to the bitter end, haha.  Thanks as always for all the stellar work!
