### ISSUE TITLE
Index Problem with Target "Browse FX"?

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#769]
I created a mapping with this target.
I noticed that I could not access the FXs of the last track.
ReaLearn inserted this default formula for dynamic track selection:

`selected_track_indexes[0]+1
`
It seems for this particular target, I would need to remove the "+1" for it to work as expected.

**Comment by helgoboss** [comment]
Mmh, there's no such thing as default formulas in ReaLearn. Maybe some auto-fill issue on your side? Or are you using a preset?

**Comment by vonglan** [comment]
I don't know where that formula came from.
I think I haven't used it before.
And I don't know of any OSX auto-completion working in ReaLearn windows.

If it is not a default, then the issue can be closed.

**Comment by vonglan** [comment]
I found the culprit, using grep: I had previously written that formula myself (long ago ;-), and then changed the mapping to a different target, but the formula was still buried in the mapping.

**Comment by helgoboss** [comment]
Haha okay. Yes, the JSON session data and presets save even values that became unused. The new Lua API fortunately doesn't.
