### ISSUE TITLE
Reapack install problem ?

### ISSUE THREAD

**Issue by DaveInDev** [helgoboss/realearn#780]
Hi, 
making tests between ReaLearn versions, I have a problem with ReaPack telling me :

> Data\helgoboss\realearn\sounds\high-click.mp3:
>   Cannot rename to target: File exists

I have to delete manually this file to achieve a version reinstall...

**Comment by helgoboss** [comment]
Oh. Which OS? Do you have ReaLearn installed for 2 architectures (x86, x64)?

**Comment by DaveInDev** [comment]
Win 10 x64.
Only 1 architecture.

**Comment by DaveInDev** [comment]
note that I have to exit Reaper to delete this mp3 file. Otherwise it said that the file is in use.

**Comment by DaveInDev** [comment]
I tried to uninstall. Then reinstall 2.14.0pre7 . No problem. Then 2.14.0 stable. Same mp3 problem.

**Comment by helgoboss** [comment]
I'll need to fix this, yes. Probably a file lock problem.
