### ISSUE TITLE
X-Touch with Realearn not reset after closing Reaper

### ISSUE THREAD

**Issue by tompad2** [helgoboss/realearn#788]
Hi!

I am not sure if this is a bug or me missing something important.

When I close Reaper the name of the tracks remain in my X-Touch displays.
After shutting down X-Touch and restart it the displays are reset to default.

Running Reaper 6.71 on Win 10 and latest Realearn (from ReaPack)

**Comment by helgoboss** [comment]
It's a current limitation / something that I haven't closely looked into yet. It's probably related to ReaLearn not getting a chance to send the messages anymore.

It shouldn't happen if you close the project while having an (empty) ReaLearn instance on the monitoring FX chain. Can you verify that?

**Comment by tompad2** [comment]
I'll try - but what do you mean by "having an empty ReaLearn instance on Monitoring FX"? I have ReaLearn on Monitoring FX, do you mean no mapping or presets loaded? Will the tracknames show up on X-Touch then?

**Comment by tompad2** [comment]
I tested to close the project by making a new project - and then the displays shift to the new track names,
but closing Reaper dont seem to make the text in displays to clear.

**Comment by helgoboss** [comment]
It's just a current limitation. ReaLearn probably doesn't have enough time to turn the LEDs off because REAPER already removed it. At the moment, you have to live with that. But we can leave this ticket open so when I get back to ReaLearn development, I can have a look at it.

**Comment by tompad2** [comment]
Ok, thanks Benjamin!
You are doing a great job!
I am collecting some money for a donation soon.

**Comment by helgoboss** [comment]
I looked into this an found a solution. Fingers crossed that this works reliably.

**Comment by tompad2** [comment]
Thanks!
Will it show up in 2.16.0-pre.8?

**Comment by helgoboss** [comment]
Yes
