### ISSUE TITLE
Add Advanced>Paste from LUA (add to group)

### ISSUE THREAD

**Issue by PucksEvilTwin** [helgoboss/realearn#789]
I've come across the desire for this a couple of times now, so it's time for a FR.

Just what it says on the tin, pasting lua code that adds to the current group instead of replacing the whole group.

**Comment by helgoboss** [comment]
Right mouse click on a mapping of that group => Paste n mappings below?

**Comment by PucksEvilTwin** [comment]
My apologies!

It just wasn't where I was looking.  I was using the menu to do this operation and only paste(replace all in group) seems to be available there.  Thanks for pointing me in the right direction!  p.s. hope everything is going smoothly with PlayTime 2!

**Comment by helgoboss** [comment]
No problem :) I'm going to close this one. Playtime is going nicely, well, as a side car only but soon full time again ... looking forward.
