### ISSUE TITLE
Realearn on Ubuntu and Fedora : fail to scan

### ISSUE THREAD

**Issue by lion-artiste** [helgoboss/realearn#797]
Hello,

It's the first time I post an issue for any software, but I recently switched from Windows to Linux, and Realearn doesn't seem to start, when installed through Reapack. It stays in the list of VST plugins that failed to scan.

![Screenshot_20230112_112954](https://user-images.githubusercontent.com/110665593/212043322-5aa00c85-5531-4a6c-9481-79d262d50bf2.png)

I had this problem on the last Fedora version, in the meantime I installed Ubuntu Studio, and I have the same exact problem.

I don't know which information would help to understand and work on this bug, so don't hesitate to ask, and I'll provide :) I heavily rely on Realearn, and I'm currently stuck.

Thank you.

**Comment by helgoboss** [comment]
Hi. It's probably a library load error. Can you try this? https://github.com/helgoboss/realearn/issues/503#issuecomment-1320964181
