### ISSUE TITLE
Transport Targets

### ISSUE THREAD

**Issue by DLongoni** [helgoboss/realearn#8]
It would be very handy to have the following targets:
- Play/stop
- Toggle Repeat
- Toggle Record
- Toggle Metronome

Especially (or even only) for feedback purposes. 
Right now Metronome, Record, and Repeat are working fine if I select the corresponding action. A minor issue I am encountering is that the repeat state is set inside a custom action, the the feedback is not triggered. I fear that the reason is that I use a SWS action for this, inside the cusrom action.
On the other hand if I press the "toggle trigger" midi device button, or if i set id from Reaper gui button itself, the status is properly sent as a feedback. 
The one I am having the most issues with is Play/Stop. I noticed that if I use a feedback only mapping with "play", then the button is lit when the project is playing, but it doesn't get turned off when the project is stopped. Do you have any suggestion for this?

Cheers, and thanks

**Comment by helgoboss** [comment]
I confirm that none of the play actions work properly with ReaLearn and that transport targets make sense to cover all use cases.
