### ISSUE TITLE
Bug? - Enabling two mappings for touch causes unusable lag

### ISSUE THREAD

**Issue by RichardJECooke** [helgoboss/realearn#801]
I installed sensors2osc on my phone and connected it to ReaLearn as shown in the screenshot below.

When I enable only one mapping for the multitouch screen (I just use it as a single touch XY pad) on my phone - either touch argument 1 mapped to expression, or touch argument 2 mapped to vibrato, ReaLearn works perfectly.

However when I enable both mappings simultaneously I get unbearable lag in the movement of the values. Is there something wrong in my mapping configuration please?  Or should I have tried to map both arguments in one mapping somehow so they don't fight with each other?  Otherwise this seems like a bug.

![image](https://user-images.githubusercontent.com/5468805/213788690-4cda1d7f-7d4f-4d3e-a34b-c2d56d6e2c5d.png)

**Comment by RichardJECooke** [comment]
Unless I've made a mistake in my configuration, which I hope someone can point out. I think this may rather be a problem with Sensors2osc's multitouch pad. I don't have the same issue with OscController Android app xy pad. And I don't have an issue using two mappings while waving a magnet above my phone - which is a fantastic solution I'm now sticking with.

**Comment by helgoboss** [comment]
Using two mappings is the correct approach here. The mappings look alright.
