### ISSUE TITLE
FR: Organize the periodical or cycle of undepended LCD-assigment feedback of bank position

### ISSUE THREAD

**Issue by Vladistone** [helgoboss/realearn#804]
How to show both the MODE-keys condition and the current track bank number, on the small LCD-assigment display?
for exsample:
- I want it to show for example 5 seconds the send bus number and 2 seconds the bank number.

**Comment by helgoboss** [comment]
We solved that already: https://forums.cockos.com/showpost.php?p=2639513&postcount=3172
