### ISSUE TITLE
When assigning output to named FX plugin and selecting "All Selected Tracks" only first track responds

### ISSUE THREAD

**Issue by larryseyer** [helgoboss/realearn#807]
When selecting multiple tracks, each with the same FX plugin in the same location and Realearn told to control the same parameter in each one of those FX on each selected track, Realean only controls the FX plugin on the first track.

**Comment by larryseyer** [comment]
This is Mac OSX running on an M1 16 Gb and 1Tb storage.  OS is Big Sur.  DAW is Reaper.

**Comment by helgoboss** [comment]
Works for me: https://imgur.com/a/xLr6pQX

Probably you didn't use "All named"? Anyway, please reopen if you still experience the issue.
