### ISSUE TITLE
Is it possible to set the target FX plugin as a “fixed parameter” in ReaLearn?

### ISSUE THREAD

**Issue by pineweevil** [helgoboss/realearn#81]
I tried to control graphic EQ on a selected track using ReaLearn. It works fine on a selected track where the graphic eq plugin is loaded. However, when I select another track, Realearn will control whatever plugin which is loaded on that track. I would like to make it possible so that Realearn only controls a specific plugin on selected tracks and doing nothing on tracks where the plugin is not loaded. Is it possible? Did I miss something? I read the manual but still can’t get this right. (I  just hope this is the right forum to ask such questions :) )

**Comment by helgoboss** [comment]
Which version are you using? In 1.12.0-pre8, you can choose an FX anchor: ID, position or name. In your case, "Name" would be the best I think. Then whenever you have an FX in your chain that has the same name, it will use it and otherwise do nothing. Let me know if it works.

**Comment by pineweevil** [comment]
Thanks for a quick reply!

You are right! I downloaded reapack and realearn just a couple of days ago as I stumbled upon your ReaLearn tool. For some reason, however, I’ve got an old version (v1.11.0 x86_64 rev edfe64 (2020-09-16 19:02:36 UTC)).

I managed to download the latest version (v1.12.0pre8), found the option you suggested (FX: ID/name/position/ID or position), selected “Name” and it solved the whole problem!

Now, when the track is selected and the target plugin is not loaded there, the MIDI mappings in ReaLearn are greyed out and inactive! That’s genius!

I even managed to add and control a second plugin and switch between the two using modifier/bank. That's exactly what I was trying to achieve!

Thanks a lot for solving this problem!
And thanks a million for sharing this great tool!

**Comment by helgoboss** [comment]
Glad it works! v1.12.0-pre8 is a prerelease (a kind of beta version), that's why it isn't picked automatically. Hope to release the final v1.12.0 soon.
