### ISSUE TITLE
Linux support lost?

### ISSUE THREAD

**Issue by tompad2** [helgoboss/realearn#817]
Hi!

I have a linux machine I test some thing on sometimes (I mostly work in Windows).
This day when I start Reaper and wanna open Realearn 2.14.3 it dont load in Ubuntu.
Trying to remove and add again to FX chain is not possible because Reaper
dont list ReaLearn in FX list. Trying to reinstall ReaLearn 2.14.3 with ReaPack make
no change. Updating Reaper from 6.69 to 6.75 make no change. 

Is the support for linux changed?

Regards
Thomas

**Comment by helgoboss** [comment]
`sudo apt-get install -y libxdo-dev`, see updated installation instructions.

**Comment by tompad2** [comment]
Splendid!

Thanks, I missed the updated installation instructions totally.
