### ISSUE TITLE
(Already Implemented!): MIDI monitors for input, output

### ISSUE THREAD

**Issue by mccrabney** [helgoboss/realearn#821]
while diving into ReaLearn i find myself missing a MIDI monitor screen: both to watch/troubleshoot what's coming in, and to watch/troubleshoot the feedback that is going back out.

since ReaLearn takes over the MIDI device, we can't use a normal REAPER track to observe the MIDI with another monitoring VST/JSfx - otherwise, i'd do that. 

if you're looking for inspiration, bidule has a 3-panel OSC monitoring window that would work well as a ReaLearn MIDI monitor. In bidule, one panel is for processed incoming messages (messages tied to mappings), another panel is for non-processed incoming messages (messages not yet tied to mappings), and the last panel is for outgoing messages.

**Comment by helgoboss** [comment]
There's logging, see the menu.
