### ISSUE TITLE
Removal of hardware sends with poll element causes endless error loop in Reaconsole (bug)

### ISSUE THREAD

**Issue by 7enz** [helgoboss/realearn#838]
i have been modifying my template with my realearn instances...
and what i picked up on.. based on the Poll use

is that if you have a send that is polled and then decide to remove the send from using Reapers internal routing matrix ...
it would naturally come up with a error message in the console.. as the polling is relying upon there being a existing send by which it can gather the state

however removing it... goes through the error and
deny's access to realearn instance to remove the offending poll midi source... forcing you to close down and reload which isnt a bad thing..

but i think this is something that should be mentioned in the userguide perhaps??
from memory polling option can sometimes be a default in some options, thus people not being aware of the issue of poll and what it does will be oblivious to any removal of what the poll tickbox does and is tied with... and how it can error out.. if the poll is reliant upon a event being still in existence even though i have removed it

in my case, i was using the poll as a send... so that i know a hardwareout-send is in use& a toggling LED is lit (a very useful option in my view)
upon removing the hardware send within Reapers routing matrix for modification purposes... the reaconsole kicks in alerting me to a send type error message.

i dont know what can be done at the point of the reaconsole error message showing as it goes in a continous loop(understandably)

but i do think a userguide mention of the occurrence might be in order?? *shrugs

**Comment by helgoboss** [comment]
Analysis: Tried with "Send: (Un)mute". Usually, ReaLearn listens to `HardwareOutputSendCountChanged` (which reaper-rs `ChangeDetectionMiddleware` can emit whenever REAPER calls `SetTrackListChange` on `IReaperControlSurface`). It re-resolves targets in response and therefore prevents targets holding on to removed hardware sends. It works the same way with track-to-track sends (`TrackSendCountChanged`). However, the difference is that REAPER reliably calls `SetTrackListChange` when a track-to-track send is added. But it doesn't reliably call `SetTrackListChange`when a hardware output send is added. As a consequence, the removal of a hardware output send is not detected as a change and the targets are not re-resolved. Therefore, they can hold on to removed hardware sends. This in turn can lead to errors. When polling is enabled, the error gets very obvious because ReaLearn repeatedly queries the send mute state.

**Comment by helgoboss** [comment]
I reported this to Justin.

That said, there are some ways to fix the problem in ReaLearn directly:

- a) Not panicking when getting the current send mute state fails (probably a good idea anyway). The same goes for target invocations, they might also still panic when the send isn't present!
- b) Add hardware output send count change detection by using polling.

Option (a) would *not* turn the mapping inactive though. That means an LED connected to it would not turn off when the send disappears. Or maybe it would? Need to check what's the current behavior whenever targets fail to report the current value. Anyway, it would be a good enough solution to prevent the error from popping up, that's for sure.

Option (b) would be a workaround for a REAPER inconsistency ... let's see if Justin considers fixing it. If not, I might consider this.

**Comment by helgoboss** [comment]
I did (a), with all send targets, both for value retrieval (feedback) and value setting (control). So in upcoming ReaLearn version 2.15.0-pre.2, the error shouldn't occur anymore.

Also, Justin confirmed he would fix the notification on REAPER side. So in one of the next REAPER dev versions, it should also be fixed. And ReaLearn should become aware of the removed hardware output send and inactivate the target and mapping accordingly (making any attached LED turn off).

**Comment by helgoboss** [comment]
> Option (a) would _not_ turn the mapping inactive though. That means an LED connected to it would not turn off when the send disappears. Or maybe it would? Need to check what's the current behavior whenever targets fail to report the current value. Anyway, it would be a good enough solution to prevent the error from popping up, that's for sure.

A bit more about the use case "Have LED on if send exists and have it off when it doesn't exist". In general, this can be easily done by using a send target, e.g. "Send: Set volume" and writing "x = 1" into the "Numeric feedback: Transformation (EEL)" field. Then the LED will light up if the send exists, no matter the actual volume (it can also be -inf). It will automatically switch off when the send is removed. This works for sends to tracks already. It will work correctly for sends to hardware outputs as soon as Justin integrates his fix.

The errors should be gone in pre.2, no matter what.
