### ISSUE TITLE
disable inlay control

### ISSUE THREAD

**Issue by SvenVinat** [helgoboss/realearn#839]
Hello everyone,
I used Realearn to control the "sends volumes" on a project but since the control activates permanently as soon as I open Reaper while realearn is not open on any track. The concern is that it tends to lower the send volume of each track that I select to a minimum. I searched the Helgoboss site and the user guide for solutions but couldn't find anything to help. I uninstalled realearn but that didn't change anything. I tried to redo a setting of realearn then to deactivate it but it remains active.
I would like to avoid uninstalling and reinstalling Reaper if possible, especially without being sure that it won't fix my problem.
Has anyone had this problem before and does anyone have a solution ?
Thanks in advance !

**Comment by helgoboss** [comment]
You mean ReaLearn does something even it's not installed anymore? That's impossible.

1. Are you sure it's caused by ReaLearn?
2. If yes, maybe you put ReaLearn on the monitoring FX chain and it's still there?

**Comment by SvenVinat** [comment]
maybe I uninstalled it wrong but anyway it is active even when the plugin is not inserted on a track of the whole project :/ (in the best case I would like to keep realearn but that it only activates when I insert it on a track and give it instructions)

On the capture we see that I have already uninstalled realearn in the reapack manager and on the right screen we see that the "send" button is down while I just selected the track without touching the "send" button.

![Capture realearn](https://user-images.githubusercontent.com/129741628/229502037-6addf7e1-ea2a-4833-a1bc-8389c8864c40.png)

**Comment by SvenVinat** [comment]
So,
"1- Are you sure it's caused by ReaLearn?"
I don't know but the problem started exactly when I first configured the VST to manage a send with a MIDI controller.

"2- If yes, maybe you put ReaLearn on the monitoring FX chain and it's still there?"
on the capture that I attached above there is no Realearn or other plugin inserted, neither in the monitoring track nor in any track.

**Comment by helgoboss** [comment]
I don't think ReaLearn is active in any way in your project. I see no traces of it. If you want to be sure, just check View / Media FX bay (or something like that) and then open the FX tab. It shows all plug-ins currently loaded.

You might unknowingly have made a change in the REAPER preferences that causes the behavior that you see. Or maybe you made a change via ReaLearn that affects sends from the master track to the audio hardware outputs, I think this also persists across projects. Or you executed a REAPER action which changed a global REAPER preference. I can't tell from the screenshot what sends are at work there.

Just one thing I can tell you for sure: If ReaLearn isn't loaded, there's no way it has any influence anymore. You might have success resetting the REAPER configuration (try by temporarily renaming reaper.ini).

**Comment by helgoboss** [comment]
Then ... that's not really a command. It must be a preference. And I can't tell you which one it is. What exactly is it doing? What's the effect of that "command"? Trying to help here, but please know that this is not ReaLearn territory anymore. It's a REAPER question. You might have more success in the REAPER forum.

**Comment by SvenVinat** [comment]
@helgoboss 
Ok I'll keep looking for a solution, maybe totally reset Reaper. I thought that maybe there would be an action to reset Realearn or completely uninstall it from the pc, since that's exactly the setting I made in the vst realearn that has remained active since. Anyway, thank you for your answers and the time you gave me.
