### ISSUE TITLE
Play/stop and Play/pause target work only once

### ISSUE THREAD

**Issue by DLongoni** [helgoboss/realearn#84]
Let's say I map transport -> play/pause or transport -> play/stop to a button. Then I press that button, and the project plays. I press again, and the project pauses (all good). Then I press again and nothing happens anymore until I "manually" play via keyboard or mouse the song. After that, the mapped button will work again, but only once. Am I missing something or is it an actual bug?

Cheers

**Comment by helgoboss** [comment]
I can't reproduce this. Which version? You use Mode "Toggle buttons" (previously called "Toggle"), right? Attach a minimal RPP or at least the ReaLearn state ("Export to clipboard") so I can check.

**Comment by DLongoni** [comment]
So I tested again. The problem happens only with Play/Pause, and not with Play/Stop, sorry. I thought I tested it, but I must have gotten confused.

So this is what I did:

Using buttons in momentary mode on my device (behringer x touch compact). In behringer language this means that on button press the device sends 127 as CC value, and then on button release the device sends 0 as CC. 
So if I map it as mode "normal" on ReaLearn the behavior is what I'd expect: press and hold: the song plays. When I release, the song pauses. Problem is, if I do it a second time nothing happens.
So i tried to set min source = 10, ignore out of range, and mode = toggle. This time I had: press-> play. release ->nothing happens. press again->pause. release again-> nothing. Exactly what I expected. Problem is, once again, it only works once.

{
  "id": "QEL_cy9m",
  "controlDeviceId": "9",
  "feedbackDeviceId": "9",
  "mappings": [
    {
      "id": "ff274dba-aaf6-44f6-bae1-2558632c22bc",
      "name": " ",
      "source": {
        "number": 56,
        "character": 1
      },
      "mode": {
        "type": 2,
        "minSourceValue": 0.07874015748031496
      },
      "target": {
        "type": 16,
        "transportAction": "playPause"
      }
    }
  ]
}

Thanks!

**Comment by helgoboss** [comment]
I imported your export and it works flawlessly with my MIDI Fighter Twister (which sends the same on/off messages). Can you turn off feedback and see if it works then? Some controllers unfortunately think they must be extra clever and decide what to do based on the feedback value.

**Comment by DLongoni** [comment]
Tried with and without feedback, behavior is identical. I share your disappointment towards extra clever controllers. Here's reacontrolmidi log, identical for the 2 case (feedback on and off):

0: B0 38 7F [CC56 LSB] chan 1 val 127
1: B0 38 00 [CC56 LSB] chan 1 val 0
2: B0 38 7F [CC56 LSB] chan 1 val 127
3: B0 38 00 [CC56 LSB] chan 1 val 0
4: B0 38 7F [CC56 LSB] chan 1 val 127
5: B0 38 00 [CC56 LSB] chan 1 val 0

So here's what happens:
0: button press -> play
1: release -> nothing
2: press -> pause
3: release -> nothing
4: press -> nothing
5: release -> nothing

So here's the new thing I discovered... At first I thought that the play/pause button was not active anymore.. Now I noticed that the whole ReaLearn is not working anymore until I play (spacebar or UI button mouse click) the song. I fear didn't make myself clear. Button click 1 -> play, button click 2-> pause, after that realearn doesn't respond anymore. I have to play the song, and then all the mappings start working again.

**Comment by helgoboss** [comment]
That's interesting. It's something totally else then. I think I need your RPP and reaper.ini file.

**Comment by DLongoni** [comment]
Alright, I tried making a minimal example. 

RPP
https://drive.google.com/file/d/1A4cjB_eUBcA29hiQaZhR3n-YB-XIMRoU/view?usp=sharing

Reaper.ini
https://drive.google.com/file/d/1f_CdvNHQ4M0iaJpCfMLmFLmNXUkRL6UN/view?usp=sharing

**Comment by helgoboss** [comment]
I can reproduce it. Looking into it.

**Comment by helgoboss** [comment]
It seems like REAPER is stopping the VST processing when the transport is paused *and* the track is not armed. Workaround: Arm the track. Will have a look if this can be prevented somehow.

**Comment by DLongoni** [comment]
I confirm that if I arm ReaLearn track then play/pause is working properly!

**Comment by helgoboss** [comment]
This is solved in upcoming pre9. ReaLearn doesn't rely anymore on the VST processing method to be called. Instead it hooks into REAPER's audio processing now. A fact that we could use to remove another restriction as well: That ReaLearn doesn't send feedback if on the input FX chain and the track is not armed (not done yet).
