### ISSUE TITLE
FR: Projection view within Reaper

### ISSUE THREAD

**Issue by jmacmusic** [helgoboss/realearn#845]
It would be great to have a script that displays the projection in some kind of dockable format within Reaper so you don't have to use a mobile device or the web app. Not sure if this is already possible but I can't find anything about it.

**Comment by tompad2** [comment]
+1

**Comment by helgoboss** [comment]
Projection will become a free part of the Playtime app. It will be possible to open it from within REAPER *but* it will not be dockable. It's just a floating top-level window that you can show and hide. Making it dockable ... maybe in more distant future, not sure if it's even possible with the technology mix that I use.

**Comment by helgoboss** [comment]
Update: Latest pre-release has projection within REAPER as part of the Helgobox app (no browser necessary anymore). Projection of current feedback values doesn't work yet, still need to fix that.

As soon as the Helgobox app becomes dockable (hopefully in the future), the projection view will of course also be dockable.
