### ISSUE TITLE
Please create a controller layout!

### ISSUE THREAD

**Issue by nekoshang** [helgoboss/realearn#848]
I have a controller `json` at `<PATH TO REAPER>\Data\helgoboss\realearn\presets\controller` but when I browse to the Realearn companion, the message says *Please create a controller layout!*. Having spent a long time creating the controller layout in the first place, I didn't really want to start again from scratch. Is this is a bug? If not, can I import the `json` at this stage anyway somehow?

I am on Windows 10, Realearn v2.14.3, Reaper 6.79, Firefox. An important point is that I am using the portable version of Reaper so the path is in an unusual location. I also had to mess about with some uBlock origin settings (Firefox addon) in order to get the Realearn companion to load so there may be something more there.  

Any help would be appreciated.

**Comment by helgoboss** [comment]
Attach the controller JSON and I will have a look.

**Comment by nekoshang** [comment]
[fcb1010.json.txt](https://github.com/helgoboss/realearn/files/11365011/fcb1010.json.txt)
Thx. Had to rename it in order to upload.

**Comment by helgoboss** [comment]
Okay. This controller file doesn't contain any layout. A layout is a visual arrangement of control elements in the projection app. Are you sure you have built one (in the projection app)? You need to press the pencil button and then drag and drop the circles from the palette onto the canvas. Make sure to press save often.

**Comment by nekoshang** [comment]
Yes, I am pretty sure I did that. Now it may be that on transferring to a different device I lost something. What does this `json` contain then if not the layout? I can look in the same folder for other potential candidates. How would I know it is a controller layout? Thx

**Comment by helgoboss** [comment]
The JSON file you sent me contains the controller mappings. That's the part you build in ReaLearn, not in the companion app. If you successfully saved a layout for that controller in the projection app, the *same* JSON file will also contain a section that looks a bit like this:

```json

  "customData": {
    "companion": {
      "controls": [
        {
          "height": 32,
          "id": "0aa55949-ea14-404e-b3af-3c8a85ed50c7",
          "labelOne": {
            "angle": 0,
            "position": "center",
            "sizeConstrained": true
          },
          "labelTwo": {
            "angle": 0,
            "position": "belowBottom",
            "sizeConstrained": true
          },
          "mappings": [
            "ab332c71-6d32-40c2-9ca7-cb018012fef7"
          ],
          "shape": "rectangle",
          "width": 96,
          "x": 256,
          "y": 0
        },
```

Good luck!

**Comment by nekoshang** [comment]
Got it, Thx!
