### ISSUE TITLE
Enhancement : Default autoload preset when (any) plugin is focused 

### ISSUE THREAD

**Issue by dissofiddle** [helgoboss/realearn#871]
Hi, 

Auto-load based on a link between a plugin and a realearn preset is great. 
However, most of the time the same realearn preset is fine for  lots of plugins.

For instance, my encoders 1-8 are set to  control faders when no plugin is focused, and are set to control parameters 1 to 8 when a plugin is focused. In this case auto-load is great but I don't need a different realearn preset for each plugin, and setting a link for this preset to every plugin is not feasible.   There are still specific cases where  I need the encoders to control a different set of parameters, but most of the time 1 to 8 is ok (like with JS plugins).

A good idea would be to have a "default autoload  preset" that would load when any plugin is focused except the one manually linked.

**Comment by helgoboss** [comment]
If I understand you correctly, that should work already. Whenever you set "Auto-load" to "Based on instance FX" (with instance FX being the focused FX by default) and no plug-in is focused, it will fall back to the mappings that you defined for that instance before activating "auto-load".

Please reopen if you meant something else.
