### ISSUE TITLE
Midi: Send Message: add "Track must be selected" checkbox 

### ISSUE THREAD

**Issue by NickAllott** [helgoboss/realearn#878]
I would use this a lot for instances of ReaLearn on a track input. 

To go even further, a "Next FX must have Focus" checkbox would be great as well!

Midi send message track inputs are great for when I want to insert modified midi into a plugin from a device (to access some parameters that are tricky or unavailable otherwise), and also avoid recording it in a CC lane (So I can record automation only while playing instead).

Currently I need to manually toggle them on and off when changing tracks.

**Comment by NickAllott** [comment]
Regarding the “Next FX must have focus" button idea:  A drop down menu, to choose any input FX or track FX on that same track would be better.

**Comment by helgoboss** [comment]
There's already a way to do that: https://github.com/helgoboss/realearn/blob/master/doc/user-guide.adoc#when-target-value-met (target-based conditional activation).

You need to create a source-less mapping named "FX is open" with target "FX: Open/close", pointing to the FX in question. Then you go to the mapping with the "MIDI: Send message" target and set "Active" to "When target value met", picking the previously created mapping "FX is open" and entering the expression "y > 0" (which is like saying "when FX is open").

**Comment by NickAllott** [comment]
Thank you, I tested this out and it does it all.
