### ISSUE TITLE
Bug: midi feedback: When decrementing bank selection, on_deactivate gets called *after* next bank's on_activate 

### ISSUE THREAD

**Issue by AntoineBalaine** [helgoboss/realearn#879]
Hello, 

Hope this message finds you well. Here's a little bug I'm encountering:

### setup
- Midi Fighter Twister,
- realearn 2.15 and 2.16 pre-release - tested on both
- Macos Mojave and Arch Linux - tested on both
- Controller compartment: MFT preset from reapack
- Main compartment: 
  1.Lua script with one bank per trackFX, one knob assigned per FX param, each knob triggers its own color upon activation, and **triggers black color upon de-activation**. This is so LEDs don't keep glowing when switching banks, if they're not newly assigned to a param.
  2. side buttons trigger bank-select nextPage/previousPage 

##### steps:
- create mapping (lua script for this can be [found here](https://github.com/AntoineBalaine/reaper-keys/blob/bc3eb1bf75f19b6e006e5440fe5dc6663124e587/internal/custom_actions/MFT.lua#L177)) 
- load mapping by «import from clipboard»
- use the side buttons

##### Result: 
- Upon incrementing banks (i.e. hitting the «next page» button), the LEDs update correctly to reflect the active encoders. Let's say going from Bank1 to Bank2:
  1. Bank1's «on_deactivate» gets called, shuts off its knob's LEDs
  2. Bank2's «on_activate» gets called, turning on its knob's LEDs
- Upon **decrementing** banks («previous page» button), let's say going from Bank2 to  Bank1: 
  1. Bank1's «on_activate» gets called, its LEDs turn on
  2. Bank2's «on_deactivate» gets called, Bank2's LEDs turn off, leaving some of Bank1's knobs un-lit. 

![realearn_deactivate](https://github.com/helgoboss/realearn/assets/54488126/3ab9bebc-cff5-4926-bdf4-c096b07b11bd)

I'm not quite sure why this is, but it seems that the order of evaluation for active/inactive mappings' feedbacks doesn't follow the Bank selection. Is there a work-around, or is this actually a bug?

Best, 

Antoine

**Comment by helgoboss** [comment]
Are you sure you need on_activate and on_deactivate? Usually, switching LEDs on/off should all happen automatically when changing banks. I couldn't look into it further because the Lua script you linked to can't be imported by ReaLearn.

I'm not sure now how on_activate and on_deactivate were supposed to work in terms of order of execution, need to check.

**Comment by AntoineBalaine** [comment]
Sorry my script didn't work with a simple copy/paste - lesson learned, I'll keep it clearer for next time.
 
**You're right**: the work around is to not use on_deactivate. 

The reason why I wanted to use both on_activate and on_deactivate was for those of the pages that have some empty mappings. 
**use-case**: page1 will be FX1 and might use 16 encoders and LEDs, page2 will be FX2 with 5 encoders and LEDs. If I go from page 1 to page 2, the 11 encoders that are unused remain lit with page 1's LEDs - which can be confusing. 

As a work-around, I abandoned on_deactivate and now i just fill the empty slots of each bank with dummy mappings that have black (un-lit) LEDs. Problem solved. 

I thought of this work-around _after_ opening this issue (ideas popping-up in the shower after hours of being stuck on code, etc.). Given how easy it is, I don't know that the order of evaluation for on_activate/on_deactivate deserves much urgent attention, tbh. There's other few small bugs for which I'd like to open a ticket too (such as realearn having trouble reading from Linux's clipboard), if that's ok. 
I can close this in the meantime - but thanks a lot for your response!

Cheers
