### ISSUE TITLE
Send OSC on Program Change MIDI item

### ISSUE THREAD

**Issue by LXKsound** [helgoboss/realearn#921]
Hi, I‘m trying to send OSC messages triggered by a Program Change MIDI items on a track. I can select MIDI Program Change in the source window and also define the MIDI channel, but I can’t select the program number on which the OSC message should be sent. So when I select Program Change as source, the OSC message got sent on every PC. What did I miss?

**Comment by helgoboss** [comment]
There are 2 program change sources, one lets you pick a specific value.

Alternatively, you can always use source min/max with ignore behavior.

**Comment by LXKsound** [comment]
Great, thank you so much!
