### ISSUE TITLE
Playtime 2 - Early Access - Feedback

### ISSUE THREAD

**Issue by PlayGoals** [helgoboss/realearn#922]
### Discussed in https://github.com/helgoboss/realearn/discussions/897

<div type='discussions-op-text'>

<sup>Originally posted by **helgoboss** December 22, 2023</sup>
Hi Playtime 2 early access users,

feel free to give Playtime 2 early-access-related feedback here. Alternatively, you can respond to me directly by email.

Benjamin</div>

**Comment by PlayGoals** [comment]
Hello helgoboss, 

I'm not sure if I'm doing this right, but here goes. Using Alpha Milestone 6 on my Windows 11 4096x2160 system.
I have the following problem, 

Using a project I saved using Milestone 5, I saved it under a new project name using Milestone 6
When I open the new project, I press the Playtime toolbar icon and it opens a new empty Realearn instance.
The old project opens and works fine.

Let me know if this is preferable to the emails I've been sending.

Than you

**Comment by helgoboss** [comment]
> Hello helgoboss,
> 
> I'm not sure if I'm doing this right, but here goes. Using Alpha Milestone 6 on my Windows 11 4096x2160 system. I have the following problem,
> 
> Using a project I saved using Milestone 5, I saved it under a new project name using Milestone 6 When I open the new project, I press the Playtime toolbar icon and it creates/opens a new empty Realearn instance. The old project opens and works fine.
> 
> Let me know if this is preferable to the emails I've been sending.
> 
> Thank you [harrywhalen@aol.com](mailto:harrywhalen@aol.com)

Thanks. You are doing it right.

I will look into it. Maybe there's an issue with the project being in another folder and referencing files from the old project.

**Comment by PlayGoals** [comment]
I like to add that I tried starting a completely new Playtime session.
I pressed the Playtime toolbar icon added two rows of drum beats, then saved the project.
Restarted Reaper, loaded the project, pressed the Playtime toolbar icon...it opened a new instance of Playtime.
No way to access what I had done...YMMV.

**Comment by helgoboss** [comment]
Can you send the project on question to my email address? The one that doesn't load.

**Comment by PlayGoals** [comment]
Hello helgoboss,

I've noticed that in pre14 the Helgobox VST Main preset box always specifies <none>, even though I've set one.
What I'm doing is...

I start Reaper, press the Playtool toolbar icon, select the Helgoboss VST, set Main preset box to Factory/Generic them save as...

Quit Reaper, Restart Reaper, open the project...Helgoboss has the Main preset box set to <none>

**Comment by helgoboss** [comment]
Closing this issue because it's hard to keep track when switching between email/issue. Sent you an email.
